### ISSUE TITLE
Mapped column appears twice in combobox selection

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1014]
Trying to record the Ranorex tests for Observed Data 
Importing a file and opening the combo box for Molecules
![image](https://user-images.githubusercontent.com/1041237/117715098-d2d7a480-b1a5-11eb-9a81-1677eca0340b.png)

Select Notes (it is one column of the file)

Two things happened:

1: A bunch of entries are now "Noting Selectable" instead of "None" , why?
2: Notes is visible twice

![image](https://user-images.githubusercontent.com/1041237/117715234-fef32580-b1a5-11eb-8c9e-4db901cc973c.png)

**Comment by abdelr** [comment]
This fix broke the app. It is no longer possible to manually edit the molecule.
