### ISSUE TITLE
Icons does not disappear when going from a mapped column to NONE

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1015]
following the last issue #1014 
If I click on the X to remove the mapping

![image](https://user-images.githubusercontent.com/1041237/117715464-4bd6fc00-b1a6-11eb-85d2-3510a2f57f44.png)

None is selected but the icon is still there

Also would it be possible to add "<None>" in the list to UNDO the selection? Or was it excluded by design?

**Comment by abdelr** [comment]
Looks like it was related to the same problem since it no longer happens. The empty space was indeed suppressed by design.
