### ISSUE TITLE
Why is this file not valid?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1017]
PK-Sim®

The file: 
 
'C:\tests\RanorexTestData\ObservedData.xlsx' 
 
that you are trying to load does not comply to one of the supported formats.
You can find a documentation of the supported formats here: https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/import-edit-observed-data#supported-formats

![image](https://user-images.githubusercontent.com/1041237/117718818-9d818580-b1aa-11eb-9ae3-feee76abd8d5.png)

[ObservedData.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6454751/ObservedData.xlsx)

Two things:
I would first like to understand why this is not valid

Second: Add a button to send the user to the documentation URL instead of just OK

**Comment by msevestre** [comment]
even this one

[toto.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6454846/toto.xlsx)

WTF?

**Comment by PavelBal** [comment]
1) Specifying what is invalid: not for V10
2) Add a button or a hyperlink to the documentation in the message.

**Comment by msevestre** [comment]
This is done at least for 2. 
We can reopen if we want 1
