### ISSUE TITLE
Default Error type is Arithmetic when no unit is availalbe in the column. It should be geeometric

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1018]
Loading the file attached should default to Geometric error and not arithmetic

![image](https://user-images.githubusercontent.com/1041237/117722001-8b094b00-b1ae-11eb-8d6e-a20b608f9a92.png)
[ObservedData.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6454857/ObservedData.xlsx)

**Comment by msevestre** [comment]
In the case of Geometric error, the display is subpar

![image](https://user-images.githubusercontent.com/1041237/117722163-bb50e980-b1ae-11eb-976b-7b174dc72255.png)

We should not mention unit in my opinion

**Comment by PavelBal** [comment]
- If no unit defined -> Error is geometric by default, but the user can change to arithmetic by selecting a unit.
- Remove units from grid if error is geometric
- If the unit of the measurement comes from a separate column -> 
- 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File href="file:///C:/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List href="file:///C:/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Concentration | Unit | Error
-- | -- | --
0 | µmoll/l |  
10 | µmoll/l |  
10 | µmoll/l |  
10 | µmoll/l |  


</body>

</html>
-> Still geometric

Describe the behavior in documentation!

**Comment by georgeDaskalakis** [comment]
The issue is fixed, but just a note on the last part of Pavel's comment: for such a file the error is correctly set to Geometric, but the concentration unit is not automatically mapped to the "Unit" column.
