### ISSUE TITLE
Replace all the SmartXLS usages that have been left

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/OSPSuite.Core#1022]
@georgeDaskalakis commented on [Mon May 10 2021](https://github.com/Open-Systems-Pharmacology/MoBi/issues/559)

SmartXLS is still being used in MoBi for import of some things (like Molecule Start Values ). This should be replaced with the use of npoi.

**Comment by georgeDaskalakis** [comment]
I phrased this wrong: the remaining SmartXLS references have been removed from MoBi and npoi is being used instead - still I was thinking that it makes no sense to have in MoBi a reference to npoi - so I am moving that to Core and providing the Excel reading in MoBi as a service. 

Sorry for the misunderstnding because of the bad phrasing.

**Comment by msevestre** [comment]
oh ok. I was starting to freak out a little bit:)
