### ISSUE TITLE
Alignment is off for Extra data fields

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1026]
![image](https://user-images.githubusercontent.com/1041237/117871917-f8c77c80-b26b-11eb-8c75-987983ba348e.png)

* The two combo box should align right
* The text Unit should align left with the top combo box
* Why is there such a gap between unit and combobox?

**Comment by msevestre** [comment]
Since the Header is already saying Units, why do we need also unit? Can it be something else?
And should not the header say "Unit" in that case?

**Comment by georgeDaskalakis** [comment]
We also have the Dimension and Column selection here sometimes (according to what exactly is being opened). We could rename "Units" to "Unit Settings" or "Unit Configuration" .
