### ISSUE TITLE
setValuesByPath

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1038]
@msevestre May I also have a method for setting a value of a Quantity from path? :D

**Comment by msevestre** [comment]
?

**Comment by PavelBal** [comment]
In addition to already implemented

```
BaseUnitNamesFromPath
DimensionNamesFromPath
IsExplicitFormulasFromPath
AddQuantitiesToSimulationOutputFromPath
```

I also need a similar way to set values of quantities by path without creating the objects. Just wanted to make sure it is ok to keep adding such methods.

Why do I need it now - I just realized that I forgot to *set* the values in the steady-state example. Doing it the old way (creating Quantities from path) has the same dramatic performance effect.

**Comment by msevestre** [comment]
oh I see. 
Well those are very low level method. I would not expect a lot of people to use them to be honest. To decide whether it makes sense to update the setValue method to use this one instead

**Comment by PavelBal** [comment]
Ok, I will implement it tomorrow then.
