### ISSUE TITLE
Duplicated Study Id and no Group Id anymore

### ISSUE THREAD

**Issue by abdelr** [Open-Systems-Pharmacology/OSPSuite.Core#1050]
Study Id is duplicated in the list of meta data and Group Id is not in the list anymore. I think Group Id was renamed to Study Id. If I am mistaken please let me know so we could restore it. In any case either we rename the second Study Id to Group Id or we remove the second Study Id.

**Comment by PavelBal** [comment]
I think it should be Study Id and Group Id, so rename the second "Study Id" to "Group Id".

**Comment by msevestre** [comment]
Why is STUDY_ID gone here
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/pull/1051/files#diff-abcadd7dd5adb4abea7aeaf6e05b9b5d71716b87101c4616414b1334c424593eL70
