### ISSUE TITLE
Cannot import Ontogeny file (Ranorex test data)

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1065]
Trying to run the ranorex tests for PK-Sim. Importing Fraction Data does not work as expected

![image](https://user-images.githubusercontent.com/1041237/120080981-1d538f00-c089-11eb-89ca-8b7aeb491953.png)
[OntogenyImport.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6565166/OntogenyImport.xlsx)

Even if trying by hand, I cannot select the empty unit!
![image](https://user-images.githubusercontent.com/1041237/120081022-4f64f100-c089-11eb-9257-f6168d1a1702.png)

**Comment by msevestre** [comment]
FYI @Yuri05  @PavelBal

**Comment by georgeDaskalakis** [comment]
I deally "dimensionless" should be automatically identified form the file when there is no unit in the fraction header. 
In the current implementation, empty unit is missing from fraction dimension, and for dimensionless, although empty unit is allowed and also default it still does not exist in the list of units.

Also, it seems that the list of units simply gets larger when we select fe dimensionless, we also see all the units for concentration. (could be really just a RefreshAllLists for the view)

**Comment by PavelBal** [comment]
Yes, but also the dimension "Fraction" should offer an empty unit.

**Comment by georgeDaskalakis** [comment]
@Yuri05 @msevestre @PavelBal I have implemented the change, but I have two questions:

In the list of dimensions there are almost always the following available dimensions. This is OK, right?
![image](https://user-images.githubusercontent.com/37107428/120352282-eab3cb80-c300-11eb-868a-efc9a106db0d.png)


Also, more importantly, if the measurement header has no unit, in the format with unit on the headers, the dimension "Dimensionless" will be automatically selected - even if the column is called fraction. is this OK? Of course, if the user wants to change this to "fraction" it is still possible.

**Comment by msevestre** [comment]
@georgeDaskalakis 
Dimensionless is a valid dimension. No problem with me on this. 

>Also, more importantly, if the measurement header has no unit, in the format with unit on the headers, the dimension "Dimensionless" will be automatically selected - even if the column is called fraction. is this OK? Of course, if the user wants to change this to "fraction" it is still possible.

Somehow it feels that this should be part of the column configuration. When I am importing ObsData, error should be Dimensionsless
But importing fraction, well the dim should be fraction.

**Comment by PavelBal** [comment]
If the unit of the measurement (observed data) is empty, then the dimension is "Dimensionless" by default - that is correct.

> But importing fraction, well the dim should be fraction.

I think we do not have a separate "Import fraction" for observed data any more, and by default no unit is always "guessed" as Dimensionless.

**Comment by msevestre** [comment]
We do have for Formulation for example (Table )

**Comment by PavelBal** [comment]
Create issues for V.>10 to handle edge use-cases - "Dimensionless vs. Fraction" etc...
