### ISSUE TITLE
loading of second sheet results in exception

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/OSPSuite.Core#1078]
If the user tries to load more than one sheets of one excel documents, this results in an exception.

**Comment by abdelr** [comment]
Check with @georgeDaskalakis what exactly fails. If I load two sheets one by one or all together from an excel, it seems to import everything just fine.

**Comment by georgeDaskalakis** [comment]
[Book.3.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6646559/Book.3.xlsx)

**Comment by georgeDaskalakis** [comment]
I have uploaded one of the files I have used to reproduce this error.

**Comment by georgeDaskalakis** [comment]
It seems that the error does not have to do with more than one sheets, but with the other sheets not conforming to the format (no headers).Still it has to be handled
