### ISSUE TITLE
LLOQ values from column are not used although configured

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#1090]
PKSim Version from 15.6.2021
Import attached file.
Filter for molecules GLP-1_7...  and Insulin and load and import
For the concentration values is the LLOQ value given in the concentration_LLOQ column:
for first molecule LLOQ = 15 , for the second molecule LLOQ = 100.
But not in the preview nor in the import results in PKSim the LLOQ is used.

I would expect display of LLOQ in the preview both in the table right of Error and in the chart.
[CSV JJ.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6662781/CSV.JJ.xlsx)
![LLOQnotUsed](https://user-images.githubusercontent.com/25579536/122214659-a69cfb00-ceaa-11eb-92c7-7bc9df917eb7.jpg)

**Comment by ju-rgen** [comment]
Well, I have not looked carefully enough, LLOQ/2 values seem to be used.
But it is not visible here nor in the imported data later, that there were used LLOQ/2 values to replace measurement values.
This information should not get lost. 
I would expect display of LLOQ in the preview both in the table right of Error and in the chart.

![grafik](https://user-images.githubusercontent.com/25579536/122401082-90f80600-cf7c-11eb-875b-d18c2a8d5e9a.png)

**Comment by msevestre** [comment]
if the value is set in the DataColumn, an horizontal line should also be visible

**Comment by abdelr** [comment]
I think this is ready for revision. Could you please add feedback if something is missing?

**Comment by ju-rgen** [comment]
Sebastian had mentioned, that LLOQ values given in column can in some cases be different even for the same curve. How does this fit to "horizontal line"?

**Comment by abdelr** [comment]
> Sebastian had mentioned, that LLOQ values given in column can in some cases be different even for the same curve. How does this fit to "horizontal line"?

As far as I remember, we all agreed that a single data set (from a single source) should have the same lloq value. You could have different lloq values on an excel column but they all should be the same for every single data set on your file. Consider the following example:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ABDELR~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ABDELR~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



Time [h] | Concentration | Concentration unit | Concentration LLOQ | Study id
-- | -- | -- | -- | --
1 | 100 | mmol/l | 17 | 1
2 | 15 | mmol/l | 17 | 1
3 | 60 | mmol/l | 17 | 1
4 | 35 | mmol/l | 17 | 1
1 | 7 | mmol/l | 19 | 2
2 | 8 | mmol/l | 19 | 2
3 | 100 | mmol/l | 19 | 2
4 | 120 | mmol/l | 19 | 2



</body>

</html>

Here you have two data sets defined by the "study id" and both have a different value of lloq which is constant for all the data set.

**Comment by ju-rgen** [comment]
I think you are right, that fits to my memories, too.

Nevertheless, Sebastian mentioned this case last week.
I could imagine, that such cases are exceptional.

What happens in such a case, if there are contradicting LLOQ values given?

@Yuri05: will you clarify with Sebastian, if the solution chosen is sufficient.
Probably not my task, so I should stay out.

**Comment by PavelBal** [comment]
> What happens in such a case, if there are contradicting LLOQ values given?

@georgeDaskalakis just a memo, this definitely has to be added to the documentation.

**Comment by georgeDaskalakis** [comment]
In case of multiple LLOQ per dataset:

1)Show warning, but allow import. Ask the user if she wants to continue with import or cancel.
﻿2) Take the highest value (show the applied value in the warning)

**Comment by abdelr** [comment]
> I think you are right, that fits to my memories, too.
> 
> Nevertheless, Sebastian mentioned this case last week.
> I could imagine, that such cases are exceptional.
> 
> What happens in such a case, if there are contradicting LLOQ values given?
> 
> @Yuri05: will you clarify with Sebastian, if the solution chosen is sufficient.
> Probably not my task, so I should stay out.

Hi @ju-rgen, currently if you have different values for LLOQ, the importer will remember the last value provided and will accept the data. We decided today that this is not the perfect way to go so it will be as @georgeDaskalakis described above. So, if there are different values for LLOQ a message will be shown and the user will be prompted if he/she still wants to import the data like this (taking the highest LLOQ value on the data set) or cancel and correct whatever is wrong (maybe a missing "grouping by" or "meta data" to further separate the data) before importing.
