### ISSUE TITLE
Configuration of LLOQ column gets lost sometimes

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#1091]
PKSim Version from 15.6.2021
Add attached file as Observed Data.
[CSV JJ.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6662790/CSV.JJ.xlsx)

Click on "Edit extra fields: Measurement". 
![RemoveLLOQcolumn](https://user-images.githubusercontent.com/25579536/122215403-77d35480-ceab-11eb-85c1-01823c0f68a7.jpg)  
Finish action e.g. by clicking the x

Go to another .e.g. empty "Edit Extra fields".

Return to "Edit extra fields: Measurement"
Now the configuration is in Unit settings and LLOQ different from the intended state.
![returnToLLOQconfig](https://user-images.githubusercontent.com/25579536/122216443-b3bae980-ceac-11eb-9627-4c87f02abb00.jpg)

Also strange effects, when clicking on "Edit Extra fields: Error". ....

**Comment by abdelr** [comment]
@ju-rgen and @Yuri05 please notice that if you click the x button you are cancelling the action so what ever you did will be ignored. If you want to set the changes you have to either click outside the editor or press enter. Could you please try to reproduce following the intended steps and let me know if still some problems arise? Also, if the x button is not completely clear to you maybe we should do something about it but this is the way it works in the rest of PKSim as far as I know.

**Comment by ju-rgen** [comment]
I had at least a similar problem also when clicking outside.
Do the following:
Add attached file as Observed Data.
Then click on "Edit extra fields: Measurement" and switch off the "Import LLOQ from a column".
Then click outside.
Then "Load current sheet"
Then click on "Edit extra fields: Measurement" and switch on the "Import LLOQ from a column" and select concentration_LLOQ as column.
Then click outside.   Now the first value is changed to 7.50
Then click on "Edit extra fields: Measurement", do nothing here.
Then click outside.   Now the first value is changed to 10.92.
Then click on "Edit extra fields: Measurement" and see, that the concentration_LLOQ is not longer selected.

Screenshots:
![grafik](https://user-images.githubusercontent.com/25579536/122400109-b5071780-cf7b-11eb-8c5a-a6ec69007032.png)
![grafik](https://user-images.githubusercontent.com/25579536/122400134-b9cbcb80-cf7b-11eb-8380-8e9c4aab1f12.png)
![grafik](https://user-images.githubusercontent.com/25579536/122400143-bd5f5280-cf7b-11eb-91da-0ce4260bc0d2.png)
![grafik](https://user-images.githubusercontent.com/25579536/122400162-c2240680-cf7b-11eb-9249-c20ff90b66db.png)
![grafik](https://user-images.githubusercontent.com/25579536/122400185-c6e8ba80-cf7b-11eb-9ca2-9c4be79ad7df.png)
![grafik](https://user-images.githubusercontent.com/25579536/122400202-ca7c4180-cf7b-11eb-932f-452a7e2e70a8.png)

**Comment by abdelr** [comment]
Thanks @ju-rgen, I was able to reproduce and will work on fix it now.
