### ISSUE TITLE
OSP 10 beta: Naming of "Load" buttons and and "Confirmation" Tab (Importer-Redesign)

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/OSPSuite.Core#1093]
In the redesigned data importer, it was confusing (not only for me) that it was not possible to reload the sheets, i.e. press again the button “Load current sheet” after adjusting some settings. 
What is actually done after clicking “Load current sheet” is that a preview is generated in the Tab currently called “Confirmation”. 
Since changes are (or should be) directly displayed in this Tab, there is no need to click the button again once the preview has been generated. We suggest thus to rename the buttons now called “Load current sheet” and “Load all sheets” (cf. Figure 1) to “Generate preview based on current sheet” and “Generate preview based on all sheets”, respectively. Accordingly, we suggest to rename the Tab “Confirmation” (cf. Figure 2) to “Import-Preview”.

![Figure1](https://user-images.githubusercontent.com/26439150/122250376-e58e7900-cec9-11eb-953a-35396232105d.PNG)
![Figure2](https://user-images.githubusercontent.com/26439150/122250387-e8896980-cec9-11eb-892c-8266efaaf370.PNG)

**Comment by Christoph27** [comment]
I’m not sure anymore if the renaming described above is really the solution. If you have more than one sheet and loaded all sheets, it seems to be not possible to go back and load only one/the current sheet. You can go back to the Source Tab and delete one sheet, but it is not clear what consequences this has. I still/again think it would be clearer if the user is able to re-load from the sheet after changes and then also be able to correct the selection “from current”/from “all sheets”.
What do you think? @ju-rgen @Yuri05 @sfrechen @AndreDlm

**Comment by abdelr** [comment]
The buttons currently add the current sheet or all the sheets to the selection that will be imported and indeed the confirmation view is a preview of what will be imported. The preview is always up to date to the current settings so changing the mappings or anything else will affect the preview instantly. I would suggest to do three things:
1. Rename "Confirmation" tab to "Import preview".
2. Change "Load current sheet" and "Load all sheets" to "Add current sheet to selection" and "Add all sheets to selection" or something else that makes more sense (and hopefully will not be too long) for the users. I would say the final label could change a bit more if someone else finds a better option.
3. Currently, there is no way to remove a sheet that was previously added and there should be a way to perform this. There could be a third button close to "Load current sheet" that will be also enabled/disabled depending on whether the sheet has been loaded or not and it will remove this sheet from the current selection. The buttons could also be, for a better usage of the space, shown/hidden although this could lead to further confusion if Add/Remove are on the same spot.

**Comment by abdelr** [comment]
After some discussion we decided two accept the first two points. The third point will be slightly modified. There will not be any button to unload from the current selection but if the user closes a sheet from the data preview, this sheet will be unloaded if it was already loaded [(1121).](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1121) Additionally we could have a reset sheets to closed sheets [(1122)](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1122).
