### ISSUE TITLE
OSP10 beta: Order of compartments (Importer-Redesign)

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/OSPSuite.Core#1095]
A very minor thing: In the pull-down menu of the ”Compartments” within the  "Mapping Name" field of the redesigned data import: The order of compartments seems strange to me. First there are the compartments Blood Cells, Interstitial & Intracellular, then there some others and at the end there is Plasma. This order has the consequence that one has to scroll to the compartment which is selected most. I would put Plasma to its peers at the beginning.

**Comment by Yuri05** [comment]
Same for the Organs: Peripheral Venous Blood and Venous Blood should appear on top of the list.
Compare PK-Sim 9:
![grafik](https://user-images.githubusercontent.com/25061876/122349614-b3722b00-cf4c-11eb-8864-52830cd172dc.png)   ![grafik](https://user-images.githubusercontent.com/25061876/122349706-ca188200-cf4c-11eb-9c81-6067b3044b36.png)
