### ISSUE TITLE
Importer: Rename tab "Confirmation"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1105]
![image](https://user-images.githubusercontent.com/25903040/122538100-82662900-d026-11eb-8645-653ac7393391.png)

I would rename the tab "Confirmation" to something like "Import preview".

**Comment by abdelr** [comment]
I will close this issue in favor of [1093](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1093)
