### ISSUE TITLE
Cannot import multiple sheets when the units are different

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1106]
In the attached file, there are two sheets `TestSheet_1` and `Stevens_2012_placebo`. The first sheet has the unit `hours` for the Time-column, the second `minutes`.

Trying to import them both, the following error is shown:
![image](https://user-images.githubusercontent.com/25903040/122539034-72027e00-d027-11eb-877b-ebc17f6668ac.png)

[CompiledDataSet.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6676019/CompiledDataSet.xlsx)

**Comment by abdelr** [comment]
And what do we propose here? In some discussion we agreed that the columns that we use in the configuration should be available in all imported sheets. In this case the column is 'Time [h]' which is indeed not available on the other sheet. We could leave the units out of the name and do some smart parsing with the spaces so 'Time [h]' is also the same as 'Time    [h]' but maybe we need to think this more and include it in the next version?

**Comment by PavelBal** [comment]
The sequence that is used for guessing the unit (i.e., everything in `[]` in the affected columns) should be allowed to be variable.

I think this is crucial because otherwise we cannot import sheets with different units (or even dimensions), which is a basic functionality for me.

**Comment by PavelBal** [comment]
And currently we cannot import the second sheet at all!

**Comment by Yuri05** [comment]
Well, having sheets with different structures (`Time [h]` in sheet1 and `Time [min]`) in sheet 2 is different structure for me) I would NOT expect to be able importing all the sheets in the same import process. Instead, a new import process should be started by user for every sheet then (where the import configuration can be adjusted to this particular sheet).

**Comment by PavelBal** [comment]
Closed in favor of https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1119
