### ISSUE TITLE
Exception in ParameterIdentificationValidator

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#114]
when running a PI with an output without any observed data mapped

https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/212

**Comment by moulirc** [comment]
#msevestre, 

Thanks for your comments and it worked, and was able to generate the graph.
I am trying to establish PBIVIVC for a drug, I am able to generate the convolution process and would like to know how I can generate a full profile? is there a tutorial manual/webinar I can refer to 
I used Saliva to measure the drug levels how can I record (Attached picture) saliva levels under organ tab. 
[Doc1.docx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/1053823/Doc1.docx)

**Comment by msevestre** [comment]
Would you please open a question on the forum? We aim at having only one
topic per issue to avoid any confusion. Thanks
