### ISSUE TITLE
After import: observed data may not be modified anymore (except for the meta data)

### ISSUE THREAD

**Issue by abdelr** [Open-Systems-Pharmacology/OSPSuite.Core#1145]
@Yuri05 commented on [Tue Jun 29 2021](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1820)

It should not be possible to edit observed **data** in PK-Sim (**meta data** can be edited as before)
If data needs to be changed: the new "Update" functionality must be used instead.

![grafik](https://user-images.githubusercontent.com/25061876/123847766-403ac280-d917-11eb-911c-adf141843df2.png)

**Comment by msevestre** [comment]
Please verify and close if needed

**Comment by PavelBal** [comment]
This is not fixed.
