### ISSUE TITLE
Importer: Error when measurement column has missing entries

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1192]
[CompiledDataSet.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6828656/CompiledDataSet.xlsx)

- Load attached file
- Select sheet "MissingTimeEntries"
- Reset mapping based on current sheet
- For measurement, select "Conc[nM]"
- For "Subject Id", select column "Patient Id"
- Import -> Unexpected error

This is due to some entries having no measurement values. Such entries should be ignored and not crash.

**Comment by Yuri05** [comment]
>This is due to some entries having no measurement values.

Seems so. Can be solved now by filtering empty values out:
![grafik](https://user-images.githubusercontent.com/25061876/125928594-b89d9139-f427-439b-a3e9-b6c932df2152.png)
![grafik](https://user-images.githubusercontent.com/25061876/125929142-4f713dc2-98f4-4da6-8754-ccb3d8f620ce.png)

>Such entries should be ignored and not crash.

Depends on the NaN-values setting. But with the default setting "Ignore the row" I would also expect that the rows with NaN-measurement are ignored.
![grafik](https://user-images.githubusercontent.com/25061876/125929380-b2420e4b-ac9d-449a-aa81-98d60de7b9db.png)

And with the setting "Prevent the import" an explicit error message would be better.
![grafik](https://user-images.githubusercontent.com/25061876/125929615-fa7d881e-1baf-40bf-8bb4-27430d523e47.png)

**Comment by georgeDaskalakis** [comment]
The error seems to come when the first (or also all) the values of the measurement for a specific data set are empty.

**Comment by georgeDaskalakis** [comment]
Error is solved through #1199 fix. The problem was not really that there were empty values in measurement, but that all the values were empty, resulting in empty datasets.
