### ISSUE TITLE
Importer Exception handling not working optimally

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/OSPSuite.Core#1240]
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/b204d33c73146fba4d2b1bae9ade3b94ca16d260/src/OSPSuite.Infrastructure.Import/Services/Importer.cs#L77-L86

In the above code snippet the catch is masking any exceptions thrown in the try block with this PossibleUnsupportedSheetFormatException(). This means for example, that already the missing column exception is being correctly identified and thrown (when fe a column set in a configuration is missing from the sheet trying to be loaded with this configuration), the actual exception we get is the PossibleUnsupportedSheetFormatException(). 

We could of course totally remove the try-catch block, but I am a bit afraid this could cause some uncaught exceptions to break the things that were up to now working.

**Comment by Yuri05** [comment]
Something like this?
```
catch (OSPSuiteException)
{
    throw;
}
catch (Exception)
{
  throw new PossibleUnsupportedSheetFormatException(...);
}
```

**Comment by georgeDaskalakis** [comment]
yes, I was also thinking of conditional catch
`catch (Exception e) when (!(e is OSPSuiteException ))`

This solves the issue of masking the exceptions we throw ourselves, but if something really unexpected happens during the this part of the loading process ( mainly includes the identification of the format ), all the user will know is that the file he is using might not be supported. The actual exception will be lost.

**Comment by msevestre** [comment]
In my opinion, catch all exception is suspicious.
What you could do (If you do not want to loose the real exception) is to pass the exception as parameter in your custom exception and extract the message. That way you could show more info to the user
