### ISSUE TITLE
Importer: Wrong values when importing with LLOQ?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1241]
[CompiledDataSet.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6945325/CompiledDataSet.xlsx)

When trying to import the first sheet of the attached file, the second data set contains entries <1 and <0.5 for measurement.

![image](https://user-images.githubusercontent.com/25903040/128506699-e6562cfa-e8df-48c4-a99c-ac39f35fcd3e.png)

In the import preview, the LLOQ-line is correctly set at 1, but the imported values for the entries are 0.5 and 0.25?

![image](https://user-images.githubusercontent.com/25903040/128506793-72f23b2f-02b4-4733-b8b2-cbf9e5105eb9.png)

**Comment by georgeDaskalakis** [comment]
Just to make sure: both values should be 0.5, correct?

**Comment by PavelBal** [comment]
No, the values should be as they are in the source - 1 and 0.5...

Or? @msevestre how did you handle this?

**Comment by msevestre** [comment]
@PavelBal 
There is one value per data repository. So I am not sure how the importer is doing it, but we either have one value or two values depending on the grouping

The value used to be to LLOQ/2 internally I believe. 
The values should also be stored in base unit

**Comment by msevestre** [comment]
Yes. The value in the CELL is going to be set to LLOQ/2
The LLOQ value however is what is right of the < (< 1)

**Comment by PavelBal** [comment]
> The LLOQ value however is what is right of the < (< 1)

Yes, we agreed on that in case there are different LLOQs per data set (which does not make that much sense), the higher value (in this case 1) is used and the user gets a warning message about that (but can import).

> Yes. The value in the CELL is going to be set to LLOQ/2

OK I would not expect that. E.g. for PI we can select "ignore" or "set to LLOQ/2", I would expect that in the data repository the value is as is and is then set to LLOQ/2 in the PI or (wherever it will be used).

I vote for letting the values as is, but if you insist on setting it to LLOQ/2 during import then we should at least add an info message somewhere in the import frame.

**Comment by Yuri05** [comment]
>I vote for letting the values as is, but if you insist on setting it to LLOQ/2 during import then we should at least add an info message somewhere in the import frame.

LLOQ/2

**Comment by PavelBal** [comment]
Both must be LLOQ/2, i.e. in this case both must be 0.5.

**Comment by PavelBal** [comment]
![image](https://user-images.githubusercontent.com/25903040/128673250-5b3f014c-0357-4c7b-a593-362c53396d1c.png)

**Comment by georgeDaskalakis** [comment]
I did not add an info text regarding this issue since it was exactly the same with the old importer. I did though add the description of this behaviour in the documentation.
