### ISSUE TITLE
Importer: Unhandled exception when changing configuration

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1292]
1) Open the usual excel test file
1) "Add current sheet" for the first sheet (TestSheet_1)
1) Go back to "Source"-tab
1) Select the sheet "Stevens_2012_placebo"
1) Reset Mapping based on current sheet ->

![image](https://user-images.githubusercontent.com/25903040/132692481-dd34bb48-2c0b-424c-b679-443fef463e57.png)

**Comment by georgeDaskalakis** [comment]
Updating the packages in MoBi solves this problem (also was not able to reproduce in Core)

**Comment by georgeDaskalakis** [comment]
I researched a bit into this and it actually is a bigger problem:

Whe we have already imported sheets and we change the configuration automatically ( so either **reset configuration based on current sheet** or even **load configuration** ) it is not checked whether the mapped excel columns actually exist in the sheets that have ALREADY been loaded. If they are missing this results in exceptions. 

I have given this some thought and my suggestion (especially taking into account the release) would be simply to deactivate (grey out) those 3 options (load configuration, reset mapping, reset mapping based on current sheet) AFTER the user has loaded some sheets. After that point the changes to the mapping should only be manual.

Alternatively I can write a function to check the compatibility of the format trying to get loaded by one of this actions, and if it is not compatible then simply deny the action with an error message. @msevestre @Yuri05 @PavelBal what do you think?

**Comment by msevestre** [comment]
but should not >Reset Mapping based on current sheet ->

Clear everything and map again?

**Comment by georgeDaskalakis** [comment]
Yes this is also a solution to the issue that I like. 

Currently it only clears the mapping and sets it to the one calculated from the current sheet. If something is already loaded the importer tries to interpret it according to the new mapping - which causes in this case the exception since the column is missing.
