### ISSUE TITLE
Parallelization of PI with "Calculation methods variation"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1301]
I somehow have a feeling that running a PI with "Calculation methods variation" is not properly parallelized.

I have a PI with 17 simulations, so, in theory, up to 17 threads could be run in parallel. I have a 32 core CPU (64 threads). When running this PI with "standard" options, CPU time of the PK-Sim process spikes up to 15% (approx. 10 threads for 100%) with 7.2% between the spikes (also interesting - the time between the spikes, which I think is the simulation time, is greater than the actual simulation time:

![image](https://user-images.githubusercontent.com/25903040/133630348-6e464cab-0b32-408d-a73f-ba5c8d490b35.png)
)

Now if I select "Calculation methods variation" and select 4 methods to test, CPU load for the process never exceeds 7.4% (4 threads + some overhead). If I select only one method for variation, CPU load never exceeds 2% -> the whole PI is running on one core only!

**Comment by msevestre** [comment]
@PavelBal How many cores are recognized when you go to the settings?
![image](https://user-images.githubusercontent.com/1041237/134692569-bfadf84b-01a8-4ae8-be51-a767bce911b8.png)

**Comment by PavelBal** [comment]
63. Without "Calculation methods variation" it seems to parallelize fine. If I select "methods variatioN" and then select only one method, only one core is used.

**Comment by msevestre** [comment]
and if you select multiple methods? What happens?

**Comment by msevestre** [comment]
Any chance you can send me the project so that I can reproduce ?

**Comment by PavelBal** [comment]
> and if you select multiple methods? What happens?

One core per methods, so if I select 5 methods -> 5 cores are used.

**Comment by msevestre** [comment]
Can you check again?
https://ci.appveyor.com/project/open-systems-pharmacology-ci/pk-sim/build/artifacts

version 10.0.243

I think I found the issue with the crash happening sometimes

**Comment by PavelBal** [comment]
Hmm still got the same behavior with 10.0.243

**Comment by msevestre** [comment]
With the same error?

**Comment by PavelBal** [comment]
Yepp
