### ISSUE TITLE
Some issue with logging still

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1307]
@georgeDaskalakis Here is what I did
Get the latest of qualificationRunner and PKSim

Clone repo Efavirenz-Model
https://github.com/Open-Systems-Pharmacology/Efavirenz-Model

In the QualificationRunner folder, start the runner with the following parameters

`QualificationRunner.exe -i "C:\projects\Efavirenz-Model\Evaluation\Input\evaluation_plan.json" -o "C:\tests\10.0\Efavirenz\output1" -f -p "C:\projects\PK-Sim\src\PKSim\bin\Debug\net472" -l "C:\tests\10.0\Efavirenz\log.txt" --norun --logLevel Debug`

Observe that there are many log files everywhere. 

3 for the main log
![image](https://user-images.githubusercontent.com/1041237/134402000-efead2cc-b1a3-4e12-a0ab-f0f82e35323b.png)

And 3 for each instance of PKSIm started (I started two). Can it be that there is something global going on here?
![image](https://user-images.githubusercontent.com/1041237/134402094-c7c25792-e7e2-4dd5-a974-021b7af23462.png)
and

![image](https://user-images.githubusercontent.com/1041237/134402205-9d0d0983-3179-44bc-a586-d2f237d77ec0.png)

**Comment by msevestre** [comment]
also some log look very weird such as 
```
[2021-09-22 14:17:48.874 Efavirenz INFORMATION]  [2021-09-22 14:17:48.504 OSPSuite INFORMATION] Starting validation run... 
 
 [2021-09-22 14:17:48.876 Efavirenz INFORMATION]  [2021-09-22 14:17:48.505 OSPSuite DEBUG] Reading configuration from file 'C:\t
```
It looks that there is a mix of two entries mixed together

**Comment by msevestre** [comment]
might be normal...just weird

**Comment by PavelBal** [comment]
How can we decide whether its a bug or "normal just weird"?

**Comment by msevestre** [comment]
It could be due to the fact that we have now more than one log file. If we can fix this issue, it might solve.tbis one
@georgeDaskalakis seriously considering reverting to  it using serilog and roll out the simple yet pain free implementation we used to have. Thoughts?

**Comment by georgeDaskalakis** [comment]
I personally think we should stick with serilog. It just needs some configuring (and learning of how to do this, which ofcourse is kind of a pain in the beginning).
The issue of multiple logs (log_001, log_002) can be solved by configuring the file as shared. I have already commited a branch concerning this. 
However still in this case we get 3 logs (all named log.txt), one in tests\Efavirenz (the central one) and then two more in "tests\Efavirenz\output1\temp\Efavirenz" and "tests\Efavirenz\output1\temp\Midazolam". The entries of the 2 "secondary" logs are duplicated in the central one, having this format with the timestamp twice in the beginning. I am not quite sure why this is happening....

**Comment by georgeDaskalakis** [comment]
It coud also be a good idea to do a developers doc on this, so we can keep the knowledge gained from configuring serilog.... I could do this, just not sure of the correct location for smthing like this
