### ISSUE TITLE
DataImporter: Units for Molecular weight

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1326]
I think this is an important point - the "Molecular Weight" is obviously treated in base units - though I cannot imagine that any user will ever consider entering the MW values in the excel as kg/µmol!

@msevestre @Yuri05

**Comment by Yuri05** [comment]
You mean the use case when MW is mapped to a data column?

**Comment by PavelBal** [comment]
Yes

**Comment by Yuri05** [comment]
in this case g/mol would be obviously the better choice :)

**Comment by PavelBal** [comment]
Yes. Should we take care of this? I know @msevestre mentioned the code freeze, but I consider it an important feature.

**Comment by msevestre** [comment]
> the "Molecular Weight" is obviously treated in base units

It does not seem that obvious to me. The only unit that make sense is `g/mol` and this is indeed how it should be implemented

How long for this feature? I spent over 2hrs yesterday trying to align all components and DLLs etc... this will have to be done again. So I am ok as long as this can be implemented TODAY. (it should be a matter of minutes but who knows)

**Comment by georgeDaskalakis** [comment]
@msevestre I ll start working on this rightaway, yes should actually not take that long

**Comment by PavelBal** [comment]
>It does not seem that obvious to me. 

By "obviously" I meant the current implementation, which is indeed not obvious to the user :)

**Comment by georgeDaskalakis** [comment]
reopened to push the unit test

**Comment by Yuri05** [comment]
assuming it's fixed. please reopen if not
