### ISSUE TITLE
Color group observed data when drag and dropping folders to charts

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/OSPSuite.Core#1337]
Feature specification:

When adding data sets via drag-and-drop of a folder (or multiple folders), all data sets within one folder can be assigned to a single color. This behavior is optional and can be changed by a setting integrated into the context menu of the “Observed Data” entry of the building blocks explorer. This setting is valid for all subfolders.

![image](https://user-images.githubusercontent.com/37107428/139945893-0b0cbcd8-c95f-470d-a936-43f3c0e7d0d0.png)

Alternatively this feature can be toggled on and off from the User Settings, under “Utilities” -> “Options” -> “General” -> “Colors”:

![image](https://user-images.githubusercontent.com/37107428/139945924-3717af54-a8a4-4190-9ac3-73bf5eecdad9.png)

Also, in case the user selects individual observed data sets instead of folders and drags and drops them on the plot, then each one should be assigned a new color, and they should not be grouped according to the folder they belong to.

**Comment by msevestre** [comment]
@PavelBal Why did you decide to remove the question to the user?

**Comment by PavelBal** [comment]
@msevestre 

I think that 99% of the users will use the "never show this again"-checkbox the first time they see this question. I really do not like the idea of having a dialogue with the sole purpose of announcing a new feature.

We could actually make a small user survey about this. We could even distribute a current version of PK-Sim and ask a couple of users (e.g. from esqlabs, Bayer, or anyone you can think about) if they would use such a dialogue?

**Comment by Yuri05** [comment]
implemented in 11.1
