### ISSUE TITLE
Move SimulationSettings to project as a single default for all simulations

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1354]
Located e.g. under "Utilities -> Options", the pre-defined values will be stored and applied upon simulation creation. They still can be changed in the simulation itself.

**Comment by rwmcintosh** [comment]
Issue moved to [Open-Systems-Pharmacology/MoBi #939](https://github.com/Open-Systems-Pharmacology/MoBi/issues/939) via [**Zenhub**](https://www.zenhub.com/)
