### ISSUE TITLE
Project-wide Chart Settings

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1355]
- Save default per Project (saves into project)
- Save/load to/from templates

**Comment by rwmcintosh** [comment]
Implement along with #1354

**Comment by rwmcintosh** [comment]
@PavelBal is this more than just moving the chart templates along with ```SimulationSettings```

https://github.com/Open-Systems-Pharmacology/MoBi/issues/939
