### ISSUE TITLE
Remove "Simulation Settings"-BB

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1356]
Replace by https://github.com/Open-Systems-Pharmacology/OSMOSES/issues/7 and https://github.com/Open-Systems-Pharmacology/OSMOSES/issues/6.

**Comment by rwmcintosh** [comment]
Replaced by https://github.com/Open-Systems-Pharmacology/OSPSuite-Epics/issues/35

**Comment by msevestre** [comment]
Not planned?

**Comment by rwmcintosh** [comment]
It's the only choice besides 'Fixed' I opened up an epic with the same name to collect individual issues.
