### ISSUE TITLE
Create Icon for Expression Profile Folder

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1366]

**Comment by msevestre** [comment]
@Yuri05 @PavelBal Are we happy with the Expression Icon for Expression Profile? I would say yes? thoughts?

**Comment by Yuri05** [comment]
@msevestre You mean this one? I'm fine with that :)
![grafik](https://user-images.githubusercontent.com/25061876/140303255-06c5f4b6-31f9-4f5b-8724-b120041db0bf.png)
