### ISSUE TITLE
Should be possible to switch ParameterIdentification from Feedback view

### ISSUE THREAD

**Issue by abdelr** [Open-Systems-Pharmacology/OSPSuite.Core#1372]

**Comment by msevestre** [comment]
In fact, we will have multiple feedback view visible (one per PI, created on demand when the user clicks on the feedback button)
CLicking twice for the same view should bring the existing view to the front and not create a new one
The list if currentPIs run should be removed also from the FeedbackPresenter ( I am merging the code now but this is not quite clean yet)

**Comment by abdelr** [comment]
Reopening so we use the active method from ActiveSubjectRetriever instead of listening to events
