### ISSUE TITLE
Color group curves in chart according to their metadata

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/OSPSuite.Core#1378]
In order to further extend the color grouping functionality for the charts, the following new feature is suggested:

A new button will be introduced in the Chart Editor called “Color Group Curves”. 

![image](https://user-images.githubusercontent.com/37107428/141753877-d1ec9ffb-f195-4d21-ae4a-612a681fec9b.png)

Clicking the button opens the following dialog where all the common metadata of the observed data shown in the curve are shown.
 
![image](https://user-images.githubusercontent.com/37107428/141753923-9ba6fe19-a118-4b63-9da0-a0354898da21.png) 

The user can select one or more metadata, according to which the lines will be grouped and given the same color.  Although the colors assigned to the specific lines should be saved, the whole configuration will not be saved, but will only be applied once.

**Comment by Yuri05** [comment]
@georgeDaskalakis https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/pull/1392 says "closes #1378" but the issue is still open. Should it be closed then?

**Comment by georgeDaskalakis** [comment]
@Yuri05 My guess is this happens because I have merged on the feature branch and not on develop. I was also guessing that when the feature branch gets merged into develop, the issues solved there would automatically close. But I was planning on verifying this after the merging of the feature branch, since I am not that sure it will work this way.

**Comment by msevestre** [comment]
Yes this works this way @georgeDaskalakis . All correct here as long as you use the Fixes # keyword ( closes # too)
