### ISSUE TITLE
Import tool does not read UTF-8 encoded files as UTF-8

### ISSUE THREAD

**Issue by AnnikaRPS** [Open-Systems-Pharmacology/OSPSuite.Core#1379]
When importing data from an UTF-8 encoded data file, PK-Sim seems to read the data as another format (probably LATIN-1). This results in problems when the file contains a "µ" symbol, as this is encoded differently in UTF-8 in comparison to LATIN-1. The result looks like this:
![image](https://user-images.githubusercontent.com/63294872/142035483-b821e8fe-ca12-48af-af8c-34ab428a1457.png)

**Comment by georgeDaskalakis** [comment]
Hi @AnnikaRPS ! Could you please provide us with the file so that I can more easily reproduce the error?

**Comment by AnnikaRPS** [comment]
Hi @georgeDaskalakis,
this is the dummy dataset encoded as UTF-8
[DummyDataUTF8.csv](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/7601722/DummyDataUTF8.csv)

**Comment by PavelBal** [comment]
Even excel cannot read this file properly, so I would say - very low prio..

**Comment by Yuri05** [comment]
Let's be better than Excel then :)
