### ISSUE TITLE
Importer: "Molecule" MetaData saved to configuration even when not mapped

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/OSPSuite.Core#1387]
When "Molecule" is not mapped, ColumnName remains null, in order to be able to get edited manually. This mapping is currently save to the configuration:

![image](https://user-images.githubusercontent.com/37107428/143507851-3535f741-a647-493d-b92f-9e1d8925436c.png)

I suggest we remove this. Such an entry to the configuration makes no sense. Still, for reasons of backcompatibility, configuration with null Molecule mappings should be loaded without a problem.

**Comment by PavelBal** [comment]
No opinion on this.

**Comment by georgeDaskalakis** [comment]
After some thought and discussion with @abdelr about this, I believe the possibility of introducing errors by changing this is a far bigger problem than the existence of that line there, especially since it is currently not causing any unwanted behaviour. I will close this error.
