### ISSUE TITLE
Importer: Handling of "invalid" files

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/OSPSuite.Core#1409]
Currently in the importer, if the first sheet of a file is identified as invalid (meaning it does not comply to one of the existing formats), it is not allowed to load the file. This can create a problem in case a user has a file where the first sheet is a description or chart fe. Also we are currently not allowing string values in the numerical columns, meaning we are rejecting files that can in the importer UI actually be configured to be imported.

Concerning this there are 3 suggestion to discuss:
a) allow string values in the numerical column (this actually is certainly a bug, since we are filtering them out later on)
b) allow files that have at least one valid sheet ( not necessarily the first one )
c) should we actually display even the non-valid sheets?

**Comment by PavelBal** [comment]
a) yes, allow mixed types (as you mentioned, we could configure the file the way this column is not used at all)
b) Yes, of course
c) Yes, why not.

**Comment by Yuri05** [comment]
a) yes
b) yes
c) not sure. if we display them, I would at least add a red cross icon to the tab header of invalid sheets.

**Comment by PavelBal** [comment]
I like the proposal with "red cross".

**Comment by abdelr** [comment]
> c) not sure. if we display them, I would at least add a red cross icon to the tab header of invalid sheets.

Because we are treating the data on demand, this is not a straight forward feature. I think we could show an indicator when the sheet is active or loaded but not always since it would mean changing how the importer was designed originally. Also, at some point we decided not to do all calculations on all sheets all the time to save performance.

**Comment by abdelr** [comment]
Then when mappings change or when a user recalculates the format based on a new sheet we set all sheets to hourglass icon (not leaded) except the current one off course.

**Comment by PavelBal** [comment]
For every loaded sheet: show a green checkmark
If the configuration changes and one of the loaded sheets becomes invalid: show an error AND show a red cross for ALL (if no performance issue) or at least for the first invalid sheet.

**Comment by PavelBal** [comment]
Not sure it is that obvious how this is solved now.

- Open the attached file [CompiledDataSet.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/8097853/CompiledDataSet.xlsx)
- The first two sheets are invalid. However, it is not shown that they are invalid (I would expect a red cross), and the configuration is based on the third sheet. Technically this makes sense, but it is not obvious where the configuration comes from.

Possible solutions:
1) Show the first sheet, even if it is invalid, and do not show any configuration. The user would have to select the correct sheet and create a configuration based on that sheet
1) Create configuration based on third sheet, and show red crosses for the first two sheets (so it is clear they are invalid)
1) My favorite: Create configuration based on third sheet, show red crosses for the first two sheets (so it is clear they are invalid), and select the third sheet.

**Comment by PavelBal** [comment]
Decided on: just select the sheet on which the configuration is based on (in this examlple, "TestSheet_1" will be pre-selected), the other sheets are not removed or anything.
