### ISSUE TITLE
Importer crashes with no unit on the error

### ISSUE THREAD

**Issue by abdelr** [Open-Systems-Pharmacology/OSPSuite.Core#1425]
**Steps to reproduce:**
1. Open importer
2. Select file [BookPercent.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/7824394/BookPercent.xlsx)
3. Edit measurement's unit
4. Click "Add All Sheets"
 
**Expected behavior:**
Should not crash

**Comment by PavelBal** [comment]
Strange, I cannot reproduce.
