### ISSUE TITLE
New data import: group data is not used

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/OSPSuite.Core#1432]
Import (in MoBi) from file "Test4.xlsx"

[Test4.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/7829561/Test4.xlsx)

Mapping as shown blow (especially group by -> location):
<img width="244" alt="mapping" src="https://user-images.githubusercontent.com/26439150/148563760-caac2bea-3e5d-4809-a852-66b929890c7b.png">

(Mapping Organ to column "location" gives the same result)

The default naming pattern is kept: {Source}.{Sheet}.{location}

After importing, the location is not used for naming the data sets (naming is e.g. "Test4.Organs._1")
Further, the location is missing at the meta data

<img width="146" alt="locationMissing" src="https://user-images.githubusercontent.com/26439150/148564452-d13b5ec1-7f14-46dd-9f75-75ef0162f385.png">

**Comment by Christoph27** [comment]
similar for file "test_fractions_Tumor.xlsx" when mapping Subject ID to column PatientID
[test_fractions_Tumor.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/7829981/test_fractions_Tumor.xlsx)

**Comment by georgeDaskalakis** [comment]
Cannot reproduce with develop. I think this should have been solved by PR #1384
