### ISSUE TITLE
Maximal number of output points

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1433]
The number of output points (in the OutputSchema) is restricted to 5000. This value is a great limitation when simulating months (or even years). I think this value should be increased (or even exposed as an input parameter).

**Comment by PavelBal** [comment]
`Constants.MIN_NUMBER_OF_POINTS_PER_INTERVAL` should be an input parameter in solver settings. What do you think?

**Comment by msevestre** [comment]
Yep. I like it

**Comment by Yuri05** [comment]
**MAX**_NUMBER_OF_POINTS_PER_INTERVAL :wink: 

The restriction of 5000 points was introduced long time ago - before we had the possibility to restrict the number of stored time courses, before different memory optimizations (e.g. storing constant time courses with just 1 value) and having the total memory limit of 2 GB per application.
Now with all those improvements this limit can be drastically increased.
I would not define max number of points as an additional parameter. Instead I would either
* drop this limitation completely
* or set it as per default to a much higher value. When simulating over 1 year with the standard resolution 4 pts/h you would end up with ca. 35000 points. Thus if we set the limit to 100000 - you could simulate over almost 3 years with the standard resolution. If you need longer simulation time - either you accept lower resolution (is it really required to simulate with 4pts/h over 20 years?) or you could split your simulation time interval into several subintervals (each subinterval up to 3 years).

**Comment by msevestre** [comment]
Fine with me too

**Comment by msevestre** [comment]
Let's just remove it. PR coming
