### ISSUE TITLE
Importing a file: Are you sure you want to cancel

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1460]
Clicking on Import does the following

![image](https://user-images.githubusercontent.com/1041237/151385883-b7f14d15-722d-4ab9-aaed-d77a16f82675.png)

WHAT?

**Comment by msevestre** [comment]
I imported once using the following config
![image](https://user-images.githubusercontent.com/1041237/151386129-b08edfc2-c54c-421b-be99-ee8a06d4dcdc.png)
(forgot to select groupId first and then I did it)

I cannot import it seems (or I do not know how)

**Comment by msevestre** [comment]
[config.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/7951435/config.zip)
[TestData.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/7951436/TestData.xlsx)

Attached testfile and config

**Comment by PavelBal** [comment]
Click "OK", it will import. Its a known bug

**Comment by msevestre** [comment]
Well it's so nasty that it should be reported twice lol

**Comment by msevestre** [comment]
Well there is no PR fixing this currently open and I am using the latest PK-Sim from which I pulled the latest DLL. I am going to try again. just to be sure

**Comment by msevestre** [comment]
Not fixed in latest build of core from 10 min ago(11.0.60)
![image](https://user-images.githubusercontent.com/1041237/151422335-5a2e6a21-df04-4bd2-89d0-666b5e4b7c95.png)
