### ISSUE TITLE
Throw exception when running the same simulation with runSimulations

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1464]
as we are caching with id

**Comment by msevestre** [comment]
@abdelr  @Yuri05 do you concur?

**Comment by msevestre** [comment]
see https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/733

**Comment by abdelr** [comment]
> @abdelr @Yuri05 do you concur?

Sorry, I reply on the original issue. Feel free to move the comment here. But I think we should throw when caching the simulations. As I explained, I see no need for having a copy of the simulation since you could use a simulation batch.

**Comment by msevestre** [comment]
It's not a copy...it's the same instance (e.g same id). Having a copy is not optimal but why not

**Comment by PavelBal** [comment]
I think it does not make sense to run the same simulation (== same ID) multiple times in parallel, so I agree on throwing an error.
