### ISSUE TITLE
Observed data import: Error

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#1482]
Open the CSV file [prefiltered_testcsv.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/8014219/prefiltered_testcsv.zip) and load the configuration [Config01_withFilter.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/8014252/Config01_withFilter.zip)

Confirm the warnng with Yes (s. #1481) and click "Add current sheet". The error below comes:

```
Application:
PK-Sim® 10.0.257

An item with the key 'Dose' has already been added
-----------------------------------------------------
An item with the same key has already been added.

Stack trace:
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
 --- End of inner exception stack trace ---
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   at OSPSuite.Utility.Collections.Cache`2.Add(TValue value)
   at OSPSuite.Infrastructure.Import.Core.Mappers.DataSetToDataRepositoryMapper.ConvertImportDataSet(ImportedDataSet dataSet)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.plotDataSet(Object sender, DataSetSelectedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OSPSuite.Presentation.Presenters.Importer.ImportConfirmationPresenter.DataSetSelected(Int32 index)
   at OSPSuite.UI.Views.Importer.ImportConfirmationView.onDataSetNameSelected(Object sender, EventArgs eventArgs)
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass26_0`1.<OnEvent>b__0()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

The reason is probably that we have a "Dose" column which is not mapped to "Dose" but used as a group by instead and another column mapped to "Dose":
![grafik](https://user-images.githubusercontent.com/25061876/152768158-5ad88663-2e4f-4754-bcef-3cf2bf2a0945.png)

**Comment by georgeDaskalakis** [comment]
Yes that is the reason...."Dose" is added to the extended properties twice.

**Comment by msevestre** [comment]
Do we agree that this is not a good reason and this needs to be fixed?

**Comment by PavelBal** [comment]
> Do we agree that this is not a good reason and this needs to be fixed?

I hope so :D @georgeDaskalakis ?

**Comment by georgeDaskalakis** [comment]
Obviously! I am onto it, was just commenting on what user actions end up creating this.

**Comment by georgeDaskalakis** [comment]
To summarize the current behaviour and problem:

When we assign a column to the "Group By" the column is being also imported as data to the data repository, with MetaDataName = ExcelColumnName. In order to avoid a possible collision with another mapped MetaData with the same name there are 2 possible solutions:

a) ALWAYS add to ALL the MetaData coming from a "GroupBy" a postfix with that string (eg "Dose_GroupBy" in the case of this issue, but also "COLA_GroupBy", "BLA_GroupBy" and so on)

b)  only if there is a collision with an existing mapping, add an index postfix to the grouping_By (in this specific case the Grouping By would be added to the dataRepository as "Dose_1" and "Dose" would also exist)

@msevestre and @Yuri05 what are your thoughts on this?

**Comment by georgeDaskalakis** [comment]
@msevestre @Yuri05 any preferences here? had not seen the issue was open in time to mention in yesterdays meeting.

**Comment by msevestre** [comment]
I am against a) (e.g. always renaming just for an edge case) and I am not sure I like b also because having meta data dose and dose_1 is probably an error anyways.

Should not we throw an error instead?

**Comment by georgeDaskalakis** [comment]
@msevestre Through an error and stop the import? That would mean that @Yuri05 's usecase will not be importable?

**Comment by PavelBal** [comment]
This is a valid use case that should be supported.

**Comment by msevestre** [comment]
I meant warn the user that they should map dose to dose

@PavelBal Why having two metadata named Dose and Dose_1. looks like a valid use case to you?

**Comment by georgeDaskalakis** [comment]
If it is just a warning and we continue with the import in case the user ignores, should we then import with _1?

**Comment by Yuri05** [comment]
I vote for b)

**Comment by msevestre** [comment]
@Yuri05 Can you explain why this use case makes sense? I am just curious.

**Comment by msevestre** [comment]
for me it looks, even based on the file, that this is a  mapping error.

**Comment by Yuri05** [comment]
well, the issue comes from the example in https://github.com/Open-Systems-Pharmacology/MoBi/issues/685#issuecomment-1029993010 and the mapping is exactly as defined there :)

I think it's a pretty rare use case and thus not a high prio for me. But could happen. Especially if the terminology within the observed data uses the same keywords as OSP but with a different meaning.
E.g. if in you data you have a "Tissue" column which needs to be mapped to "Compartment" and a "Compartment" column, which means something completely different as in the OSP but needs to be used as a grouping.

**Comment by msevestre** [comment]
Then you'll end up with two meta data having same name almost and different meanings

Anyway...b it is
