### ISSUE TITLE
initPKSim bug

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite.Core#1493]
When using `initPKSim`

```
initPKSim(pksimFolderPath = "path/to/PK-Sim 10.0.257")
Error in rClr::clrLoadAssembly(pksimR) :   Failure in rclr_ms_call_static_method, but could not retrieve an error message
```

[This ](https://www.open-systems-pharmacology.org/OSPSuite-R/articles/create-individual.html) vignette seems to show the same error message after calling [createIndividualCharacteristics](https://www.open-systems-pharmacology.org/OSPSuite-R/reference/createIndividualCharacteristics.html), which calls `initPKSim` as well.  The same issue was discussed [here](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/393).

**Comment by msevestre** [comment]
I think this is all because those were generated using a wrong version of pksim
And in fact, you are initializing using 10.0 while the version is 11. So the proof is in the pudding?

**Comment by abdullahhamadeh** [comment]
I uninstalled `ospsuite`, then reinstalled v10.0.72.  I referenced a folder containing PK-Sim 10.0.257 in `initPKSim`.  So both v10, no? Got this:

![image](https://user-images.githubusercontent.com/18409098/153923771-e1591e62-10a6-4e18-8460-c5bb0270ce59.png)

**Comment by msevestre** [comment]
also this https://www.open-systems-pharmacology.org/OSPSuite-R/articles/create-individual.html is probably because it was created on a laptop with the wrong version of PK-sim... Let see when we recreate this for the next release
