### ISSUE TITLE
Rename `AllApplicationParametersOrderedByStartTimeFor`

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#1494]
I would rename the function `AllApplicationParametersOrderedByStartTimeFor` to something like `AllOrderedApplicationStartTimes`. 
Because in `AllApplicationParameters `I would expect also all other application parameters like e.g. DrugMass, InfusionTime etc. (I had to look into the implementation of the function to understand what it does)

**Comment by msevestre** [comment]
hum this is not accurate
IT returns a IReadOnlyList of ApplicationParameters

```
 public class ApplicationParameters
   {
      public IParameter StartTime { get; }
      public IParameter InfusionTime { get; }
      public IParameter DrugMass { get; }

      public ApplicationParameters(IParameter startTime)
      {
         StartTime = startTime;
         InfusionTime = startTime.ParentContainer?.Parameter(Constants.Parameters.INFUSION_TIME);
         DrugMass = startTime.ParentContainer?.Parameter(Constants.Parameters.DRUG_MASS);
      }

      public ApplicationParameters(IParameter startTime, IParameter drugMass, IParameter infusionTime)
      {
         StartTime = startTime;
         InfusionTime = infusionTime;
         DrugMass = drugMass;
      }
   }
```

So with StartTime, InfusionTime, DrugMass. I think this is correct as is

**Comment by msevestre** [comment]
Please feedback for what needs to be changed or close if this does not need to be changed

**Comment by Yuri05** [comment]
hmm, ok.
