### ISSUE TITLE
Importer: Cannot select " " as unit for "Fraction"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1500]
- Open the file - Select file [BookPercent.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/7824394/BookPercent.xlsx)
- Measurement dimension is "Fraction", unit is "%"
- Changing unit to " " automatically changes the dimension to "Dimensionless". Having "Dimensionless", it is possible to select "%" as unit, but this automatically changes the dimension to "Fraction".

Expected behavior - once selected manually, the dimension does not change by changing the unit. I believe this is also the reason for https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1499

**Comment by abdelr** [comment]
Closing in favor of #1499
