### ISSUE TITLE
Importer: Arithmetic error unit should follow measurement error.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1501]
### Example:
- Open the file - Select file [BookPercent.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/7824394/BookPercent.xlsx)
- Measurement dimension is "Fraction", unit is "%", Error is set to "Geometric"
- Changing error type to arithmetic requires user action to set the units:

![image](https://user-images.githubusercontent.com/25903040/154674127-325bc6f6-f757-4bda-8f04-43b14f5568bc.png)

### Expected behavior 
- When changing from "Geometric" to "Arithmetic" error type, error unit is automatically set to that of the measurement.

And I would go further:
- changing the dimension of the "Measurement" also changes the unit of the arithmetic error.
- Changing the unit only of measurement does not change the unit of arithmetic error (at this state, they are definitely compatible)
- If measurement unit is from column and a column is selected, changing "Geometric" to "Arithmetic" automatically pre-selects the same column for the units as the one selected for "Measurement" (currently, it must be explicitly set by the user).

**Comment by PavelBal** [comment]
Also in such a case: https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1427

**Comment by PavelBal** [comment]
Ok have to play through all the possible use cases...
@Yuri05 @msevestre @abdelr @georgeDaskalakis Please go through and comment or add use-cases I did not think of. I will then test it though and create issues if something is not working as expected (e.g. unit of Error is not inferred from column).


## 1. Creating configuration for a sheet:
### Measurement unit can be inferred from column header (e.g. "µmol/l")
- Measurement dimension (Concentration (molar)" and unit ("µmol/l") are set from the header
- #### Error unit can be inferred from column header
  - If error unit from header is compatible with measurement dimension -> set error unit from header (e.g. "mmol/l")
  - Otherwise, show an error and user must set the unit (e.g. inferred unit is "mmol")
- #### Error unit is not defined in column header
  - Geometric error
- #### Error unit cannot be inferred from column header (e.g. not supported unit, "lol")
  - Show an error and user must set the unit
### Measurement unit cannot be inferred from column header
- User sets measurement dimension and unit (e.g. "Concentration (molar" and "µmol/l")
  - #### Error unit can be inferred from column header
    - If error unit from header is compatible with measurement dimension -> set error unit from header (e.g. "mmol/l")
    - Otherwise, show an error and user must set the unit (e.g. inferred unit is "mmol")
  - #### Error unit is not defined in column header
    - Geometric error
  - #### Error unit cannot be inferred from column header (e.g. not supported unit, "lol")
    - Show an error and user must set the unit
  - User sets measurement from column
    - The same column is pre-selected for the error unit
    - User can change the column for error unit

## 2. State: Measurement and arithmetic error units are set
- User changes unit of measurement without changing the dimension -> Error unit is not changed
- User changes unit of error -> Nothing else is touched
- User changes error type to geometric
- User changes dimension of measurement
  - Unit of measurement set to default unit of the dimension
  - Unit of error set to default unit of the dimension
- User changes unit of dimension to a column
  - The same column is pre-selected for the error unit
  - User can change the column for error unit
- User selects another column for measurement
  - Unit defined by a column: nothing changes
  - Unit not defined by a column -> Dimension and Units are inferred from column header, see **# 1. Creating configuration for a sheet:** for workflow
- User selects another column for unit
  - Unit defined by a column: nothing changes
  - Unit not defined by a column ->   
    - If error unit from header is compatible with measurement dimension -> set error unit from header (e.g. "mmol/l")
    - Otherwise, show an error and user must set the unit (e.g. inferred unit is "mmol")

## 3. State: Measurement and geometric error units are set
- User changes error type to arithmetic
  - Error unit set to the unit of measurement

**Comment by Yuri05** [comment]
"**1. Creating configuration for a sheet**" - is this the **default** configuration (before user changes the mapping and/or additional fields)? Then the part "_User sets measurement dimension and unit (e.g. "Concentration (molar" and "µmol/l")_" does not belong into this Use Case.

**Comment by PavelBal** [comment]
Yes, Nr.1 is the default configuration. I think this use case does belong here - we start in a non-valid state (Measurement unit cannot be inferred from column header) and the user then sets the dimension and unit for measurement.
