### ISSUE TITLE
Importer: Dimension "Time" missing for Measurement

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1505]
E.g. it is not possible to properly load this file: https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1404

Time should be available for Measurement.

**Comment by PavelBal** [comment]
Ok it is possible to load the file, but still, "Time" should be available.

**Comment by PavelBal** [comment]
@msevestre The dimension `Time` is explicitly removed from the list of allowed dimensions. Is there a reason for this? I definitely have multiple use cases for importing `Time` as measurement dimension, but we don't want to break something.

**Comment by msevestre** [comment]
It made sense at the time since we were only focusing on data measured over time.
I think it's worth removing it ... provided that automatic recognition of unit in [] is working....still a bit of a random behavior
