### ISSUE TITLE
Importer: "Reset mapping based on current sheet" should be a button.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1513]
This feature is so often used that it should be placed more prominent than in the context menu. I think it should be a button (e.g. above the "load/save" buttons).

Especially for users who are not aware of this feature it is very hard to understand how to get a sheet loaded if it is not compatible with the very first sheet.

**Comment by msevestre** [comment]
Agreed!! And a tool tip explaining what it means

**Comment by PavelBal** [comment]
23.03.2022:

- Remove "Reset mapping"
- "Reset mapping based on current sheet" will become a button and named "Reset mapping". Will be placed above the mapping frame
- "Clear mapping" will become a button "Clear all"

No context menu any more.

**Comment by msevestre** [comment]
> I would place the label "Mapping settings" above the Reset/Clear buttons

I agree with @Yuri05 on this

Let's move the button to the right and not to the left. This is how it is in all other instances when we have buttons over a Grid

>plain red "X" icon, but not sure it makes sense right now timewise to the release.

I think we need a new icon for this.  This does not take time at all. Garbage is better than the white cross on red background but it is still not ideal. 

Suggestion: Add a new icon in the ApplicationIcons. 
Call it "RedCross"
Add it at the end of the ApplicationIcons List like so under the OSPSUiteIcon (Line 494)

```
      public static readonly ApplicationIcon RedCross = AddNamedIcon("RedCross", "Delete");
```

This will ensure that we have an icon that you can use, that is using the Delete icon for now. Reference this icon in your code. That way when we have the new icons, we do not need to change anything

**Comment by PavelBal** [comment]
I agree with the proposal.

**Comment by msevestre** [comment]
@georgeDaskalakis I just added a RedICon in my upcoming PR for SVG. It will be available once merged
