### ISSUE TITLE
Data importer: "Group by" / Using naming element from a group does not work

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/OSPSuite.Core#1540]
1. Load data from attached xlsx-file (testData)
2. Map data as in attached screenshot (Time -> Time, Measurement -> area; Error -> StdErr ;  Group by -> Type, Group by -> RRR)
3. Then entries for group {Type} are empty while in group {RRR} there are the entries from group {Type} 

[testData.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/8225303/testData.xlsx)
![Data_Mapping](https://user-images.githubusercontent.com/26439150/157713213-c3138208-e8a3-4127-952f-9b8a209622b7.jpg)

**Comment by PavelBal** [comment]
This is fixed.
