### ISSUE TITLE
Observed data import: Source metadata

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#1559]
At the moment it is possible to manually modify selected data source
![grafik](https://user-images.githubusercontent.com/25061876/159504106-a0d71c5e-c0ea-4a57-bcb6-2c75b2c61a5d.png)

However when importing, the **Source** metadata is set to the original file location, which is usually meaningless
![grafik](https://user-images.githubusercontent.com/25061876/159504464-e9a76eb8-05e1-4d90-a399-89d641fae790.png)

I would suggest to set the **Source** metadata to the value of the **Source** input field. 
This will enable the users to keep only the meaningful part of the file name or change it completely.

Of course it can be done **after the import** by editing the meta data as well, but then you might need to select multiple data sets etc. (and users usually forget to adjust it afterwards @sfrechen @andredlm 😉 )

I would also extend the source input field caption with the hint, that it's recommended to adjust the value to avoid saving local paths in the meta data.

**Comment by PavelBal** [comment]
This is not implemented for Mobi.

**Comment by PavelBal** [comment]
This is done, rigth?

**Comment by Yuri05** [comment]
not done, but obsolete after removing the source from the imported data set.
