### ISSUE TITLE
Chart Editor tab "Curves Color Grouping": check boxes require two clicks

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1585]
The chekboxes get activated only on second click.

**Comment by msevestre** [comment]
@PavelBal @georgeDaskalakis 
I don't quite get the feature
![image](https://user-images.githubusercontent.com/1041237/164294148-279bfc07-8627-412e-ae78-d81a6af858b0.png)

Where is the chosen color coming from? Should't I be able to specify which color to choose?

**Comment by PavelBal** [comment]
@msevestre It groups data sets based on meta data. So the user actually would not know how many colors to specify etc.

**Comment by msevestre** [comment]
@PavelBal I was under the impresssion that it would create the list of possible "groups" and then you could specify the color
e.g. selecting Meta1 and Meta 2 would show all possible combination, assigned default colors that could be set. As it is, I find that something is missing as I have no way to specify the rendering
