### ISSUE TITLE
Iconsistent display in Importer

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1600]
Trying to import file from
https://github.com/Open-Systems-Pharmacology/Forum/discussions/1203

In the Preview I see 3 digits

![image](https://user-images.githubusercontent.com/1041237/164489957-20299363-2fb1-473b-a38f-475a57c1d750.png)

In the Import Preview, I see 2 digits
![image](https://user-images.githubusercontent.com/1041237/164490037-78176958-bf9f-42e5-acce-90904d63fe25.png)

**Comment by msevestre** [comment]
@Yuri05 Thoughts?

**Comment by msevestre** [comment]
@Yuri05 Agreed

@georgeDaskalakis @abdelr Can you fix this. ?

**Comment by georgeDaskalakis** [comment]
@msevestre working on it :)

**Comment by georgeDaskalakis** [comment]
@msevestre @Yuri05 @PavelBal actually while working on fixing this ( for the first Grid, we actually have a DataTable of strings, not double or float, so it is not as straighforward as just setting the decimal accuracy), I would say I disagree that this should be changed.

The first Grid, called Source, shows EXACTLY the contents of the Excel. The second one  ("Import preview") shows the data with the accuracy they will be displayed when imported. If the decimal accuracy is changed in the "Options", the accuracy in the Preview will also be changed. Fe, the same file as above, but with decimal accuracy 6:

![image](https://user-images.githubusercontent.com/37107428/165754533-f1dec06f-b4b8-49fa-8e61-19527e4a0977.png)


A further argument to keep the display the way it currently is, is that the value we are actually importing is the one displayed in the "Source". So if we import with decimal accuracy "2", and open the dataset, we see the following:

![image](https://user-images.githubusercontent.com/37107428/165754992-534f0549-e8cf-49ae-b6f1-fd57ba592763.png)

Now if we change the accuracy to "6", without offcourse reimporting everything, the observed data view changes to this:

![image](https://user-images.githubusercontent.com/37107428/165755286-68d44847-7285-4077-95f9-08e37c1e1b07.png)


I strongly believe that the user should be able to see somewhere the actual value she is importing.

**Comment by msevestre** [comment]
I agree with @georgeDaskalakis 

>Now if we change the accuracy to "6", without offcourse reimporting everything, the observed data view changes to this:

I don't understand why changing accuracy would change with our without reimporting. 
In fact it is NOT accuracy. It is just a display thing. It does not change the underlying value

**Comment by PavelBal** [comment]
I do not see any problem here, for me it behaves as I would expect..

**Comment by msevestre** [comment]
I agree
