### ISSUE TITLE
Importer Layout. There is some empty space to the right of the buttons

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1612]
![image](https://user-images.githubusercontent.com/1041237/164736361-ef108f41-cd19-4535-b5f6-b2348b70e2d8.png)

This needs to be removed

**Comment by msevestre** [comment]
and here too
![image](https://user-images.githubusercontent.com/1041237/164740114-43a6dc94-829c-4b5a-8656-ec3401175336.png)

**Comment by PavelBal** [comment]
Suggestions:

- The "Preview" panel should align with the "source" field, so changing the size of the importer dialogue does not produce empty space.
- "Reset mapping" and "Clear All" buttons should be (much) smaller - maybe only show the icons and explain the function as a tooltip
- Align "Reset mapping" and "Clear All" to the right, at the same height as the "Mapping Settings" label.

**Comment by PavelBal** [comment]
Related to https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1613

**Comment by georgeDaskalakis** [comment]
I would suggest the following changes:

- adding a frame around the column mapping control and the buttons.
- making the buttons thinner (LongButtons)

This results in the following view:

![image](https://user-images.githubusercontent.com/37107428/165645854-691f4137-bc64-4c5e-8d1e-a8b662c3d24e.png)

I will create a PR with this variant.

Another possibility would be to explicitely name the new layout group "Mapping settings". This would result in the following:

![image](https://user-images.githubusercontent.com/37107428/165646098-67d1a134-dd4c-4ce0-bae3-0a645a25cbba.png)


Regarding the empty spaces:

I have deleted the empty space to the right of the buttons, but between "Source" and "Preview" panels there is no empty space. I have tried different anchor settings to solve the empty space appearing when the view gets reseized, but have not succeded in fixing the issue. I will try a bit also tomorrow morning, but I suggest we do not postpone this fix just for the sake of that particular empty space.

**Comment by msevestre** [comment]
Yes you need to use variant two with naming the group. This is what we do every where else
No reason to have a group and a caption underneath

and for the space: I disagree .This needs to be fixed. If you are using a layout control, you can set a max size for the layout item.

**Comment by msevestre** [comment]
for option two, you have to also remove the `columnMappingLayoutControlItem` text

**Comment by msevestre** [comment]
This is better. But it can be improved
![image](https://user-images.githubusercontent.com/1041237/165754043-b15c6bd2-bb66-4095-b9ca-f5b2d2051cc4.png)

Source needs to be the header of the group. It does not make sense to have a floating label within a border 
It is still growing. As I mentioned, you can fix the height of a layout item. Either programmatically or with designer
This is called AdjustControlHeight

```
      /// <summary>
      /// Only sets the control item height. Width will be calculated dynamically
      /// </summary>
      public static void AdjustControlHeight(this LayoutControlItem layoutControlItem, int height)
      {
         //using 0 allows the control witdh to be calculated dynamically
         layoutControlItem.AdjustControlSize(0, height);
      }
```

While the import button has some padding (BTW it is missing an icon, can you also add it)
![image](https://user-images.githubusercontent.com/1041237/165754525-ef314261-4dc4-4e58-976b-e83d059928cd.png)


the other two buttons are claimed to the right, which does not look nice

![image](https://user-images.githubusercontent.com/1041237/165754582-cba40b53-7f1c-4c23-b5f5-85eb13f8bce0.png)

One last iteration hopefully

**Comment by georgeDaskalakis** [comment]
@msevestre everything else in your comment is fixed (at the end removed the frame around "Source", was there as a workaround anyway)

**Comment by msevestre** [comment]
Can you show a screenshot with the frame. I think it looked better

**Comment by georgeDaskalakis** [comment]
you can just look the one a few comments up :)
the thing is, in order to avoid havinf the bold header (like mapping settings), as far as I understand the name "Source" has to be left inside the frame.

**Comment by msevestre** [comment]
No the source was not set in the group and it did look bad I agree.

**Comment by msevestre** [comment]
but I want to see with the name in the group. The fact that is is bold etc, is based on the style. It will look different in the app

This is how it looks in PKSim 
![image](https://user-images.githubusercontent.com/1041237/165778198-50526367-2590-4ab8-9cdf-3db823cfb4a5.png)

**Comment by georgeDaskalakis** [comment]
@msevestre fixed :)

![image](https://user-images.githubusercontent.com/37107428/165825998-6aace2c9-5aed-46c3-8d18-729d6225a4ea.png)

Only thing left is the "Import" button icon, but I am really not sure which icon to use for it...

**Comment by msevestre** [comment]
I am sorry but this is not fixed

![image](https://user-images.githubusercontent.com/1041237/165826362-64fc9e37-fd13-4410-b15b-af3f9e392232.png)

There is a random control name , the groups are not aligned, neither left nor top.
We should not have to do anything for this to work normally...or hardly. You have define somewhere some hard coded values that are preventing the layout control to do its job

**Comment by georgeDaskalakis** [comment]
![image](https://user-images.githubusercontent.com/37107428/165830383-43e16363-e448-4d68-a69c-1fe4466ed5f3.png)

You are right, I have introduce the goupControl, but I had not fixed the spacing as before. It is not hard coded, it is just that the Preview panel and the Source panel are not somehow connected to each other, and I have introduced more space through the spacing properties of the panels. With the introduction of the group Control it got missalligned

**Comment by msevestre** [comment]
ahh. That looks much better
