### ISSUE TITLE
Separating of simulation outputs from observed data in the Chart Editor for specific plots

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/OSPSuite.Core#1632]
As an enhancement of the “Time Profile”, “Predicted vs. Observed”, “Residual vs. Time” plots (individual simulations and parameter identification (PI)) it is proposed to separate the simulation outputs from the observed data. SO instead of the current view where all the curves are listed in just one panel:

![image](https://user-images.githubusercontent.com/37107428/168573605-bc3eab34-26d3-438a-ad74-64fd3baf2153.png)

it is proposed to seperate them like in the following image:

![image](https://user-images.githubusercontent.com/37107428/168573690-29b85483-c1de-4f86-9b89-bdef7d9c4488.png)

**Comment by msevestre** [comment]
There is already a way of doing this out of the box by grouping by a "Category" column

**Comment by msevestre** [comment]
Let's not reinvent the wheel here

**Comment by PavelBal** [comment]
Every user we presented this proposal to was impressed and stongly supported it, so why not?

I also speculate that only minor fraction of the user base actually knows how to show the "Category"-column (and how to group by it). Furthermore, in MoBi the column is just empty:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/25903040/168579990-abadbe15-727c-4b91-8c94-74c089bcfc54.png">

**Comment by msevestre** [comment]
>Every user we presented this proposal to was impressed and stongly supported it, so why not?

I am not saying that this is not good. I am just saying that there is almost no need for code for this. This can be done programmatically so do not make it harder on us by creating multiple views etc.. This is not required

Maybe we will need to add a new column using the column type ( I said category but it might be something else)
This is an example in PKSim on how you can group automatically. 

![image](https://user-images.githubusercontent.com/1041237/168585541-8a8cd384-e25c-47d2-b36c-449362121070.png)

**Comment by msevestre** [comment]
And the column is already there and is called Origin
![image](https://user-images.githubusercontent.com/1041237/168586034-5392f79b-abfa-4a7b-a3a9-5292c45d40b5.png)

**Comment by georgeDaskalakis** [comment]
To my understanding, what supports the creation of two ciews programatically is that we need to have simulation results and observed data always split - not just to have the posibility to group them on demand. 

As a second step to this, there will be given the opprotunity to de/select the observed data belongin to a simulation by simply de/selecting the simulation result on the upper part of the chart editor. I will create the rest of the issues that comprise this bigger feature, maybe as a whole it makes more sense.

**Comment by msevestre** [comment]
>To my understanding, what supports the creation of two ciews programatically is that we need to have simulation results and observed data always split - not just to have the posibility to group them on demand.

Why?

**Comment by msevestre** [comment]
note that the way it is done in PKSim , at the moment, is to group obs data and conc together by repository and then organ
![image](https://user-images.githubusercontent.com/1041237/168595513-c37c36bf-3bb6-4b41-83e1-65404ad82df0.png)

>As a second step to this, there will be given the opprotunity to de/select the observed data belongin to a simulation by simply de/selecting the simulation result on the upper part of the chart editor

This has nothing to do with the way stuff is being grouped in my opinion
