### ISSUE TITLE
Comparison Threshold for Fractions

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#1633]
At the moment we get sometimes very low comparison thresholds for **fractions** from SimModel.
E.g. in some of our Batch Comparison projects we have tolerance 1E-17 for `Fraction absorbed into mucosa segment`.

In principle it should not be the problem. The automatically calculated threshold of the ODE variables are usually OK, and then we calculate the threshold of the `Fraction absorbed ` as `Threshold_of_ODE_variable / Total_Applied_oral_drug_mass`.

However in this particular case applied drug mass **changes during the simulation in case of multiple administrations**.
And then the threshold (calculated using the total drug mass at the end of the simulation) might be too high at the beginning of the simulation.
In order to calculate the threshold properly here, we must either make it time dependent (too complicated) or e.g. use just the **first** applied dose (still too complicated).

Instead, I would suggest the following:
* define new constant (MIN_FRACTION_COMPARISON_THRESHOLD or so) for the lowest value of comparison threshold for all fraction quantities. 
  * I would set it to 1E-4 ➡️ we ignore the differences if both fractions are below 0.01%
* when setting the threshold for a quantity: check if the quantity has dimension "Fraction". 
  * If yes: `set quantity.threshold = Max(calculated threshold; MIN_FRACTION_COMPARISON_THRESHOLD)`

 Either here
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/f741455db467c4449ddb28106adb5c51c4aaf2f7/src/OSPSuite.Core/Batch/Mappers/SimulationResultsToBatchSimulationExportMapper.cs#L56

or here 
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/f741455db467c4449ddb28106adb5c51c4aaf2f7/src/OSPSuite.Core/Domain/DataFactory.cs#L76

**Comment by msevestre** [comment]
>I would set it to 1E-4 ➡️ we ignore the differences if both fractions are below 0.01%

This is not how the threshold works.
It calculates the relative difference. That would mean the relative difference is < 0.0.1%. I think it's still ok
