### ISSUE TITLE
Layout issue PI feedback view

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1634]
![image](https://user-images.githubusercontent.com/25903040/170219196-df2969ec-eb5c-48c7-a209-decc15d3ee49.png)

**Comment by msevestre** [comment]
some 4k issue to check . Might be fixed already

**Comment by rwmcintosh** [comment]
![image](https://user-images.githubusercontent.com/261477/197050713-1e2eae50-1af7-44ab-aab6-73dc28c7eac6.png)

Seems to be fixed.

**Comment by PavelBal** [comment]
MoBi 11.1 Build 61 - problem still there.

**Comment by rwmcintosh** [comment]
4K 200% scale?

**Comment by PavelBal** [comment]
Yes.

**Comment by rwmcintosh** [comment]
@PavelBal When new feedback is refreshed on the screen, does the display correct itself?

**Comment by PavelBal** [comment]
Yepp, works.
