### ISSUE TITLE
"Apply Color Grouping" button layout issue

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1635]
![image](https://user-images.githubusercontent.com/25903040/170223769-b38645b7-8b5b-4380-97df-99682f023861.png)

**Comment by msevestre** [comment]
that should be a very easy fix

**Comment by msevestre** [comment]
(might be fixed already)

**Comment by rwmcintosh** [comment]
![image](https://user-images.githubusercontent.com/261477/196708377-a63b9918-56dd-49c0-a4a1-f6d3a488492c.png)

FYI - this is at 200% scaling. At 100% it's fine.
