### ISSUE TITLE
Show a warning message when number of output points is high

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1636]
As we have removed the limit points in the output interval, the software can sometimes fail to plot the specified number of points (or the calculation time explodes). Sometimes this happens when the user accidentially selects wrong unit for the resolution. I propose to show a warning before starting the simultation when the number of points exceeds a certain threshold.

Warning: "The selected output resolution will generate xxx points and may severy impact the software performance. Are you sure you want to run with these setting? If not, consider changing output resolution in simulations settings".

29 days, two output curves:

- 4 pts/h - ok
- 20 pts/h - ok 
- 60 pts/h - ok
- 120 pts/h - already slow

So I would propose to show a warning when the number of output points exceeds `2*29*24*60*100` = 8352000 points (8300000).

**Comment by msevestre** [comment]
The warning will be shown all the time that one simulates. Too much work to save this at the simulation level

**Comment by PavelBal** [comment]
But only if the selected output resolution is "too hight", right? In that case - agree.

**Comment by msevestre** [comment]
I don't know where this number is coming from again. I know you told me lol
Should we say anything above 100000 pts deserved a warning?

**Comment by PavelBal** [comment]
> I don't know where this number is coming from again.

I just performed a couple of runs with different resolutions and calculated the number of points when it became a problem. Based on my experience, I would suggest 5,000,000 as a threshold.
