### ISSUE TITLE
"Apply color grouping" button too small

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1653]
![image](https://user-images.githubusercontent.com/25903040/176473757-204bad1d-28d8-4a0f-b89a-36931f45b4f4.png)

**Comment by msevestre** [comment]
@PavelBal I cannot reproduce, even with a font at 225%. I am wondering if you see the same behavior in PKSim
I have added a property. Can you try in MoBi on Monday let me know?
