### ISSUE TITLE
Calculate AUC_tEnd for multiple administration simulations

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#1693]
Don't see any reason why not to calculate it.
For AUC_norm/AUC_inf, I would understand why this might be problematic, but not for the simple AUC.

And now if we e.g. would like to add user defined PK-Parameter like AUC between 3th and 4th application - it is not possible.

**Comment by msevestre** [comment]
I am fine with this. The changes are pretty straightforward. Could probably be implemented for v11.1

**Comment by Yuri05** [comment]
@twendl FYI
