### ISSUE TITLE
SimulationOutputMappingPresenter: Does too much and breaks presentation logic

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1695]
this code
```
 {
         if (!_simulation.OutputMappings.OutputMappingsUsingDataRepository(simulationOutputMappingDTO.ObservedData).Any())
            _simulation.OutputMappings.Add(simulationOutputMappingDTO.Mapping);
      }
```

does not belong in the presenter as discussed . (at least I think so, please explain if this is required)

Suggestion:
When an observed data is ADDED to a simulation, directly add to the output mapping
Similarily, when an observed data is REMOVED from a simulation remove from output mapping,. The presenter should not modify the simulation by reacting to those events.

FYI: @georgeDaskalakis @rwmcintosh

**Comment by georgeDaskalakis** [comment]
functionality is implemented in PK-Sim (and MoBi then in the future)

**Comment by PavelBal** [comment]
@georgeDaskalakis 

> functionality is implemented in PK-Sim (and MoBi then in the future)

Please create an issue in MoBi.
