### ISSUE TITLE
Simulation OutputMappings cannot get deserialized

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/OSPSuite.Core#1697]
Since the OutputMappings member 
`SimulationQuantitySelection OutputSelection`
has a dependency on the simulation itself (that has ofcourse not yet being deserialized) it is not possible to load the OutputMappings that we have saved.

We have to think a bit about finding a workaround to avoid having to write a whole new OutputMapping object.

**Comment by Yuri05** [comment]
@georgeDaskalakis I assume this is fixed in the meanwhile?
