### ISSUE TITLE
Automatically re-run when batch does not return a result

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/OSPSuite.Core#1713]
Based on this issue in SimModel - https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/issues/151-
it might be helpful to automatically re-run batch runs that fail to return a result.

Depends on what a fix timeline will be like. 

@Yuri05 @msevestre @PavelBal

**Comment by Yuri05** [comment]
After clarification and fix of the underlying issue: no need for this anymore
