### ISSUE TITLE
Pixels and scaling - button sizing is not working as expected

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/OSPSuite.Core#1724]
See #1635

The button was being sized according to pixels. That makes all the button sizes consistent. For this button, when scaled to 200% the text no longer fit inside the button. Obviously, scaling the fonts and the pixel sizing has to be reconciled.

This is just one button of many possible areas where this problem will arise.

**Comment by msevestre** [comment]
Probably we should allo buttons to resize to tje content being shown
That way, we'll let the button grow or shrink. They will have different sizes but this requirement of all buttons look the same is probably not a good expectation to have

Thoughts?

**Comment by rwmcintosh** [comment]
> Probably we should allo buttons to resize to tje content being shown That way, we'll let the button grow or shrink. They will have different sizes but this requirement of all buttons look the same is probably not a good expectation to have
> 
> Thoughts?

Sounds good to me

**Comment by Yuri05** [comment]
assume this is fixed. closing. please reopen if it's not the case
