### ISSUE TITLE
11.1 Observed data mapped in a simulation must be mapped again in a PI

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#1743]
In the simulation:
![grafik](https://user-images.githubusercontent.com/25061876/199952345-a87018c6-5cf1-4d22-9513-9dcc07b3802f.png)

Selecting "Start Parameter Identification..." from the simulation kontext menu:
![grafik](https://user-images.githubusercontent.com/25061876/199952634-1abd18b4-8aaf-4225-9922-7b1e0f87de54.png)

Click on "Add Output":
![grafik](https://user-images.githubusercontent.com/25061876/199952737-fc806b50-eb26-43ce-b144-910c1de82af6.png)

**Comment by msevestre** [comment]
That I don't understand. This was the whole goal of the implementation no?
