### ISSUE TITLE
11.1: Observed data mapping / Delete Entry

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/OSPSuite.Core#1763]
@Yuri05 commented on [Wed Nov 02 2022](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2380)

The tooltip for **X** says "Delete entry", but it just clears the mapping to the simulation output.
Under "Delete Entry" I would usually understand that the entry is completely removed from the table (meaning the observed data set is removed from the simulation).
So we should either change the tooltip to something like "Clear mapped simulation output" or the click on **X** should trigger "Remove observed data set from the simulation" use case.
I would vote for the latter ("Remove obs data set")
![grafik](https://user-images.githubusercontent.com/25061876/199517476-2ab69051-d1b2-4204-9c33-46c69ebfe3d2.png)

---

@Yuri05 commented on [Wed Nov 02 2022](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2380#issuecomment-1300559201)

@msevestre @PavelBal @rwmcintosh FYI

---

@PavelBal commented on [Wed Nov 02 2022](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2380#issuecomment-1300654334)

- Delete entry
- "Unmapping" should be done via selecting "<None>" from the "Simulation Ouputs"-drop-down
- ONLY implement if max. 1 days

---

@georgeDaskalakis commented on [Thu Nov 03 2022](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2380#issuecomment-1301799788)

The existing way of removing observed data from the simulation (right click on the list and remove), should still be available, right?
 

---

@PavelBal commented on [Thu Nov 03 2022](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2380#issuecomment-1301852599)

> The existing way of removing observed data from the simulation (right click on the list and remove), should still be available, right?

Yes

**Comment by msevestre** [comment]
Interesting behavior. I just understood what was implemented looking at the code. 
I WOULD NOT HAVE EXPECTED THIS BEHAVIOR but that's fine with me

**Comment by PavelBal** [comment]
> I WOULD NOT HAVE EXPECTED THIS BEHAVIOR but that's fine with me

Obviously, it depends on the user, because Yuri expected exactly this :D

**Comment by msevestre** [comment]
this is why I said fine with me
