### ISSUE TITLE
OutputMapping should be exported to MoBi?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1772]
@msevestre commented on [Fri Nov 11 2022](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2424)

I think this belongs to the simulation transfer between PKSim and MoBi 
@rwmcintosh @PavelBal @Yuri05 @georgeDaskalakis 

or is there a reason why this was not done?

**Comment by PavelBal** [comment]
Just didn't think about it.

**Comment by msevestre** [comment]
ok this is I believe implemented. in my last PR
