### ISSUE TITLE
Charts: provide more symbol styles?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#1789]
DevExpress currently provides the following markers (symbol styles) for charts:
![grafik](https://user-images.githubusercontent.com/25061876/201880780-4ccee572-4f48-4d6f-a248-7bc755219d95.png)

However only few of then are supported in PK-Sim/MoBi:

![grafik](https://user-images.githubusercontent.com/25061876/201881039-3d6af8e8-1836-446c-9ef0-5bbb84f03497.png)

Any reason why we should not provide ALL available symbol styles?

**Comment by Yuri05** [comment]
P.S. How it looks like: https://docs.devexpress.com/CoreLibraries/DevExpress.XtraCharts.MarkerKind

**Comment by msevestre** [comment]
I don't see any.. either arbitrary decision years ago or those were added after the fact
It needs to be synchronized with the reporting engine probably so that plots are drawn with the right symbols too

**Comment by Yuri05** [comment]
>It needs to be synchronized with the reporting engine probably so that plots are drawn with the right symbols too

Yes. tlf already supports a lot of symbols and can be extended with the missing ones (which are "pentagon", "hexagon" and "thin cross" - all others are already in the list) (correct, @pchelle ?)
https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/07776aa28f45c662cf77ba7713a1c85cf8c1b3b0/R/utilities-enums.R#L290-L337

**Comment by PavelBal** [comment]
I am for providing all symbol types... Don't see a reason to artificially limit this.

**Comment by msevestre** [comment]
doing it now

**Comment by pchelle** [comment]
> > It needs to be synchronized with the reporting engine probably so that plots are drawn with the right symbols too
> 
> Yes. tlf already supports a lot of symbols and can be extended with the missing ones (which are "pentagon", "hexagon" and "thin cross" - all others are already in the list) (correct, @pchelle ?) https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/07776aa28f45c662cf77ba7713a1c85cf8c1b3b0/R/utilities-enums.R#L290-L337

Yes, reporting engine has an internal dictionary translating input symbol names into tlf symbol names that will need synchronization
