### ISSUE TITLE
Eception when new empty Output mapped in PI

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/OSPSuite.Core#1806]
In Parameter Identification, if the user clicks the "Add Output" button, the result is the following empty OutputMpaping:

![image](https://user-images.githubusercontent.com/37107428/202928321-b7329242-4468-4e79-a8ef-55616c118672.png)

If the user (accidentally fe) closes the PI in this state, then it is not anymore possible to open this Parameter Identification, since when trying to open, the user will always get the following exception:

![image](https://user-images.githubusercontent.com/37107428/202928386-5a2040c1-a935-4f0e-ba88-48f33f35915f.png)

**Comment by Yuri05** [comment]
seems to be fixed. Closing
