### ISSUE TITLE
11.1 Deviation lines disappear after run simulation and cannot be added anymore

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#1812]
If I add a deviation lines to PredictedVsObserved plot and run simulation after that: all deviation lines disappear in the plot.
They are also not shown in the chart editor anymore, so I cannot select/deselect them.

However: if I try to add a fold range which was added **before** run simulation: nothing happens (meaning that the deviation lines are still saved internally). Adding a fold range which was NOT added before works (and disappears again after the next run sim).

**Comment by Yuri05** [comment]
happens both in PK-Sim and MoBi.
@rwmcintosh @georgeDaskalakis @msevestre

**Comment by georgeDaskalakis** [comment]
@Yuri05 on it
