### ISSUE TITLE
Cannot import valid CSV file

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#1821]
[test1.csv](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/10188458/test1.csv)
In the csv file attached, column separator is the **blank**, and decimal separator is **comma**.

when importing, I set the separator to blank:
![grafik](https://user-images.githubusercontent.com/25061876/206537300-c982b9d4-fcbf-42ca-8420-a2ca2ebb0da3.png)

The import window opens and shows all the column mappings as expected and the data is correctly shown in the preview window (so comma was correctly recognized as decimal separator):

![grafik](https://user-images.githubusercontent.com/25061876/206537599-ca0bd242-635c-4b6c-8dde-7d56a866e233.png)

However, when I click on "Import current sheet" after that: I don't get any graph of the data set which could be imported and the import button is disabled:
![grafik](https://user-images.githubusercontent.com/25061876/206537872-8d9727c5-dc9e-4571-882b-b8c25e1c90af.png)

This happens both in PK-Sim and MoBi

**Comment by rwmcintosh** [comment]
> The import window opens and shows all the column mappings as expected and the data is correctly shown in the preview window (so comma was correctly recognized as decimal separator):

Not necessarily true because the cells can be showing the separated text, not as a number.

My debugging so far shows me that the problem is related to the comma. Even if it's shown correctly in the preview somehow, when converted the ',' are being interpreted as thousands separator.

We probably should prompt for 'Decimal separator' the way we do for column separator, because even if you have your PC's culture set up people may often import data with the wrong (for them) separator.

**Comment by rwmcintosh** [comment]
Could you do this in a PowerShell @Yuri05 

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\mcint> Get-Culture

LCID             Name             DisplayName
----             ----             -----------
4105             en-CA            English (Canada)


PS C:\Users\mcint>
```

**Comment by Yuri05** [comment]
>We probably should prompt for 'Decimal separator' the way we do for column separator, because even if you have your PC's culture set up people may often import data with the wrong (for them) separator.

Agree, we should extend the CSV import settings with the decimal separators ("." or ",").

**Comment by Yuri05** [comment]
```
Get-Culture

LCID             Name             DisplayName
----             ----             -----------
1031             de-DE            Deutsch (Deutschland)
```
