### ISSUE TITLE
Importer: Meta data messed up

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1872]
[pksim-metadata-messed-up.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/10465846/pksim-metadata-messed-up.zip)

Import the file with the configuraiton.

Metadata is wrong - study id is mapped to group id, subject id to study id, group id to subject id.

![image](https://user-images.githubusercontent.com/25903040/213686903-02622697-0f7f-40c8-a7ce-6a86b4375a5f.png)

**Comment by georgeDaskalakis** [comment]
@PavelBal FYI this error comes when the "group by" is mapped before some other mapping parameters. I will have a fix shortly, but till then to bypass this issue, you can simply delete the "group by" mapping and add it in the end.
