### ISSUE TITLE
Data importer - performance issues

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1881]
I have a file with >3k data sets. Loading the file and "Add current sheets" is ok, but then clicking on "Import" takes ages (actually I do not know wheter it will ever finish because it did not after half an hour).

**Comment by Yuri05** [comment]
@PavelBal Is this still the case?

**Comment by PavelBal** [comment]
Yes

**Comment by PavelBal** [comment]
Have no example to reproduce.
