### ISSUE TITLE
Extend Path concept with more keywords?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1882]
As we are adding some new logic here, can we think of some new keywords that would be helpful to navigate the tree structure?

/cc @Yuri05 @PavelBal @georgeDaskalakis @StephanSchaller @abdullahhamadeh @rwmcintosh

**Comment by msevestre** [comment]
An example would be to add the `PARENT_ORGAN` keyword that would navigate directly to the top most container with the type "ORGAN"

so `PARENT_ORGAN|V` would always be the volume of the parent organ, independently from where the owner of the formula is located

**Comment by PavelBal** [comment]
https://github.com/Open-Systems-Pharmacology/MoBi/issues/310

**Comment by Yuri05** [comment]
Related issues:
https://github.com/Open-Systems-Pharmacology/MoBi/issues/837
https://github.com/Open-Systems-Pharmacology/MoBi/issues/310 (@PavelBal 😉 )
https://github.com/Open-Systems-Pharmacology/MoBi/issues/196

**Comment by PavelBal** [comment]
@VanessaBa FYI
