### ISSUE TITLE
Icons that need implementations

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/OSPSuite.Core#1888]
**Edit this comment to add icons as we go**

- PKSim modules
- Extension modules
- PKSim modules folder
- Extension modules folder
- Neighborhood

**Comment by rwmcintosh** [comment]
Another placeholder icon #1890

**Comment by msevestre** [comment]
@rwmcintosh Do we have a list of all the icons we need? I need to add to that list neighborhood

**Comment by rwmcintosh** [comment]
We are removing 'Extension Modules' from the UI. 

https://github.com/Open-Systems-Pharmacology/MoBi/issues/981

We will need a distinct icon for modules that come from PK-Sim so they can be differentiated in another way in the UI

**Comment by msevestre** [comment]
I think the same icon, just different colors would be enough?

**Comment by msevestre** [comment]
Hovering over would show all the meta info (PKSimVersion, read-only etc..)

**Comment by rwmcintosh** [comment]
We'll need to revise the MSV and PSV building block icons to use different initials now.

**Comment by Yuri05** [comment]
Maybe something like this (modified in the way that the brick on top comes down with an arrow, similar to your first image)?
![Unbenannt-1](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/25061876/cdce00b8-e5c8-4afc-85dd-67516e665c43)

**Comment by rwmcintosh** [comment]
> Maybe something like this (modified in the way that the brick on top comes down with an arrow, similar to your first image)? ![Unbenannt-1](https://private-user-images.githubusercontent.com/25061876/332768861-cdce00b8-e5c8-4afc-85dd-67516e665c43.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTc4NzQsIm5iZiI6MTcxODE5NzU3NCwicGF0aCI6Ii8yNTA2MTg3Ni8zMzI3Njg4NjEtY2RjZTAwYjgtZTVjOC00YWZjLTg1ZGQtNjc1MTZlNjY1YzQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEzMDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZWU3MmIyOTdmZGMxM2Y0ZWEzZTE4MTdhNWYxMzcyMmM0OGYxYjMxMDM1MTYwNWU0MmM4YmExYzU4ZWU0NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iaS3ZAwTgN8f846-f58hX4N66mG2IZZ8LdWcp0EehSA)

I think this is too much detail for a 16x16 px image
