### ISSUE TITLE
What should happen when removing a container linked to neighborhoods

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1921]
@PavelBal @Yuri05 
At the moment, the neighborhood is deleted as well. But now that the neighborhood in the spatial structure is loosely coupled by path and not by reference, do we expect the first/second neighbors to be set to null for instance? or to delete the neighborhood completely

Also, when renaming a container, we will have to rename all neighborhoods path as well... The feature that keeps on giving :)

**Comment by msevestre** [comment]
For now I am going to keep the same behavior and delete the neighborhood

**Comment by Yuri05** [comment]
I can think about some edge cases where setting the path to empty would be more usefull, but in the most cases deleting the neighborhood should be ok.

**Comment by PavelBal** [comment]
Best solution would be - show a dialogue with the list of associated neighborhoods and let the user select which to delete.

**Comment by msevestre** [comment]
Not in the card for this release

**Comment by Yuri05** [comment]
nothing happens now (which is OK), but simulation is then created without error or warning.
Expected: Error during simulation creation

**Comment by PavelBal** [comment]
I am still not sure about 

> Expected: Error during simulation creation

I propose to close this issue and create a new one for "Should an error be thrown when a simulation is being created and a neighbor of of an neighborhood is not found?".

**Comment by Yuri05** [comment]
> > Expected: Error during simulation creation
> 
> I propose to close this issue and create a new one for "Should an error be thrown when a simulation is being created and a neighbor of of an neighborhood is not found?".

ok for me

**Comment by PavelBal** [comment]
Close in favor of https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2289
