### ISSUE TITLE
Unit tests not running on latest Visual studio (2023 17.5.2)

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/OSPSuite.Core#1930]
Creating this issue since I struggled a bit with this:

After updating to the latest VS (17.5.2, although I think this was not working also a few versions before), the unit tests do not run. This seems to be a known issue  ( [](https://github.com/nunit/nunit3-vs-adapter/issues/987) )  and I got it solved by updating the NUnit3TestAdapter nuget package to 4.4.2

I would suggest pushing this change, if nobody is against it. I don't think that would cause any compatibility issues for anyone.

**Comment by msevestre** [comment]
No problem. Tests are running with me but we should upgrade our components anywa.s Can you create a PR?
