### ISSUE TITLE
PROPOSAL for Parameters in Individual

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1945]
This is a follow-up of the discussion in https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1939, specifically https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1939#issuecomment-1479389184 by @Yuri05 

Here is a suggestion that I would like to get feedback on by tomorrow for our meeting

## Spatial Structure

* We only define parameters that are common for all species (based on our current knowledge). All formulas defined in those parameters are common for all species (by default but can be overwritten in the individual for specifc use cases)
* The only constant values are the ones that are species-independent (Avogadro Number etc)

## Individual

* Defines a list of ParameterPath, Value And/Or Formula, Dimension
* Only individual-specific parameters are defined here
* Supporting parameters that are species-specific (Age, height etc.) are also defined only in the individual

## Model

When the model is created, we do something more advanced with the Individual parameter. Instead of JUST updating parameters that exist in the Spatial structure, we also ADD parameters that are not defined (assuming the container structure is defined otherwise, we do not do anything, probably an error)

Example: 
Assuming we have a human-specific formula for a parameter
Something like 
P = r1 + r2 + r3 

where P is a parameter that is defined in the spatial structure, available for all species, and r1 r2 and r3 are supporting parameters that only make sense for human
The Individual Human would look like this
| Parameter | Formula | Value | Dimension | 
| - | - | - | - |
| P| r1 + r2 + r3 | null | Dim
| r1| null | 1 | Dim1
| r2| null | 2 | Dim2
| r3| null | 3 | Dim3

The Individual Dog for instance would look like this
| Parameter | Formula | Value | Dimension | 
| - | - | - | - |
| P| null | 20 | Dim

In the simulation, we would have a different set of parameters based on the used species

## When using from R

One would only get the values for P from the Individual code. This would ensure that one could set a whole individual completely, independently from the species. 

## DB Changes
We would need to add a new flag at the parameter level (or maybe parameter container level) to specify of this individual parameter is "global" (e.g. to be added in the spatial structure) or local (to be added in the Individual). This flag would only affect the creation of the PKML structure

Please feedback @Yuri05 @PavelBal @rwmcintosh @StephanSchaller

**Comment by rwmcintosh** [comment]
👍 I think it's the easiest to understand this way.

**Comment by Yuri05** [comment]
Very nice!
Some remarks:
1. Individual parameters table should contain the full path, not only parameter name, correct?

| Parameter | Formula | Value | Dimension | 
| - | - | - | - |
| Organism/Liver/P| r1 + r2 + r3 | null | Dim
| Organism/Liver/r1| null | 1 | Dim1
| Organism/Liver/r2| null | 2 | Dim2
| Organism/Liver/r3| null | 3 | Dim3

2. I think we do not need an additional flag in the DB. With 2 additional views it is possible to check which parameters are not available in ALL species (maybe even possible with just 1 view, but I did not manage to do it so far)

With this I get (we have currently 10 species):

<details><summary><b>Container parameters defined not for all species</b></summary>

container_id | container_type | container_name | parameter_name | species_count
-- | -- | -- | -- | --
146 | ORGANISM | Organism | Age | 1
146 | ORGANISM | Organism | BMI | 1
146 | ORGANISM | Organism | BSA | 1
146 | ORGANISM | Organism | Estimated gestational age | 1
146 | ORGANISM | Organism | Gestational age | 1
146 | ORGANISM | Organism | Height | 1
146 | ORGANISM | Organism | MeanHeight | 1
152 | ORGAN | Fat | Volume fraction lipids scale factor | 1
152 | ORGAN | Fat | Volume fraction water scale factor | 1
157 | ORGAN | Kidney | Age of aging onset | 1
157 | ORGAN | Kidney | Aging half-time | 1
157 | ORGAN | Kidney | GFR | 1
157 | ORGAN | Kidney | GFRmat | 1
157 | ORGAN | Kidney | Hill coefficient for GFR | 1
157 | ORGAN | Kidney | Hill coefficient for aging GFR | 1
157 | ORGAN | Kidney | Maximal decreasing rate factor | 1
157 | ORGAN | Kidney | TM50 for GFR | 1
157 | ORGAN | Kidney | Volume (standard kidney) | 1
157 | ORGAN | Kidney | eGFR | 1
158 | ORGAN | LargeIntestine | Volume (default) | 9
161 | ORGAN | Muscle | Volume fraction lipids scale factor | 1
161 | ORGAN | Muscle | Volume fraction proteins scale factor | 1
161 | ORGAN | Muscle | Volume fraction water scale factor | 1
166 | ORGAN | Saliva | Saliva flow rate | 1
168 | ORGAN | SmallIntestine | Volume (default) | 9
261 | COMPARTMENT | Saliva | pH (saliva) | 1
4482 | COMPARTMENT | Stomach | Default thickness of gut wall | 9
4483 | COMPARTMENT | Duodenum | Default thickness of gut wall | 9
4483 | COMPARTMENT | Duodenum | L_p0 | 1
4483 | COMPARTMENT | Duodenum | L_p1 | 1
4483 | COMPARTMENT | Duodenum | Thickness_p1 | 1
4483 | COMPARTMENT | Duodenum | Thickness_p2 | 1
4483 | COMPARTMENT | Duodenum | Thickness_p3 | 1
4483 | COMPARTMENT | Duodenum | r1_p0 | 1
4483 | COMPARTMENT | Duodenum | r1_p1 | 1
4483 | COMPARTMENT | Duodenum | r2_p0 | 1
4483 | COMPARTMENT | Duodenum | r2_p1 | 1
4484 | COMPARTMENT | UpperJejunum | Default thickness of gut wall | 9
4484 | COMPARTMENT | UpperJejunum | L_p0 | 1
4484 | COMPARTMENT | UpperJejunum | L_p1 | 1
4484 | COMPARTMENT | UpperJejunum | Thickness_p1 | 1
4484 | COMPARTMENT | UpperJejunum | Thickness_p2 | 1
4484 | COMPARTMENT | UpperJejunum | Thickness_p3 | 1
4484 | COMPARTMENT | UpperJejunum | r1_p0 | 1
4484 | COMPARTMENT | UpperJejunum | r1_p1 | 1
4484 | COMPARTMENT | UpperJejunum | r2_p0 | 1
4484 | COMPARTMENT | UpperJejunum | r2_p1 | 1
4485 | COMPARTMENT | LowerJejunum | Default thickness of gut wall | 9
4485 | COMPARTMENT | LowerJejunum | L_p0 | 1
4485 | COMPARTMENT | LowerJejunum | L_p1 | 1
4485 | COMPARTMENT | LowerJejunum | Thickness_p1 | 1
4485 | COMPARTMENT | LowerJejunum | Thickness_p2 | 1
4485 | COMPARTMENT | LowerJejunum | Thickness_p3 | 1
4485 | COMPARTMENT | LowerJejunum | r1_p0 | 1
4485 | COMPARTMENT | LowerJejunum | r1_p1 | 1
4485 | COMPARTMENT | LowerJejunum | r2_p0 | 1
4485 | COMPARTMENT | LowerJejunum | r2_p1 | 1
4486 | COMPARTMENT | UpperIleum | Default thickness of gut wall | 9
4486 | COMPARTMENT | UpperIleum | L_p0 | 1
4486 | COMPARTMENT | UpperIleum | L_p1 | 1
4486 | COMPARTMENT | UpperIleum | Thickness_p1 | 1
4486 | COMPARTMENT | UpperIleum | Thickness_p2 | 1
4486 | COMPARTMENT | UpperIleum | Thickness_p3 | 1
4486 | COMPARTMENT | UpperIleum | r1_p0 | 1
4486 | COMPARTMENT | UpperIleum | r1_p1 | 1
4486 | COMPARTMENT | UpperIleum | r2_p0 | 1
4486 | COMPARTMENT | UpperIleum | r2_p1 | 1
4487 | COMPARTMENT | LowerIleum | Default thickness of gut wall | 9
4487 | COMPARTMENT | LowerIleum | L_p0 | 1
4487 | COMPARTMENT | LowerIleum | L_p1 | 1
4487 | COMPARTMENT | LowerIleum | Thickness_p1 | 1
4487 | COMPARTMENT | LowerIleum | Thickness_p2 | 1
4487 | COMPARTMENT | LowerIleum | Thickness_p3 | 1
4487 | COMPARTMENT | LowerIleum | r1_p0 | 1
4487 | COMPARTMENT | LowerIleum | r1_p1 | 1
4487 | COMPARTMENT | LowerIleum | r2_p0 | 1
4487 | COMPARTMENT | LowerIleum | r2_p1 | 1
4488 | COMPARTMENT | Caecum | Default thickness of gut wall | 9
4488 | COMPARTMENT | Caecum | L_p0 | 1
4488 | COMPARTMENT | Caecum | L_p1 | 1
4488 | COMPARTMENT | Caecum | Thickness_p1 | 1
4488 | COMPARTMENT | Caecum | Thickness_p2 | 1
4488 | COMPARTMENT | Caecum | Thickness_p3 | 1
4488 | COMPARTMENT | Caecum | r1_p0 | 1
4488 | COMPARTMENT | Caecum | r1_p1 | 1
4488 | COMPARTMENT | Caecum | r2_p0 | 1
4488 | COMPARTMENT | Caecum | r2_p1 | 1
4489 | COMPARTMENT | ColonAscendens | Default thickness of gut wall | 9
4489 | COMPARTMENT | ColonAscendens | L_p0 | 1
4489 | COMPARTMENT | ColonAscendens | L_p1 | 1
4489 | COMPARTMENT | ColonAscendens | Thickness_p1 | 1
4489 | COMPARTMENT | ColonAscendens | Thickness_p2 | 1
4489 | COMPARTMENT | ColonAscendens | Thickness_p3 | 1
4489 | COMPARTMENT | ColonAscendens | r1_p0 | 1
4489 | COMPARTMENT | ColonAscendens | r1_p1 | 1
4489 | COMPARTMENT | ColonAscendens | r2_p0 | 1
4489 | COMPARTMENT | ColonAscendens | r2_p1 | 1
4490 | COMPARTMENT | ColonTransversum | Default thickness of gut wall | 9
4490 | COMPARTMENT | ColonTransversum | L_p0 | 1
4490 | COMPARTMENT | ColonTransversum | L_p1 | 1
4490 | COMPARTMENT | ColonTransversum | Thickness_p1 | 1
4490 | COMPARTMENT | ColonTransversum | Thickness_p2 | 1
4490 | COMPARTMENT | ColonTransversum | Thickness_p3 | 1
4490 | COMPARTMENT | ColonTransversum | r1_p0 | 1
4490 | COMPARTMENT | ColonTransversum | r1_p1 | 1
4490 | COMPARTMENT | ColonTransversum | r2_p0 | 1
4490 | COMPARTMENT | ColonTransversum | r2_p1 | 1
4491 | COMPARTMENT | ColonDescendens | Default thickness of gut wall | 9
4491 | COMPARTMENT | ColonDescendens | L_p0 | 1
4491 | COMPARTMENT | ColonDescendens | L_p1 | 1
4491 | COMPARTMENT | ColonDescendens | Thickness_p1 | 1
4491 | COMPARTMENT | ColonDescendens | Thickness_p2 | 1
4491 | COMPARTMENT | ColonDescendens | Thickness_p3 | 1
4491 | COMPARTMENT | ColonDescendens | r1_p0 | 1
4491 | COMPARTMENT | ColonDescendens | r1_p1 | 1
4491 | COMPARTMENT | ColonDescendens | r2_p0 | 1
4491 | COMPARTMENT | ColonDescendens | r2_p1 | 1
4492 | COMPARTMENT | ColonSigmoid | Default thickness of gut wall | 9
4492 | COMPARTMENT | ColonSigmoid | L_p0 | 1
4492 | COMPARTMENT | ColonSigmoid | L_p1 | 1
4492 | COMPARTMENT | ColonSigmoid | Thickness_p1 | 1
4492 | COMPARTMENT | ColonSigmoid | Thickness_p2 | 1
4492 | COMPARTMENT | ColonSigmoid | Thickness_p3 | 1
4492 | COMPARTMENT | ColonSigmoid | r1_p0 | 1
4492 | COMPARTMENT | ColonSigmoid | r1_p1 | 1
4492 | COMPARTMENT | ColonSigmoid | r2_p0 | 1
4492 | COMPARTMENT | ColonSigmoid | r2_p1 | 1
4493 | COMPARTMENT | Rectum | Default thickness of gut wall | 9
4493 | COMPARTMENT | Rectum | L_p0 | 1
4493 | COMPARTMENT | Rectum | L_p1 | 1
4493 | COMPARTMENT | Rectum | Thickness_p1 | 1
4493 | COMPARTMENT | Rectum | Thickness_p2 | 1
4493 | COMPARTMENT | Rectum | Thickness_p3 | 1
4493 | COMPARTMENT | Rectum | r1_p0 | 1
4493 | COMPARTMENT | Rectum | r1_p1 | 1
4493 | COMPARTMENT | Rectum | r2_p0 | 1
4493 | COMPARTMENT | Rectum | r2_p1 | 1
4838 | ORGAN | Gallbladder | Gallbladder ejection fraction | 9
4838 | ORGAN | Gallbladder | Gallbladder ejection half-time | 9
5638 | ORGAN | Breasts | Acidic phospholipids [mg/g] - RR | 1
5638 | ORGAN | Breasts | Allometric scale factor | 1
5638 | ORGAN | Breasts | Density (tissue) | 1
5638 | ORGAN | Breasts | Fraction interstitial | 1
5638 | ORGAN | Breasts | Fraction vascular | 1
5638 | ORGAN | Breasts | Specific blood flow rate | 1
5638 | ORGAN | Breasts | Vf (acidic phospholipids)-WS | 1
5638 | ORGAN | Breasts | Vf (extracellular water)-RR | 1
5638 | ORGAN | Breasts | Vf (intracellular water)-RR | 1
5638 | ORGAN | Breasts | Vf (lipid) | 1
5638 | ORGAN | Breasts | Vf (neutral lipid)-PT | 1
5638 | ORGAN | Breasts | Vf (neutral lipid)-RR | 1
5638 | ORGAN | Breasts | Vf (neutral lipid)-WS | 1
5638 | ORGAN | Breasts | Vf (neutral phospholipid)-RR | 1
5638 | ORGAN | Breasts | Vf (neutral phospholipid, plasma)-WS | 1
5638 | ORGAN | Breasts | Vf (phospholipid)-PT | 1
5638 | ORGAN | Breasts | Vf (protein) | 1
5638 | ORGAN | Breasts | Vf (protein)-WS | 1
5638 | ORGAN | Breasts | Vf (water) | 1
5638 | ORGAN | Breasts | Vf (water)-PT | 1
5638 | ORGAN | Breasts | Vf (water)-WS | 1
5638 | ORGAN | Breasts | Volume | 1
5639 | ORGAN | Myometrium | Acidic phospholipids [mg/g] - RR | 1
5639 | ORGAN | Myometrium | Allometric scale factor | 1
5639 | ORGAN | Myometrium | Density (tissue) | 1
5639 | ORGAN | Myometrium | Fraction interstitial | 1
5639 | ORGAN | Myometrium | Fraction vascular | 1
5639 | ORGAN | Myometrium | Specific blood flow rate | 1
5639 | ORGAN | Myometrium | Vf (acidic phospholipids)-WS | 1
5639 | ORGAN | Myometrium | Vf (extracellular water)-RR | 1
5639 | ORGAN | Myometrium | Vf (intracellular water)-RR | 1
5639 | ORGAN | Myometrium | Vf (lipid) | 1
5639 | ORGAN | Myometrium | Vf (neutral lipid)-PT | 1
5639 | ORGAN | Myometrium | Vf (neutral lipid)-RR | 1
5639 | ORGAN | Myometrium | Vf (neutral lipid)-WS | 1
5639 | ORGAN | Myometrium | Vf (neutral phospholipid)-RR | 1
5639 | ORGAN | Myometrium | Vf (neutral phospholipid, plasma)-WS | 1
5639 | ORGAN | Myometrium | Vf (phospholipid)-PT | 1
5639 | ORGAN | Myometrium | Vf (protein) | 1
5639 | ORGAN | Myometrium | Vf (protein)-WS | 1
5639 | ORGAN | Myometrium | Vf (water) | 1
5639 | ORGAN | Myometrium | Vf (water)-PT | 1
5639 | ORGAN | Myometrium | Vf (water)-WS | 1
5639 | ORGAN | Myometrium | Volume | 1
5640 | ORGAN | Endometrium | Acidic phospholipids [mg/g] - RR | 1
5640 | ORGAN | Endometrium | Allometric scale factor | 1
5640 | ORGAN | Endometrium | Density (tissue) | 1
5640 | ORGAN | Endometrium | Fraction interstitial | 1
5640 | ORGAN | Endometrium | Fraction vascular | 1
5640 | ORGAN | Endometrium | Specific blood flow rate | 1
5640 | ORGAN | Endometrium | Vf (acidic phospholipids)-WS | 1
5640 | ORGAN | Endometrium | Vf (extracellular water)-RR | 1
5640 | ORGAN | Endometrium | Vf (intracellular water)-RR | 1
5640 | ORGAN | Endometrium | Vf (lipid) | 1
5640 | ORGAN | Endometrium | Vf (neutral lipid)-PT | 1
5640 | ORGAN | Endometrium | Vf (neutral lipid)-RR | 1
5640 | ORGAN | Endometrium | Vf (neutral lipid)-WS | 1
5640 | ORGAN | Endometrium | Vf (neutral phospholipid)-RR | 1
5640 | ORGAN | Endometrium | Vf (neutral phospholipid, plasma)-WS | 1
5640 | ORGAN | Endometrium | Vf (phospholipid)-PT | 1
5640 | ORGAN | Endometrium | Vf (protein) | 1
5640 | ORGAN | Endometrium | Vf (protein)-WS | 1
5640 | ORGAN | Endometrium | Vf (water) | 1
5640 | ORGAN | Endometrium | Vf (water)-PT | 1
5640 | ORGAN | Endometrium | Vf (water)-WS | 1
5640 | ORGAN | Endometrium | Volume | 1
5641 | ORGAN | PlacentaMaternal | Acidic phospholipids [mg/g] - RR | 1
5641 | ORGAN | PlacentaMaternal | Allometric scale factor | 1
5641 | ORGAN | PlacentaMaternal | Density (tissue) | 1
5641 | ORGAN | PlacentaMaternal | Fraction interstitial | 1
5641 | ORGAN | PlacentaMaternal | Fraction vascular | 1
5641 | ORGAN | PlacentaMaternal | Specific blood flow rate | 1
5641 | ORGAN | PlacentaMaternal | Vf (acidic phospholipids)-WS | 1
5641 | ORGAN | PlacentaMaternal | Vf (extracellular water)-RR | 1
5641 | ORGAN | PlacentaMaternal | Vf (intracellular water)-RR | 1
5641 | ORGAN | PlacentaMaternal | Vf (lipid) | 1
5641 | ORGAN | PlacentaMaternal | Vf (neutral lipid)-PT | 1
5641 | ORGAN | PlacentaMaternal | Vf (neutral lipid)-RR | 1
5641 | ORGAN | PlacentaMaternal | Vf (neutral lipid)-WS | 1
5641 | ORGAN | PlacentaMaternal | Vf (neutral phospholipid)-RR | 1
5641 | ORGAN | PlacentaMaternal | Vf (neutral phospholipid, plasma)-WS | 1
5641 | ORGAN | PlacentaMaternal | Vf (phospholipid)-PT | 1
5641 | ORGAN | PlacentaMaternal | Vf (protein) | 1
5641 | ORGAN | PlacentaMaternal | Vf (protein)-WS | 1
5641 | ORGAN | PlacentaMaternal | Vf (water) | 1
5641 | ORGAN | PlacentaMaternal | Vf (water)-PT | 1
5641 | ORGAN | PlacentaMaternal | Vf (water)-WS | 1
5641 | ORGAN | PlacentaMaternal | Volume | 1
5642 | ORGAN | PlacentaFetal | Acidic phospholipids [mg/g] - RR | 1
5642 | ORGAN | PlacentaFetal | Allometric scale factor | 1
5642 | ORGAN | PlacentaFetal | Density (tissue) | 1
5642 | ORGAN | PlacentaFetal | Fetal Hematocrit | 1
5642 | ORGAN | PlacentaFetal | Fraction interstitial | 1
5642 | ORGAN | PlacentaFetal | Fraction vascular | 1
5642 | ORGAN | PlacentaFetal | Specific blood flow rate | 1
5642 | ORGAN | PlacentaFetal | Vf (acidic phospholipids)-WS | 1
5642 | ORGAN | PlacentaFetal | Vf (extracellular water)-RR | 1
5642 | ORGAN | PlacentaFetal | Vf (intracellular water)-RR | 1
5642 | ORGAN | PlacentaFetal | Vf (lipid) | 1
5642 | ORGAN | PlacentaFetal | Vf (neutral lipid)-PT | 1
5642 | ORGAN | PlacentaFetal | Vf (neutral lipid)-RR | 1
5642 | ORGAN | PlacentaFetal | Vf (neutral lipid)-WS | 1
5642 | ORGAN | PlacentaFetal | Vf (neutral phospholipid)-RR | 1
5642 | ORGAN | PlacentaFetal | Vf (neutral phospholipid, plasma)-WS | 1
5642 | ORGAN | PlacentaFetal | Vf (phospholipid)-PT | 1
5642 | ORGAN | PlacentaFetal | Vf (protein) | 1
5642 | ORGAN | PlacentaFetal | Vf (protein)-WS | 1
5642 | ORGAN | PlacentaFetal | Vf (water) | 1
5642 | ORGAN | PlacentaFetal | Vf (water)-PT | 1
5642 | ORGAN | PlacentaFetal | Vf (water)-WS | 1
5642 | ORGAN | PlacentaFetal | Volume | 1
5643 | ORGAN | Fetus | Allometric scale factor | 1
5643 | ORGAN | Fetus | Density (tissue) | 1
5643 | ORGAN | Fetus | Fetal Hematocrit | 1
5643 | ORGAN | Fetus | Fraction vascular | 1
5643 | ORGAN | Fetus | Vf (extracellular water)-RR | 1
5643 | ORGAN | Fetus | Vf (lipid) | 1
5643 | ORGAN | Fetus | Vf (protein) | 1
5643 | ORGAN | Fetus | Vf (protein)-WS | 1
5643 | ORGAN | Fetus | Vf (water) | 1
5643 | ORGAN | Fetus | Vf (water)-PT | 1
5643 | ORGAN | Fetus | Vf (water)-WS | 1
5643 | ORGAN | Fetus | Volume | 1
5644 | ORGAN | AmnioticFluid | Allometric scale factor | 1
5644 | ORGAN | AmnioticFluid | Density (tissue) | 1
5644 | ORGAN | AmnioticFluid | Volume | 1
5645 | ORGAN | ArterialBlood_UmbilicalCord | Allometric scale factor | 1
5645 | ORGAN | ArterialBlood_UmbilicalCord | Density (tissue) | 1
5645 | ORGAN | ArterialBlood_UmbilicalCord | Fetal Hematocrit | 1
5645 | ORGAN | ArterialBlood_UmbilicalCord | Volume | 1
5646 | ORGAN | VenousBlood_UmbilicalCord | Allometric scale factor | 1
5646 | ORGAN | VenousBlood_UmbilicalCord | Density (tissue) | 1
5646 | ORGAN | VenousBlood_UmbilicalCord | Fetal Hematocrit | 1
5646 | ORGAN | VenousBlood_UmbilicalCord | Volume | 1
5647 | NEIGHBORHOOD | PlacentaMaternal_pls_PlacentaFetal_cell | Surface area (plasma/intracellular) | 1
</details>
