### ISSUE TITLE
Data importer - parsing units should be case insensitive

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1949]
Now "mg/mL" is not recognized, but "mg/ml" is.

**Comment by msevestre** [comment]
what the heck?!?

**Comment by msevestre** [comment]
All of this should be handled at the unit level anyways. We have the methods for this.

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/229368164-e32e3120-13be-44d8-887b-931680b4ca0e.png)
