### ISSUE TITLE
Only export species independent parameters to spatial structure

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1963]
@msevestre commented on [Wed Apr 05 2023](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2589)

---

@msevestre commented on [Wed Apr 05 2023](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2589#issuecomment-1497900847)

@Yuri05 
```
OneTimeSetUp: PKSim.Core.Services.CannotCreateSimulationException : Transport 'GallbladderEmptying' with path 'simulation|Neighborhoods|Gallbladder_Lumen_duo|C1|GallbladderEmptying' references an entity with path 'simulation|Organism|Gallbladder|Gallbladder ejection fraction' that cannot be found
Transport 'GallbladderEmptying' with path 'simulation|Neighborhoods|Gallbladder_Lumen_duo|C1|GallbladderEmptying' references an entity with path 'simulation|Organism|Gallbladder|Gallbladder ejection half-time' that cannot be found
Multiple Errors were found for 'GallbladderEmptying'
Transport 'PassiveDiffusionPlsToSaliva' with path 'simulation|Neighborhoods|Saliva_slv_Saliva_slv|C1|PassiveDiffusionPlsToSaliva' references an entity with path 'simulation|Organism|Saliva|SalivaGland|..|Saliva flow rate' that cannot be found
```

what could be the problem?

---

@msevestre commented on [Wed Apr 05 2023](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2589#issuecomment-1497910998)

hum I think this is running before we create dynamic parameters in core

**Comment by PavelBal** [comment]
The species is Human?

**Comment by msevestre** [comment]
Yep. The problem is two fold
1-we need to change the validation order (e.g..only validate after dynamic parameters are added)
2-export also distributed parameters. This is missing

1 is on core
2 core and PKSim
