### ISSUE TITLE
Residuals vs. Time plots: Observed values below LLOQ produce residuals=0

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#1974]
In the project attached [ObsData_LLOQ.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/11214579/ObsData_LLOQ.zip) there are some values below LLOQ in the 2 observed data sets.
<img width="450" src="https://user-images.githubusercontent.com/25061876/231545519-cfdac831-4d21-4be2-8605-89c0f03936a1.png">

In a **Predicted vs. Observed** plot those values are shown correctly.
However in a Residuals vs. Time plot all residuals are calculated(?) and shown as zero.
<img width="420" src="https://user-images.githubusercontent.com/25061876/231546054-15fada4b-37b9-4fbf-b6b3-7196a6832d6b.png"><img width="420" src="https://user-images.githubusercontent.com/25061876/231546590-8dd94fea-fea1-40d9-927c-736d212030e8.png">

**Comment by PavelBal** [comment]
I assume, that the default setting is to set simulated valus BLOQ to LLOQ/2 and then the residuals are correctly calculated.

**Comment by Yuri05** [comment]
> I assume, that the default setting is to set simulated valus BLOQ to LLOQ/2 and then the residuals are correctly calculated.

I think you are right. (Not LLOQ/2 but LLOQ though).
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/50a7aa040611e25be40541b8a8748976946808a7/src/OSPSuite.Core/Domain/Services/ResidualCalculatorForSimulationOutputAsObservedDataLLOQ.cs#L13-L36

**Comment by PavelBal** [comment]
@Yuri05 Looking at the code, I wonder if simulated value below LLOQ is ALWAYS set to lloq? I suggest to only set it to LLOQ if the corresponding observed value is LLOQ. In case observed value is >LLOQ, calculating the error to actually simulated value would make more sense.
