### ISSUE TITLE
What should happen when merging a module results in Neighborhood pointing to non existing compartment

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1985]
SAy I have sthg like this
* I have a PKSim module
* I want to create my own kidney module. 
   * it will have a kidney with parent Organism
   * bunch of neighborhoods etc

The old neighborhood, from he first module, might be pointing to compartment that do not exist anymore once new kidney is merged with old kidney. What should happen? 

Right now the simulation cannot be constructed. I think we should ignore those neighborhoods
thoughts?  
@PavelBal @Yuri05 @stephanschaller @rwmcintosh

**Comment by PavelBal** [comment]
Ignore

**Comment by Yuri05** [comment]
Ignore with Warnings ("Neighborhood XY will not be added due to missing Neighbor X")

**Comment by msevestre** [comment]
We will need to add the concept of log during merge i think. This is not available at the moment
