### ISSUE TITLE
DO not create one tab for each Obs Data in PI

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#2012]
see https://github.com/Open-Systems-Pharmacology/Forum/discussions/1535#discussioncomment-5951495

@Yuri05 @PavelBal 
I think we had discussed this. We should only have one. Selecting the entry at the top should update the active view instead of having one tab for each. This is IMO urgent

**Comment by Yuri05** [comment]
Yes. Actually the same strategy as in observed data import

**Comment by msevestre** [comment]
yep

**Comment by PavelBal** [comment]
This is done already.
