### ISSUE TITLE
Data importer - parsing units should be case sensitive

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#2019]
A while ago I created an issue that parsing of units during import should be case-insensitive https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1949

Unfortunately, I have a case where this leads to wrong dimension - when trying to import `µm` of the dimension `Lenght`, the importer regodnizes it as `µM` of the dimension `Concentration (molar)`.

**Comment by PavelBal** [comment]
Yes but then I would vote for having it case-sensitive. Otherwise there is no way to import anything other than `dm` for length without having to manually change the dimension (== no way to automatize it through R)

**Comment by Yuri05** [comment]
use` µmol/L` instead

**Comment by Yuri05** [comment]
The most flexible way:
1) Try to find the unit **case sensitive** first. If found: use it
2) If not found: try to find the unit **case insensitive**

**Comment by msevestre** [comment]
I think this is the way it's actually implemented. First case sensitive, then case insensitive

**Comment by Yuri05** [comment]
>I think this is the way it's actually implemented. First case sensitive, then case insensitive 

But then `µm `should be recognized as `µm `and not as `µM`
@PavelBal Can you describe the steps to reproduce you problem?

**Comment by georgeDaskalakis** [comment]
It is not an issue of unit recognition but of automatically detecting the correct dimension. So  (if I am not mistaken by what Pavel describes), in the calculation of the dimension from a unit given in an excel file:

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/50a7aa040611e25be40541b8a8748976946808a7/src/OSPSuite.Infrastructure.Import/Core/DataFormat/AbstractColumnsDataFormat.cs#LL159C1-L167C8

we are not trying case sensitive first, we just get the first dimension that has such a unit. In Pavel's case with µm , the first dimension found that has such a unit ( µM in this case, since case insensitive) would be Concentration (molar).

**Comment by georgeDaskalakis** [comment]
> I think this is the way it's actually implemented. First case sensitive, then case insensitive

Actually implementing this would be a fix that would keep the correct behaviour also for #1949

**Comment by Yuri05** [comment]
>It is not an issue of unit recognition but of automatically detecting the correct dimension. So (if I am not mistaken by what Pavel describes), in the calculation of the dimension from a unit given in an excel file:

I think it would be better to get the dimension from unit via `DimensionTask.DimensionForUnit()` and then check if the retrieved dimension is not null and is contained in `supportedDimensions`

**Comment by georgeDaskalakis** [comment]
@Yuri05 yeap this is a better solution to avoid code duplication - and yes it would have exactly the same result. If no objections I would implement this.

**Comment by PavelBal** [comment]
No objections.

**Comment by msevestre** [comment]
Yes. I thought this was the code used indeed. Let's update

**Comment by PavelBal** [comment]
This is NOT fixed

[UnitCaseInsensitive.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/11908069/UnitCaseInsensitive.xlsx)

the unit is "µm", which should be recognized as the dimension "Length". however, this is being recognized as "Concentration (molar)", probably because it thinks it is "µM"
