### ISSUE TITLE
Expression profile values are not applied

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#2034]
- Re-create a PK-Sim project “Fluvoxamine-Omeprazole-DDI” from snapshot with PK-Sim V 11.2

- Save project with V11.2

- Export simulation “omeprazole 40mg po asian EM fluvoxamine 50mg po” to pkml

- Open Simulation created with V11.2 in MoBi OSMOSES

- Create new expression profile
  - CYP3A4 - array
  - CYP3A4 PCR
  - Database query using different sources (Array and PCR)

Compare the expression profiles - they have different values:

![image](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/25903040/f3f1dd3d-b943-4c1a-85d2-174023beb1ba)

- Create a simulation using the **Array** profile. The values are NOT applied.

**Comment by msevestre** [comment]
Hum what values are then applied??
@rwmcintosh can you check this out? This sounds like a user error to me
@PavelBal we do not have a fully functioning conversion from 11.2 to 12 yet. So I'd strongly suggest creating new instead of using 11.2 stuff. Snapshot might be ok to load in v12 but I am not sure either

**Comment by msevestre** [comment]
Also if you can attach the Mobi project to the issue, this makes our life super duper better

**Comment by rwmcintosh** [comment]
The simulation transfer from 11.2 has relative expressions in the Parameter Values Building Block. My understanding is those are applied last, and so, they win.

**Comment by msevestre** [comment]
Correct. PSV wins

**Comment by PavelBal** [comment]
Ok, makes sense, indeed. However, I am sure this will lead to confusion for the users.... I am thinking if we could show a warning in this case.
