### ISSUE TITLE
x and y axis caption of importer graph misleading

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#2043]
![image](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/1041237/8fe35e3c-6a9e-419a-8f48-084f5131db2d)

Can we have the x and y axis show the caption in the table instead of the dimension? (e,g PMA [years] and Ontogey Factor) instead of Dimensionless?

or is there a `good` reason for this mismatch?

**Comment by Yuri05** [comment]
> or is there a `good` reason for this mismatch?

I don't see any reason. The axis captions should be indeed those from the table.

**Comment by georgeDaskalakis** [comment]
@msevestre @Yuri05 and the dimension should be mentioned in parentheses, or not at all?

**Comment by Yuri05** [comment]
For the X-axis: yes. For Y: no. So in fact I would like to see exactly the same captions as in the table
![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/25061876/01619b31-d5d4-4df0-9378-3c5fe3fd4800)

(I think in general for any plots: if the dimension is `dimensionless`, it should not be displayed as part of the caption.)

**Comment by georgeDaskalakis** [comment]
OK, so always display the caption, if not dimensionless also display the unit.
