### ISSUE TITLE
Observed data importer configuration: formula cache?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#2069]
It does not hurt, but I just wonder: why do we have a `FormulaCache `node when saving observed data import configuration to XML?

![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/25061876/39e6802d-bf52-47b0-a5b5-0c1c6f463dc3)

**Comment by rwmcintosh** [comment]
This method needs to be updated

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/56812fbe0d618b882f0e300b562b9ee49d32a8cd/src/OSPSuite.Core/Serialization/Xml/PKMLPersistor.cs#L161-L168
