### ISSUE TITLE
Feature request: Generic path to access lumen compartment from mucosa

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#2086]
Sometimes it is necessary to access a parameter or a species in lumen from the mucosal compartment.
Example: to describe the rate of a process in interstitial of duodenum, I need the amount of Compound A in the lumen of duodenum. 

It would be great to have a path concept to access luminal compartments of the respective mucosal compartments and vise versa. Something like:

Local Reference Point: "Organism|SmallIntestine|Mucosa|Duodenum|Interstitial"
Path to a reference: "..|..|LUMEN|CompoundA"

Local Reference Point: "Organism|Lumen|Duodenum"
Path to a reference: "..|MUCOSA|Interstitial|Volume"

**Comment by msevestre** [comment]
@PavelBal @Yuri05 
LUMEN_SEGMENT or <LUMEN_SEGMENT> ?

I think LUMEN_SEGMENT is probably fine. We used <NBH> becuase NBH can probably showup inadvertently in a name

**Comment by PavelBal** [comment]
Sweet!
