### ISSUE TITLE
Path keywords extensions: next/previous lumen segment

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#2091]
The idea is similar to #2086:
* introduce the new keywords LUMEN_NEXT_SEGMENT and LUMEN_PREVIOUS_SEGMENT (or LUMEN_PREV_SEGMENT ?)
* move/copy the list of the lumen segments from PK-Sim to the Core
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/e0f7adb278e0f80212114d00db29920d6eca24b8/src/PKSim.Core/CoreConstants.cs#L381-L382
* path resolution: similar to the LUMEN_SEGMENT keyword with the only difference, that **not the same** lumen segment is taken but the **next/previous** one, e.g.

- `Organism|Lumen|Stomach|LUMEN_NEXT_SEGMENT|P1` evaluates to `Organism|Lumen|Duodenum|P1`
- `Organism|Lumen|Stomach|LUMEN_PREV_SEGMENT|P1` - Error (no previous segment)
- `Organism|Lumen|Duodenum|LUMEN_PREV_SEGMENT|P1` evaluates to `Organism|Lumen|Stomach|P1`

This would allow simplifying e.g. the formulas below

![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/25061876/f266b75d-1971-4e28-9b36-4f5223652a16)

**Comment by Yuri05** [comment]
@PavelBal @msevestre as discussed

**Comment by msevestre** [comment]
I don't quite get how it would simplify the formula.it can only work for relative formula right?

because in your example, you are using Stomach so you know that you are in stomach.
Anyways, I'll implement for both but I think this ONLY makes sense for relative paths

**Comment by Yuri05** [comment]
> I don't quite get how it would simplify the formula.it can only work for relative formula right?
> 
> because in your example, you are using Stomach so you know that you are in stomach. Anyways, I'll implement for both but I think this ONLY makes sense for relative paths

if you look in the formula, there are 3 refs to the lumen segment:
* `...|Caecum|...` my parameter is in caecum, so those can be just replaced with relative paths
* `...|ColonAscendens|...` - would become something like `..|..|LUMEN_NEXT_SEGMENT|...`
(`..|..` would resolve to `Organism|Lumen|Caecum` and thus the whole Formula would resolve to `Organism|Lumen|CaecColonAscendens|...`)
* `...|LowerIleum|...` - would become something like `..|..|LUMEN_PREV_SEGMENT|...`

With this, the formula would be the same for all segments.
In the current formula absolute paths are used because in each segment I exactly know what "my segment", next segment and previous segment are.
