### ISSUE TITLE
Too many results with wildcards

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#2098]
E.g the search for `getAllMoleculesMatching("Organism|Liver|Periportal|**|CYP3A4*", sim)` returns also 
**Alfentanil-CYP3A4-1st order CL Metabolite** - which is wrong

<img width="600" src="https://github.com/Open-Systems-Pharmacology/OSPSuite-R/assets/25061876/465f7993-c1ec-4260-a16d-1130a2b0d4f3">

When I look for `getAllMoleculesMatching("Organism|Liver|Periportal|**|CYP3A4", sim)` 
(removed the wildcard at the end of the search path) - the result is as expected

<img width="500" src="https://github.com/Open-Systems-Pharmacology/OSPSuite-R/assets/25061876/88d17838-f2c5-4916-b48a-4e76a209edea">

**Comment by Yuri05** [comment]
moving to core then

**Comment by msevestre** [comment]
this is becuase of the **
