### ISSUE TITLE
Simplify two pores model

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#2130]
- [x] Remove molecules `FcRn Kinetics...` and replace by container criteria of the respective reactions. :arrow_right: https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2804
- [ ] #2355
- [ ] #2356
- [x] Reactions "FcRn binding Fluvoxamine in endosomal/plasma/etc space" should use sum formulas for total amounts of molecules. -> Create parameter "TotalM" in the reaction summing up all amounts of this molecule in "Endosome" (example) and "TotalMC" for the complex. :arrow_right: https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1347

**Comment by Yuri05** [comment]
@PavelBal I suggest creating new issue(s) for the 2 open topics ("Extend / do not extend...") and closing this issue.
