### ISSUE TITLE
Cloning a simulation duplicated observed data mapping

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#2146]
1. Create a simulation, add observed data, and map it to a simulation output
2. Clone the simulation -> The data mapping in the "Observed Data" tab is duplicated.

**Comment by msevestre** [comment]
Clone where? PKSIm or MoBi?

**Comment by Yuri05** [comment]
Assuming it's MoBi - the very same issue was fixed in PK-Sim a while ago
https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/2628

**Comment by PavelBal** [comment]
It was PK-Sim, so can be closed.

Juri Solodenko ***@***.***> schrieb am Fr., 20. Okt. 2023,
17:30:

**Comment by Yuri05** [comment]
Fixed in upcoming V12
