### ISSUE TITLE
Working Journal hides related items

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#2148]
[03_Bugs.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/12686235/03_Bugs.zip)
e.g. open the journal in the attached project. It shows no related items.
However there is 1 related item in there (simulation).

Luckily we have the "Load All" button and if I click on it - the simulation is loaded.
But it took me some time to figure out that the simulation did not disappear in the journal 😄 

![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/2cc415ec-8f1d-4338-8558-5cc5bcfc3a6b)

**Comment by msevestre** [comment]
can't reproduce 
![image](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/1041237/a6c31b00-0cb8-4b80-ac33-e73dadbaf2b7)

**Comment by msevestre** [comment]
can on my laptop screen
![Uploading image.png…]()
