### ISSUE TITLE
Removing observed data entry from simulation - do not show a warning

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#2150]
Removing observed data from the "Observed data" tab of a simulation shows a warning every time:

![image](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/25903040/47e82c77-ace1-46dd-b6df-b3136b12203c)

This is annoying and unnecessary. Add an option "Do not ask again".

**Comment by rwmcintosh** [comment]
I am thinking that we can store this preference _per-session_ instead of serializing in user preferences. That keeps us from having to implement user controls in each application to toggle it.

@PavelBal @msevestre  @Yuri05 - what do you think? To my knowledge we don't have any precedence?
