### ISSUE TITLE
Add distinction between PK-Sim and extension modules

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/OSPSuite.Core#2151]
The module version calculation includes typed versions for all the building blocks.

When trying to compare the module versions as exported by PK-Sim vs. as imported by MoBi, the module version does not match. That's because of platform-specific types such as PKSimSpatialStructure, MoBiSpatialStructure, and MoBiReactionBuildingBlock.

For those types, I think we should translate those platform types into Core types so that the module version is the same when exported from PK-Sim and imported to MoBi.

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/src/OSPSuite.Core/Domain/Module.cs#L50-L59

On the other hand, the module **is** different - in the sense that it comprises different building blocks in PK-Sim and MoBi. We could implement a separate platform agnostic calculation just to accommodate this use case.

To my knowledge, we haven't needed this concept of consistent building block versions across applications.

**Comment by rwmcintosh** [comment]
I want to create an ExtendedProperty with the module version at the time of PK-Sim export for this feature below.

https://github.com/Open-Systems-Pharmacology/MoBi/issues/1141

**Comment by rwmcintosh** [comment]
We could do it a little differently - 
during import if the module has extended property ```PKSimVersion``` but does not have ```PkSimModuleVersion``` then we can set it during import.

If the module is exported from mobi and imported again, the ```PKSimModuleVersion``` would not be changed since it's already been set once.

**Comment by msevestre** [comment]
Yeah I think this is an easy approach. When we import the first time and we don't have the PKSimVersion, we compute it and we save it. then it become immutable
