### ISSUE TITLE
Show tooltips for longer time

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#2195]
This is also valid for MoBi.

Tooltips disappear quite fast, which can be annoying for large formulas. Extending the time they are should would be great.

**Comment by PavelBal** [comment]
Hmmm this is still too fast.

**Comment by rwmcintosh** [comment]
Should we just go for 5 minutes if it's possible? You can dismiss it by moving the mouse.

**Comment by PavelBal** [comment]
Yes why not
