### ISSUE TITLE
`potentialVariableParameterPathsFor()` in R does not return all expected parameters

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#2232]
[test.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/15075970/test.zip)
S. discussion in https://github.com/Open-Systems-Pharmacology/Forum/discussions/1754

Parameter **"Alfentanil|CYP3A4-test|Ki"** is not returned by `potentialVariableParameterPathsFor()` in R - and I don't see any reason for this.
Paramer is defined by const. formula, is not zero, not table, not categorical, not read-only, not advanced, has CanBeVaried=true - so no reason, why it should not be returned.
<img width="750" src="https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/25061876/147f2993-c700-4c82-8e3e-1aaf40098bd7">

In fact if I load the simulation in PK-Sim or MoBi - I can select the parameter for sensitivity calculation via "Add All Constants" (even in the simple mode) - so obviously none of the "Can be used for sensitivity" rules is violated.
<img width="700" src="https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/25061876/278f3438-e988-40b3-9b2f-c251754ce101">

From looking at the code - I don't see any other rules, which might be violated when retrieving the parameter to R via `potentialVariableParameterPathsFor()`
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/0d01657eb8defd5501d25ffbcf21c26fa1869a06/src/OSPSuite.R/Mapper/SensitivityAnalysisToCoreSensitivityAnalysisMapper.cs#L56-L59

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/0d01657eb8defd5501d25ffbcf21c26fa1869a06/src/OSPSuite.R/Services/ParameterAnalysableParameterSelector.cs#L8-L15

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/0d01657eb8defd5501d25ffbcf21c26fa1869a06/src/OSPSuite.Core/Domain/ParameterExtensions.cs#L46-L49

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/0d01657eb8defd5501d25ffbcf21c26fa1869a06/src/OSPSuite.Core/Domain/Formulas/FormulaExtensions.cs#L21

**Comment by msevestre** [comment]
Not sure. Looks like this is an error in core. 
but I am sold anyways so let’s do it lol

**Comment by msevestre** [comment]
I am going to look at this today

**Comment by msevestre** [comment]
in core, the parameter can be varied in the simulation

**Comment by msevestre** [comment]
however 
![image](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/1041237/859469dd-9812-4148-bc31-87e6b2cfeed2)

**Comment by msevestre** [comment]
ok for me this is the right behavior. I am not sure if this should be documented somewhere. I'll create an issue in ospsuite-r

By design
