### ISSUE TITLE
Why two modules with one building block each and one module with the two building blocks behave differently

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/OSPSuite.Core#2265]
@PavelBal please include a small project

**Comment by PavelBal** [comment]
[PV_notApplied.zip](https://github.com/user-attachments/files/15901823/PV_notApplied.zip)

Parameter values from PV are just not applied properly. In this example, a parameter `ParamA` is defined in the spatial structure with an equation that cannot be resolved (wrong formula). The value is also defined in the PV BB, where the value is set to a constant 0. So the simulation should have 0 for this parameter. However, creation of the simulation fails.

**Comment by msevestre** [comment]
@rwmcintosh @PavelBal CAn we verify that this is still a bug?

**Comment by msevestre** [comment]
ok just tried. I could create the simulation  and value is 0
![Image](https://github.com/user-attachments/assets/ee301a04-8926-4df0-ae8c-9efc3a169c4e)
