### ISSUE TITLE
New selection field for "value origin mode"

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#227]
Insert a selection field  and corresponding enumeration for “Value origin mode” with (perhaps iconized) entries e.g. for PK-Sim-DB, Article, Report, Internet, Project data, Parameter Identification, Manual Fit, Assumption, Unknown.

Background:
For model building documentation it is important to document the origin of all parameter values. 
Value description should be used to document "origin mode" and data source of all values carefully.

Origin mode should be entered by standardized selection (instead of typing it manually), which is easier for the user and allows filtering. By usage of different icons the space for display of the different origin modes can be minimized.

**Comment by msevestre** [comment]
Icons required for 
Article
Report
Internet
Manual Fit
Assumption
Unknown

What is meant with Project data?

**Comment by ju-rgen** [comment]
Data got from Project team by files (e.g. xlsx) or emails, but not in a formal report.

**Comment by tobiasK2001** [comment]
I would prefer "personal communication" instead of project data as it is referring more specifically to the process where and how the data came from. In most projects the data comes either by reports or by some preliminary excel files via mails. The user is free to further specify what type of communication he had.

**Comment by ju-rgen** [comment]
It seems to be reasonable to distinguish between value origin mode **PK-Sim-DB** and **PK-Sim-Default**. For instance the values for Density etc. of molecules are not taken from a DB, but are just default values, which are not used in all cases.
