### ISSUE TITLE
Impossible to close editor on PI output mapping error

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/OSPSuite.Core#2299]
In a PI when mapping outputs if the user selects observed data with inconsistent dimension, and does not have any observed data with a consistent dimension then it becomes impossible to exit the PI editor, and you cannot delete the mapping.

**Comment by PavelBal** [comment]
Try hitting ESC.

**Comment by rwmcintosh** [comment]
ah, that works too. But we should probably allow the user to delete the mapping without knowing this escape key

**Comment by rwmcintosh** [comment]
However, this is consistent with other editors where validation fails in the same way with a combo box.
