### ISSUE TITLE
Set "value origin mode" to “Assumption” or "Unknown" at manual changes.

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#231]
Set "value origin mode"  to “Assumption” or "Unknown" when manually changing a value in a simulation.

If the user has taken the value from a certain report for example, he should select the right "value origin mode" actively afterwards.
Otherwise the risk is too high, that a user changes a value, forgets about updating the "value origin mode" (and "value description") and a "too qualified" "value origin mode" like "Report" or "Article" remains for a users assumption.

**Comment by msevestre** [comment]
Why is this only done in a simulation? Does not it apply to Building Block parameters as well?
Do we always overwrite the mode or only when the mode as predefined values?
This should be done in the task or in the command. If it needs to be undone with the value, it needs to be part of the command

**Comment by msevestre** [comment]
This needs to be done in PKSim and MoBi

**Comment by ju-rgen** [comment]
Right, this applies to Simulations and Building Blocks.
I do not understand the alternative "only when the mode as predefined values", but a general (temporary) reset to "Unknown" seems to be ok.
To encapsulate this into a command: 
should the reset and the user defined new entry be two independent steps 
or should the user be asked to confirm the value of "Unknown" or alternativly selecting another value (only one step)?

**Comment by msevestre** [comment]
Let's discuss about that requirement. I am not sure that I understand your proposals

**Comment by msevestre** [comment]
This is implemented in PKSim as well

**Comment by msevestre** [comment]
After discussing the implementation with @Yuri05, it seems more appropriate to implement the feature as follow:
- if the user sets a value and the value origin is **UNDEFINED** (e.g. nothing was set before), the value origin should be set to **UNKNOWN**
- Otherwise, do not update the value origin. Resetting the value origin to **UNDEFINED** or **MANUAL FIT** everytime a value is entered does not seem like the right fit

**Comment by msevestre** [comment]
@ju-rgen @Yuri05 No feedback here on this time critical issue so this will be the implementation. Thanks
