### ISSUE TITLE
Fill "value description" and "value origin mode" automatically, when copying a value from a web page

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#232]
When copying a value from a web page in a browser, set "value origin mode" to Internet and "value description" to address like this is done using OneNote.

This automatic filling saves time of the user and prevents from typing mistakes.

**Comment by msevestre** [comment]
It seems to be possible. We need to override the paste funtionality in devexpress in that case for the value field. While the implementation can be done in core, the usage of the paste code will need to be done in all views were value description is available, both in MoBi and PKSim

**Comment by ju-rgen** [comment]
Lets spend one day to see, if this is doable in standard situations, if not, skip the issue.

**Comment by msevestre** [comment]
Standard situation == parameter lists view (EditParameterListView  in MoBi and MultipleParameterView in PKSim)

**Comment by msevestre** [comment]
@Yuri05 Do you think that this guy is still required after our discussion with Source and Method?

**Comment by msevestre** [comment]
Especially considering the fact that pdf are often read from a webbrowser. Implementing this feature would most often than note set the value to the wrong source

**Comment by Yuri05** [comment]
>Especially considering the fact that PDF are often read from a web browser. Implementing this feature would most often than not set the value to the wrong source

Agree. Would also propose to drop this feature request

**Comment by msevestre** [comment]
Rejected
