### ISSUE TITLE
Drag & drop to "value description" field

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#233]
Allow drag&drop of file from Windows Explorer or Web Page to "value description" field and store path or address resp.

This saves time of the user and prevents from typing mistakes.

**Comment by msevestre** [comment]
How do you drag and drop a webpage? Copying the url is probably what user would do?

File Path would probably work. However this would be absolute path.

Suggestion would be to use the existing function to copy the Path on windows (starting win7)
SHIFT + Right Click => COPY AS PATH

**Comment by ju-rgen** [comment]
Drag&drop would be more elegant, but if the implementation requires more than a few hours, this (often unknown) short cut would be a sufficient alternative from my perspective.

Regarding the dragging of web pages: In my browser (Firefox) I can drag a page (the "page tab" to the favorites for example, so perhaps the URL is contained in the information passed in the drop event.
Now, after a testing drag&drop of web page to a text field in a windows application, unfortunately I have the impression, that there are no DragEventArgs available.

**Comment by msevestre** [comment]
>Drag&drop would be more elegant, but if the implementation requires more than a few hours, this (often unknown) short cut would be a sufficient alternative from my perspective.

yes absolutely more than a few hours. Values are displayed in different views etc.. so although the logic would have to be implemented once, the hooking over events etc. would have to be done in all views where a value can be entered, both in PKSim and MoBi.

Using Chrome, drag and drop of a page creates a new View so this would not work at all.

**Comment by msevestre** [comment]
Task will not be implemented
