### ISSUE TITLE
Replace message "A blackbox formula is still in use in entity..."

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#2333]
Sometimes this error is shown and it has zero informational value for the end user. This should be replaced by something more informative that would actually help the user to debug.

Proposals for the new message:

1. "The calculation method formula <FORMULA NAME> is not defined for the parameter name <PARAMETER NAME> located in the container <CONTAINER PATH>. Please use another formula type.  See https://dev.open-systems-pharmacology.org/pk-sim-database/db#black-box-formulas for more information."
2. "A formula, which should be replaced during simulation creation, was not replaced. These types of formulas are known as Black Box Formulas. Check parameter definitions for the following entity \<EntityPath>. See https://dev.open-systems-pharmacology.org/pk-sim-database/db#black-box-formulas for more information."

**Comment by PavelBal** [comment]
@Yuri05 @msevestre We could use some assistance here. I honestly have no idea what this message means.

**Comment by Yuri05** [comment]
Can you describe a use case where this error occurs?

**Comment by rwmcintosh** [comment]
We need reproducible steps to find the root cause why this happened. Ideally this message cannot happen

**Comment by PavelBal** [comment]
It has something to do with the black box formulas... But I don't know what. Can't you extract this from the code? :D

**Comment by Yuri05** [comment]
This happens e.g. when you manually assign a black box formula to a parameter which is not expected to be described by one.
(Which does not make any sense).
So the question remains: what exactly have you done for getting this error?

**Comment by Yuri05** [comment]
In fact, it's not directly possible in MoBi to **assign** a Black Box formula directly (because it does not make any sense).
But it's possible via some other actions. E.g. in the example below, I copied a parameter described by the black box formula in global molecule parameters of the spatial structure and pasted it again, renaming the new parameter to "**Nonsense**".
I kept the (black box) formula of **Nonsense**. 
Now when trying to create a simulation, the **Nonsense** parameter is added to every molecule and MoBi tries to replace its formula based on the cellular permeability method defined for this molecule (which obviously does not contain any formula for the parameter **Nonsense**).

The error message is telling you that the parameter **Nonsense** of the compound **Weak base** is still defined by a black box formula in the simulation, which means that the definition of this parameter in its building block is wrong
(the error message could be extended by something like "Check the definition of the parameter in the building block")

![grafik](https://github.com/user-attachments/assets/6946c582-ccaa-45db-afc5-95d7b8bf191e)

**Comment by rwmcintosh** [comment]
Is the terminology adequate? Maybe we should describe this more like 

"A formula, which should be replaced during simulation creation, was not replaced. These types of formulas are known as Black Box Formulas. Check parameter definitions for the following entity..." And include the entity path like before.

We need to trigger the user's memory of where the nonsense was introduced.

**Comment by PavelBal** [comment]
Maybe there is a clear misunderstanding of what the black box formulas are and how they work.

I would expect that the parameter "nonsense" will get the same formula as `P_bc_pls_factor`. So probably what I was trying to do was: use the same formula for calculation of, e.g., a partitioning, for a custom parameter. Is it not possible?

**Comment by Yuri05** [comment]
> Maybe there is a clear misunderstanding of what the black box formulas are and how they work.
> 
> I would expect that the parameter "nonsense" will get the same formula as `P_bc_pls_factor`. So probably what I was trying to do was: use the same formula for calculation of, e.g., a partitioning, for a custom parameter. Is it not possible?

no, it does not work like this.
Calculation methods overwrite the black box formula of a parameter, which is defined **by name and container criteria**.
So you can dynamically assign a formula to something like "_Parameter `P_cell_int_factor` in the molecule properties container of the neighborhood between Interstitial and Intracellular compartment_". If you somehow manage to create another parameter with the black box formula (per copy/paste or pkml load or whatsoever) with the combination of {Parameter name, Container tags} which is not a priori known to any of used the calculation methods - it will be ignored, and then you get the error message.

s. https://dev.open-systems-pharmacology.org/pk-sim-database/db#black-box-formulas and https://dev.open-systems-pharmacology.org/pk-sim-database/db#section-calculation-method-parameters

**Comment by PavelBal** [comment]
How about

"The calculation method formula <FORMULA NAME> is not defined for the parameter name <PARAMETER NAME> located in the container <CONTAINER PATH>. Please use another formula type, or extend the calculation method formula in AllCalculationMethods.pkml. See https://dev.open-systems-pharmacology.org/pk-sim-database/db#black-box-formulas for more information."

**Comment by Yuri05** [comment]
> How about
> 
> "The calculation method formula <FORMULA NAME> is not defined for the parameter name <PARAMETER NAME> located in the container <CONTAINER PATH>. Please use another formula type, or extend the calculation method formula in AllCalculationMethods.pkml. See https://dev.open-systems-pharmacology.org/pk-sim-database/db#black-box-formulas for more information."

I would rather go with Robs suggestion above. Users should never edit **AllCalculationMethods.pkml** or the PK-Sim database.

**Comment by rwmcintosh** [comment]
> > How about
> > "The calculation method formula  is not defined for the parameter name  located in the container . Please use another formula type, or extend the calculation method formula in AllCalculationMethods.pkml. See https://dev.open-systems-pharmacology.org/pk-sim-database/db#black-box-formulas for more information."
> 
> I would rather go with Robs suggestion above. Users should never edit **AllCalculationMethods.pkml** or the PK-Sim database.

Is this the decision then? I can change the text?

**Comment by PavelBal** [comment]
No not yet. Gathering user feedback.

**Comment by wilbertdew** [comment]
I would prefer option 2

**Comment by SoFiHo05** [comment]
I do not mind either option. But if option2 is selected maybe one still could provide the link for further info about black box formulas

**Comment by rwmcintosh** [comment]
We use option 2
