### ISSUE TITLE
“value origin mode” and “value description” fields in PK-Sim compound building block

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#234]
In PK-Sim should fields for “value origin mode” and “value description” be available also for all fields in Compound Building Block, e.g. for lipophilicity, solubility.

**Comment by msevestre** [comment]
How does the value description differs from the Alternative description? Should we remove alternative description alltogether? The purpose is the same and probably confusing otherwise.

What about Solubility alternatives which have more than one parameter? How should that work?

**Comment by msevestre** [comment]
We need more information to estimate. Especially how should the UI look like

**Comment by tobiasK2001** [comment]
Dear Micheal, please find a rough suggestion in the ppt discussed with Juergen. Generally it seems to me that this might be a chance reduce some inconsistancies in PK-Sim and to unify the look and feel of PK-sim and MoBi.
Especially in the cpd building block the data input is quite heterogeneous and the space could be probably used by the user to give more relevant infos in the value decription which should be always visible.
[Mock up value description.pptx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/1224483/Mock.up.value.description.pptx)

**Comment by msevestre** [comment]
ALso please address question. Not sure if this is in the ppt or not but it's easier to follow in one spot only
>Should we remove alternative description alltogether? The purpose is the same and probably confusing otherwise.

**Comment by tobiasK2001** [comment]
it is addressed in ppt. My favorite would be: remove alternative description from table view and make it available as mouse over-tooltip

**Comment by msevestre** [comment]
What is the alternative description compared to the value description? Do
we need alternatively description at all?

**Comment by tobiasK2001** [comment]
good question...Jürgen had the feeling that it is in some cases more specific and maybe helpful to understand the model...

**Comment by msevestre** [comment]
`some cases` and `maybe` sounds like a lot of uncertainty to me. :)

My suggestion would be to remove the description in the alternative completely. The value description should reflect everything that is needed

**Comment by msevestre** [comment]
@tobiasK2001 Looking at the powerpoint, I'd like to focus on the current entry here which is the value origin and description in compound window. The rest should be moved in separate issues please. More specifically

1. Can you please create  a new issue with your proposal for change in simulation (slide 4)
1. Can you please create a new issue with your proposal to reorganize the Enzyme View (slide 5)
1. Can you please create a new  issue to specify that favorites are missing in the compound building block. 

Now regarding `Value Origin Mode` and `Value Description` in the Compound window

- Fraction Unbound Binds To: Suggestion is to add an entry underneath with the Value Origin as a combo box and a field as Value Description is this correct?

- MolWeight and Compound Type PKA
You suggested "one additional column possible". That would mean that we would have one entry for each pKa values or for MolWeight and halogens etc.. Is this what you mean? 

Doesn't it make more sense to have one row instead (e.g. one common Value Origin Mode and Value description for all pKa and similar for MolWeight)

**Comment by tobiasK2001** [comment]
Done.

Fraction Unbound Binds To: Suggestion is to add an entry underneath with the Value Origin as a combo box and a field as Value Description is this correct?
-->Yes
Doesn't it make more sense to have one row instead (e.g. one common Value Origin Mode and Value description for all pKa and similar for MolWeight)
--> yes that might be more sensible. We thought that value description for Molweight might not be so important as it usually the same independent of the source.
This is different for PKA. But normally all PKA values (if there are more than one) come from the sam source

**Comment by msevestre** [comment]
Going to move this issue to PK-Sim as it is not related to OSPSuite.Core at all
