### ISSUE TITLE
Simulations comparison table: show values in same unit

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#2349]
Currently, differences in values may be presented in different units. This does not really make sense. It would be more informative to show them in the same unit.

![image](https://user-images.githubusercontent.com/25903040/65601544-8b85ab80-dfa2-11e9-9dbe-7fd9f50784c8.png)

**Comment by PavelBal** [comment]
Hmm, downloaded the above referenced project, compared the two simulations and still got the comparison in different units:

![image](https://github.com/user-attachments/assets/a4ec2fb8-d345-4fc9-96d3-e7812ba34397)

Or was MoBi not updated to the latest core?

**Comment by rwmcintosh** [comment]
Core note yet updated
