### ISSUE TITLE
Optional display of “value description” and “value origin mode” in comparison

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#235]
Allow selection of “Value Origin Mode” and “Value Description” fields in comparison view in order to see the origins of different values directly.

**Comment by msevestre** [comment]
is that flag "Only compare properties relevant to simulation results" sufficient? Or do you want two new flags ?
Also right now the difference would be shown as new lines in the difference table (one line for value, value description and value origin mode)

**Comment by msevestre** [comment]
Alternatively we could add two new columns to the comparison? THey would only be used for parameters and empty otherwise. Not sure if this is a good idea

**Comment by ju-rgen** [comment]
If  all changes in values, value descriptions, value origin mode are displayed and the rows for those changes at the same parameter are displayed one above the other, it seems sufficient.
But in SBSuite 6.3.2 I found still problems in comparison after changing value or value description in a simulation and missing entries in comparison, see screenshot. 
![grafik](https://user-images.githubusercontent.com/25579536/28863178-3728dc82-7768-11e7-9231-4f6c6807dc94.png)

**Comment by msevestre** [comment]
I don;t think ValueDescription is part of the comparison at the moment
Maybe your settings are only comparing values? if not, please create an issue in MoBi so that we can track that bug

**Comment by msevestre** [comment]
Also question here to be answered
>is that flag "Only compare properties relevant to simulation results" sufficient? Or do you want two new flags ?

@Yuri05 Any opinion?

**Comment by Yuri05** [comment]
I think if we implement differences in value description/mode in rows (as discussed #236), we will need 1 additional flag for both (with the default value 1)

**Comment by msevestre** [comment]
1? do you mean true?

**Comment by Yuri05** [comment]
yes :smile:

**Comment by msevestre** [comment]
@Yuri05 
So to summarize this feature:
We do not compare the value origin. Instead, for quantity showing up in comparison, we also show the value origin as a row if the flag is set to true. Correct?

And the default value for this flag is SHOW
