### ISSUE TITLE
In comparison display value and "value description" when overriding formula values

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#236]
In case of overriding formula values by manual values (Parameter Start Values) display value and value description. 
(currently partly no differences are shown, partly only text “new value”.

**Comment by msevestre** [comment]
Would it be enough to show the Value description difference as a new entry in the difference table? I am not sure how it should look like otherwise. Please update this requirement so that we can estimate it.

**Comment by msevestre** [comment]
@Yuri05 Maybe you can also add your inputs here. Thanks

**Comment by Yuri05** [comment]
One option would be just to display the difference in **value description** as additional entry
(can we make sure, that it's always displayed e.g. _after_ the entry for the difference in **value**?)

Another option would be to introduce the difference in value description as additional columns (_old value descr_, _new value descr_)-but I think it would overcomplicate both implementation and display of comparison

**Comment by msevestre** [comment]
You would also need new columns for value modes (old and new)
In my opinion, new raw would be much easier indeed

**Comment by msevestre** [comment]
ok rows will be implemented

**Comment by msevestre** [comment]
@Yuri05 Can you explain how it differs from #235 ?

**Comment by msevestre** [comment]
@Yuri05 No idea what needs to be implemented here . Looks a lot like #235. Wording is confusing at best. Closing. Please reopen if required
