### ISSUE TITLE
The order of Favorites should be editable.

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#237]
Favorites should be used to provide an overview about the parameters of interest, which do mostly change during the project.
In a list of 10-30 parameters the order in this list is important, e.g. to group physico-chemical parameters, organism parameters, etc.

Currently each new favorite is added at the bottom of the list, so the order of the list can not be maintained.

**Comment by msevestre** [comment]
* Project conversion is required here. Right now favorites are simply saved as a list of string. We need to add more structure to that. 
* Conversion will be required for PK-Sim and MoBi
* We need to add an index to the favorite
* adjust serialization
* Modify the UI (Adding arrows up and down like in Pop Analyzes or Drag and Drop like in Curve Chart or both)

**Comment by msevestre** [comment]
Specific tasks for MoBi and PK-Sim created
