### ISSUE TITLE
Allow attachments of general files to a Journal Page

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#239]
Allow attachments of other files like Excel files, pdf Reports etc. to a Journal page as Related Items.

This supports using the Working Journal as a comprehensive "single source" of model documentation.

**Comment by msevestre** [comment]
Extension needs to be saved somewhat explicitly. Maybe some more meta data on the file such as file name, original location.
Probably update to underlying journal DB not required but this needs to be checked

**Comment by msevestre** [comment]
The added file will need to be loaded in memory in order to be converted to byte. Should we define an upper limit on file size?

**Comment by ju-rgen** [comment]
An upper limit of file size I find reasonable, e.g. 50 MB. 
Would it create much effort, if this could be changed in the settings? 
It would be good, if for file sizes larger than 5MB a confirmation dialogue opens with information about the size of the file.

**Comment by tobiasK2001** [comment]
hmm. normally my excel files are about 50 KB. However in some extreme cases they are 30  MB. I also have some CSV with POP-sim results with about 109 MB. PDF-reports / Paper are normally below 5 MB. 
So I would suggest an upper limit of 150 MB and ask the user for files larger 5 MB if he really wants to keep  it that way ;-)

**Comment by msevestre** [comment]
Upper file limit will be set to 50MB . After various tests, I managed to crash the app with bigger files
