### ISSUE TITLE
When attaching a Parameter Identification to a Journal Page, the used simulations should be stored automatically

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#240]
When attaching a Parameter Identification as Related Item to a Journal Page the used simulations should be stored as independent items. So later the Parameter Identification can be used with other version of the simulations AND the original Parameter Identification can be redone.

**Comment by msevestre** [comment]
see https://github.com/Open-Systems-Pharmacology/MoBi/issues/157

**Comment by msevestre** [comment]
Since items will be saved independently from each other, restoring means that the user will need to restore all required items (this won't be done automatically)
Also all observed data should probably be added as related item as well.
I imagine that this feature should also be available for sensitivity analyses

**Comment by msevestre** [comment]
Label risky because restore might not work at all with the current concept since we are resetting id's when loading a related item back into a project. a PI however references Simulation (internally by ids) so this might require a lot of work to get it right

**Comment by msevestre** [comment]
Probably restore in an empty project could work (or a project where a simulation with the same id as a saved simulation does not exist)

**Comment by msevestre** [comment]
@Yuri05 In my opinion this does not really belongs to the MBD package. I think the implementation could be quite tricky to really complicated. I am not sure how you want to proceed with this task. 
We could invest up to 2d and see if we are making progress, at least in some simple use cases (reimporting in empty project etc..)

**Comment by Yuri05** [comment]
>We could invest up to 2d and see if we are making progress...

:+1:
