### ISSUE TITLE
Allow navigation to next and previous Journal Page from the Journal Page View

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#242]
The user should be able to switch from page to page within the "working journal view" itself instead of doing this only from Journal Page List in the main application window.

**Comment by msevestre** [comment]
@ju-rgen @Yuri05 
This is how it's going to look: Two buttons at the bottom right of the screen. 
Let me know if I should adjust it (Move buttons at the top, add text to the buttons etc)
![image](https://user-images.githubusercontent.com/1041237/36215259-9dfefa08-1179-11e8-81d9-8c881fb93bf9.png)
