### ISSUE TITLE
Enable the concurrent display of multiple Journal pages

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#243]
Sometimes the user wants to compare the content of Journal Pages - or even copying content from one to another. This is currently difficult.

**Comment by msevestre** [comment]
@ju-rgen This is not in the original work package documentation so I am assigning it a prio low. Let me know if this is not accurate

**Comment by ju-rgen** [comment]
That's right. The topic was mentioned from colleagues after finishing the original work package documentation. So providing this feature should depend on the required effort.

**Comment by msevestre** [comment]
Estimated effort 2d with serious workflow change. Suggestion would be to open the working journal in a new instance of MoBi or PKSim instead

**Comment by msevestre** [comment]
@Yuri05 Running out of time overall because of moving target with ValueOrigin implementation. Suggestion would be to skip this feature as this can be achieved easily by opening two instances of PKSim or MoBi. Thought?

**Comment by msevestre** [comment]
This won't be implemented
