### ISSUE TITLE
add dimension: Compliance (Area)

### ISSUE THREAD

**Issue by dzianism** [Open-Systems-Pharmacology/OSPSuite.Core#244]
Could additional dimension ( Compliance (Area) ) be added to OSPSuite.Dimensions.xml in the next release of OSP suit?

Compliance (Area) is required to specify length normalized blood vessel compliance. 

<Dimension name="Compliance (Area)" baseUnit="dm²/(kg/(dm*min²))" defaultUnit="cm²/mmHg">
      <BaseRepresentation lengthExponent="3" massExponent="-1" timeExponent="2" electricCurrentExponent="0" temperatureExponent="0" amountExponent="0" luminousIntensityExponent="0" />
      <Units>
        <Unit name="cm²/mmHg" factor="1E-2/(133.3223684*60*60)/100" />
        <Unit name="cm²/Pa" factor="1E-2/(60*60)/100" />
        <Unit name="cm²/(N/m²)" factor="1E-2/(60*60)/100" />
        <Unit name="cm²/(dyn/cm²)" factor="1E-1/(60*60)/100" />
        <Unit name="cm²/(kg/(m*s²))" factor="1E-2/(60*60)/100" />
        <Unit name="dm²/(kg/(dm*min²))" factor="1" visible="0" />
      </Units>
  </Dimension>

**Comment by msevestre** [comment]
@dzianism Could you let us know the units that should be available for this dimension?
Check this [file](https://github.com/Open-Systems-Pharmacology/OSPSuite.Dimensions/blob/master/OSPSuite.Dimensions.xml)

Ideally, you could even submit a PR with the proposed changed. We could review it and merge it in the suite for the upcoming release :)

**Comment by msevestre** [comment]
@dzianism could you get back to us on that? We will not be able to implement that feature otherwise. Thanks

**Comment by dzianism** [comment]
@msevestre I have submitted a pool request

**Comment by msevestre** [comment]
This has been implemented already. Thanks

**Comment by dzianism** [comment]
Excellent!
