### ISSUE TITLE
proposal for change of value description and value origin in Simulation view 

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/OSPSuite.Core#245]
As discussed in [https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/234#issuecomment-322488101](url)
![grafik](https://user-images.githubusercontent.com/25585248/29351238-3ed5dd2c-8262-11e7-8cca-15106f8b0094.png)

**Comment by msevestre** [comment]
This is a MoBi feature. Please defined this feature in the expected repository. Thanks
https://github.com/Open-Systems-Pharmacology/MoBi/issues

**Comment by msevestre** [comment]
Rejected: @tobiasK2001 needs to create this issue at the correct location.
