### ISSUE TITLE
Proposal for unified look for PK-sim MobiIndividual/ expression/enzymes

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/OSPSuite.Core#246]
As discussed in [https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/234#issuecomment-322488101](url)
![grafik](https://user-images.githubusercontent.com/25585248/29351361-b379218e-8262-11e7-956f-85dd05279da2.png)

**Comment by msevestre** [comment]
Closing as this should have been created in PK-Sim
See https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/554

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/35743550-ee48e28e-080b-11e8-9e68-c777f2fe3a9c.png)
