### ISSUE TITLE
favorite check boxes  are missing in the compound building block /unified look 

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/OSPSuite.Core#247]
As discussed in [https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/246](url)
![grafik](https://user-images.githubusercontent.com/25585248/29351517-53a7d538-8263-11e7-8b40-c34689a08075.png)

**Comment by msevestre** [comment]
This seems to be a PKSim issue and not a core issue. 
However Favorites are found using their path. The path in compound is different than in simulation so this is not feasible without extensive work. Once 7.3 is defined, the concept of parameter changed by the user will be available and this feature might be obsolete. Please reopen at the correct location if required

**Comment by msevestre** [comment]
rejected: because not at the right location and probably not requried
