### ISSUE TITLE
Change coverage service to codecov.io

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/OSPSuite.Core#27]

**Comment by msevestre** [comment]
Let's make sure that the filter passed to the cover task in not a bit long string. Instead one item per line so that we can comment on why sthg is filtered in or out

**Comment by msevestre** [comment]
Nope does not work yet
https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-core-h23vr
