### ISSUE TITLE
Enable Sum Formula tag "within container"

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#270]
For calculating sum formulas it would be handy to have an option to restrict summation to the current container where the sum parameter is located. So, in addition to have the condition: "tagged with <container name>" where the container name is explicitly given, it would be "tagged with local container".

This should select container parameters as well as local molecule and reaction parameters that are present in the local container.

Implementing this feature would improve and simplify maintenance of the blood coagulation simulator, probably also other things.

**Comment by msevestre** [comment]
@Yuri05 Is it what we have already with tthe "In container and Not In container" ?

**Comment by Yuri05** [comment]
I think this "within my parent container" feature is still not implemented.
@UlrichSi Please comment

**Comment by UlrichSi** [comment]
Correct - we can only explicitly select a container name or tag. "Parent Container" would be a helpful addition.

**Comment by Yuri05** [comment]
closing in favor of https://github.com/Open-Systems-Pharmacology/MoBi/issues/837
