### ISSUE TITLE
PI: random start values are not generated

### ISSUE THREAD

**Issue by dzianism** [Open-Systems-Pharmacology/OSPSuite.Core#326]
Parameter Identification -> Configuration -> Options -> Multiple optimization (Randomize start values) 

Problem: Initial values are not randomized
Version: PK-Sim 7.2.1. Standalone version
![snap](https://user-images.githubusercontent.com/27948704/35321870-25d2f22c-00e0-11e8-8319-a794099d1ece.png)

**Comment by Yuri05** [comment]
duplicates [PK-Sim/#520](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/520)

**Comment by msevestre** [comment]
Going to reopen because it needs to be fixed in core. This is the right place

**Comment by msevestre** [comment]
@dzianism I think they are generated but not displayed properly. Can you confirm?

**Comment by dzianism** [comment]
@msevestre  I run PI with Levenberg-Marquardt algorithm with multi start option and identified parameters landed far apart in the parameter space, so you are probably right.
