### ISSUE TITLE
Importing the attached data set does not set the compound name

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#361]
Steps to reproduce

1. Create PKSim Project and defined compound C1 
1. Go on the C1 node in tree view, right click => Add Observed Data
1. Select the file data.xls
1. Group by Id Column
![image](https://user-images.githubusercontent.com/1041237/36605171-f4677256-188d-11e8-8128-07140ebc5b24.png)

1. Import All
1. Notice that the Molecule Name is not set. That would be acceptable if I could not click ok. But I can set all other values and click ok resulting in MW not being set! This creates serious bug in PK-Sim down the line
![image](https://user-images.githubusercontent.com/1041237/36605187-0153c4e2-188e-11e8-8c6a-e16653e1ff6f.png)

[Data.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/1752362/Data.xlsx)

**Comment by msevestre** [comment]
This is not fixed. Using the same data set and clicking on Apply To all => The second sheet has an empty molecule again

**Comment by msevestre** [comment]
Even if I set the value to  my compound name on the first sheet, second sheet shows BS

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/36852298-50c26a9c-1d39-11e8-9287-c1aa0d745142.png)

![image](https://user-images.githubusercontent.com/1041237/36852312-56a6e6a4-1d39-11e8-96d5-31aa979bbfc7.png)

Even worth: When setting C1 on sheet 2 and going to sheet 1 and clicking on Apply To all, it resets the value to empty

**Comment by rwmcintosh** [comment]
Should Molecule be exempt from this Apply to All? The individual button is not enabled

**Comment by msevestre** [comment]
I don't think so. Why would it be different? Especially if this can be set by hand, you don't want to have to do it for all other entries

**Comment by rwmcintosh** [comment]
But why is the individual button disabled?

**Comment by msevestre** [comment]
@rwmcintosh no idea. Where does this come from?

**Comment by rwmcintosh** [comment]
@msevestre the code to disable the button is like this

```
button.Enabled = !col.IsColumnUsedForGrouping;
```

**Comment by msevestre** [comment]
in my case the column is not used for grouping. This flag is clearly not set properly then

**Comment by rwmcintosh** [comment]
I think I have a fix for this default value problem, but the grouping is separate I propose. Mostly because I don't see the need to delay putting this default value fix in.

Thoughts?

**Comment by msevestre** [comment]
forget about the grouping. This won't be fixed until we rewrite the tool
