### ISSUE TITLE
Open "other" related items by doubleclick

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#408]
If a related item of type "File" is added to a working journal: enable opening it in the default application by double click.

**Comment by msevestre** [comment]
I think this is not a good idea. Where should we download the file?
My suggestion would be to try to open the file once downloaded by the user, but location should be specified by the user

**Comment by Yuri05** [comment]
>My suggestion would be to try to open the file once downloaded by the user, but location should be specified by the user

Think that's OK. The question would be what should be the default location here: last used or e.g. the same folder where working journal is stored.

**Comment by msevestre** [comment]
@Yuri05 IS anyone using the WJ ? do we forget about this feature?

**Comment by Yuri05** [comment]
>IS anyone using the WJ ?

I have no idea.

**Comment by PavelBal** [comment]
Maybe create a poll (what would be the best way to do this on  GitHub) to assess if WJ is actually used by users?
