### ISSUE TITLE
Changing the unit of observed data column (EditObservedData) should also change unit of LLOQ

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#415]
Otherwise stuff get's completely messed up

**Comment by msevestre** [comment]
@Yuri05 Will we be allowed to change data once in PKSim or MoBi. I forgot what we said

**Comment by Yuri05** [comment]
For **referenced** obsdata - no for sure. 
For **imported** obsdata - probably yes (with prompt) - however still to be discussed.

**Comment by PavelBal** [comment]
I would vote for enabling editing imported data. And with the re-load feature it will be easy to revert changes.

**Comment by Yuri05** [comment]
obsolete. closing
