### ISSUE TITLE
Error: Strange behaviour of Excel-Import

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#442]
Worked with MoBi 7.3
[Dunn_2011_Dasatinib Sensitizes KRAS TEST New1.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/2205640/Dunn_2011_Dasatinib.Sensitizes.KRAS.TEST.New1.xlsx)
[Dunn_2011_Dasatinib Sensitizes KRAS TEST New2.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/2205641/Dunn_2011_Dasatinib.Sensitizes.KRAS.TEST.New2.xlsx)

Import of New1.xlsx (no data in first column results in correct selection of header row, recognition of Dimensions/units but unfortunately moved by one column (e.g. 2nd column is time,but recognized as measurement and so on.
![grafik](https://user-images.githubusercontent.com/25579536/42879959-bd7cd520-8a92-11e8-9aa8-2d27827263d5.png)

Import of New2.xlsx (same as New1, but with data in first column) results in wrong selection of header row and no recognition of units....
![grafik](https://user-images.githubusercontent.com/25579536/42879964-c2005a86-8a92-11e8-82d3-a6e4a07e83c5.png)

**Comment by PavelBal** [comment]
New1 results in an error:
![image](https://github.com/user-attachments/assets/e07db786-21fc-42d0-9359-9ee5c90b010f)

There are indeed duplicated columns, which is not a valid structure. So, I think the behavior is correct. When the first row (with duplicated columns) is removed, the import works.

![image](https://github.com/user-attachments/assets/ff7a1de7-9194-4a70-a3f4-255d0cfcfa74)


Please re-open if you think the behavior is incorrect.
