### ISSUE TITLE
Icons for Rabbit, Mouse and Beagle are outdated

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#46]
The Green and Red icons are using and older version of the design!

**Comment by msevestre** [comment]
I have asked the designer to send us the updated version

**Comment by msevestre** [comment]
![snap5](https://cloud.githubusercontent.com/assets/1041237/25017301/3c11f972-2051-11e7-89d0-fc0460178113.png)

**Comment by msevestre** [comment]
FYI @Yuri05

**Comment by Yuri05** [comment]
Rabbit icon is outdated also for "normal"

**Comment by msevestre** [comment]
This is fixed in core and will be available in PKSim and MoBi after core update
