### ISSUE TITLE
Fixed parameters flag is not included in the PI export

### ISSUE THREAD

**Issue by hdiedam** [Open-Systems-Pharmacology/OSPSuite.Core#485]
The information on fixed parameters introduced with https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/169 is not included in the exported xml and consequently, it is missing in the Matlab struct generated by loading the PI.

**Comment by msevestre** [comment]
This is fixed in core. However support for this new parameter should be added to the matlab script (parameter isFixed)
