### ISSUE TITLE
PI: allow multiple mapping of observed data sets

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#494]
Currently an observed data set can be maped to max. 1 simulated curve.
Trying to map it to a second curve results in the error message below.

However there are plenty of situations where this kind of multimapping is required.
![grafik](https://user-images.githubusercontent.com/25061876/53019243-9bf60680-3454-11e9-86da-3a40c38f4fb9.png)

@sfrechen @twendl FYI

**Comment by msevestre** [comment]
@Yuri05 It's implemented. Obviously some stuff now is not as obvious as we think it was
How should we name the Tabs? At the moment the name of the tab is the name of the observer .. but now it's not unique

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/53602638-67352e00-3b7d-11e9-8dc4-2c0292077cce.png)

**Comment by msevestre** [comment]
We could add the name of the output but that would be very long 
Suggestion
We add a row # in the table above 1, 2, 3 and display the number in the header. For example  1- Midazolam. Of course we need to update the id when we delete but that should not be too bad

**Comment by msevestre** [comment]
I'll wait before I implement to get some feedback

**Comment by msevestre** [comment]
Actually I don't think this is a good idea. There is too much synchronization to be done
