### ISSUE TITLE
Passing LLOQ value for numerical columns

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#495]
Currently LLOQ values can be passed only by coding them as "< xx.xxx" values in a column.
The disadvantage of this is, that the column then needs to be a character column instead a numerical column, what makes data preparation more complicated. E.g. handling of decimal separators needs to be performed "manually" by replacing comma or point characters. For usage of such columns in calculations parsing operations must be used. Visualization also more difficult.

As these columns are numerical by nature, they should be stored in numerical datatype instead of string/character.

The LLOQ value should be able to pass as column metadata like unit for example by certain coding in the header (e.g. _xx.xxx_   similar to [mg/l]  )

If all values smaller than this LLOQ value should be interpreted as LLOQ or just those values with the value of LLOQ/2 or -LLOQ should be clarified with user experts.

**Comment by PavelBal** [comment]
Yes!

**Comment by msevestre** [comment]
@ju-rgen I don't undersand this requirement

>As these columns are numerical by nature, they should be stored in numerical datatype instead of string/character.

Do you mean in Excel?
As far as I know (and I have no experience in Excel), it's possible to have a numeric column and specific fields being string/char. For example 
![image](https://user-images.githubusercontent.com/1041237/53246761-8dd7fe00-367f-11e9-9b8c-ca12649d6d9a.png)

Isn't it what you need ?

**Comment by PavelBal** [comment]
@msevestre when processing such data sets in e.g. Matlab in R, the cells with a '<' a treated as strings and not numericals.

**Comment by msevestre** [comment]
Ok but exporting those sets from PKSim or MoBi as CSV or Excel should be good then right?
The issue is only if you use the raw data without even using it in PKSim or MoBi correct?

**Comment by PavelBal** [comment]
Yes. And, etm, PK-Sim forces one to use "<xxx" for LLOQ.

**Comment by msevestre** [comment]
I don't understand your last comment?

**Comment by PavelBal** [comment]
Because of PK-Sim, the raw data have to be in this (unfortunate) format. If PK-Sim could understand LLOQ e.g. by metadata, we could format the raw data the way it can be understood by Matlab/R.

**Comment by msevestre** [comment]
I understand. However you can export the data from PKSim and MoBi back to csv and excel and it should have the actual LLOQ Value. So a workaround is easy and straightforward. Or am I missing the point ?

**Comment by PavelBal** [comment]
If, for whatever reason, you are generating hundreds of datasets and only a fraction of them will be imported to PK-Sim for actual work, you still have to load them all (one by one!!!) and save as csv.

Imagine, the decision whether to use the dataset is based on some assessment in R... So, before you can use the power of a scripting language, you first have to load every file into PK-Sim and store in back to scv, just because you have to format them that way ;)

**Comment by msevestre** [comment]
in that case it's very easy to script out something that would ensure that your column has the right type. Probably a few lines of R even for a non R programmer like me

**Comment by msevestre** [comment]
I am not opposed to the idea. I am just trying to understand why this is such a big deal that prevent people from moving forward.

**Comment by ju-rgen** [comment]
Of course it is possible to build work arounds in R to temporary change column format between numeric and string and vice versa. (I do not really understand the remarks on export from PK-Sim - in my situation there are plenty of data to be preprocessed in R and then to be imported(!) into PK-Sim).

My request is just to get rid of these work arounds, because actually the column values are numeric and so it should not be necessary just for importing one column attribute into PK-Sim to change the column datatype to string.

**Comment by Yuri05** [comment]
I think the issue is obsolete with the new observed data import where LLOQ can be a separate (numeric) column.
If not: please reopen
