### ISSUE TITLE
Enable Sum Formula tag "within container" 

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/OSPSuite.Core#534]
For calculating sum formulas it would be handy to have an option to restrict summation to the current container where the sum parameter is located. So, in addition to have the condition: "tagged with <container name>" where the container name is explicitly given, it would be "tagged with local container".

This should select container parameters as well as local molecule and reaction parameters that are present in the local container.

Implementing this feature would improve and simplify maintenance of the blood coagulation simulator, probably also other things. This is my most favored request since there is no workaround, and manual maintenance of the formulas is error-prone.

**Comment by UlrichSi** [comment]
Tagged with **_local_** container will not work, but tagged with **_named_** container does and will hopefully do the job.

**Comment by msevestre** [comment]
>Tagged with local container will not work, but tagged with named container does and will hopefully do the job.

I do not understand what you mean with 'local'

**Comment by UlrichSi** [comment]
"Local" container means the container where the parameter that is calculated by the sum formula is in. So, like a local reference. It would require just one formula that, for example, sums up the metabolites in each organ in a PK-Sim exported model. - With the currently named container tag, one would need separate formulas for all containers of interest to achieve that task.

**Comment by msevestre** [comment]
You can already use local reference for example 
..\V would be relative to the Parameter with the local formula already 

THat's why you can define object reference for sum formula. They are relative to the instance of the parameter / observer using the formula

**Comment by UlrichSi** [comment]
@msevestre That's not what I meant; selecting a container in the tag window will only accept a named container and not a generic local reference like you suggested above. But let's see how it works out. In my applications, I only need to set up sum formulas in a few selected containers, so I can live with the current implementation.

**Comment by UlrichSi** [comment]
@msevestre Since you mentioned the object reference feature (cf #539), the implementation is lacking the usual reference tree. Is that on purpose?

**Comment by msevestre** [comment]
> That's not what I meant; selecting a container in the tag window will only accept a named container and not a generic local reference like you suggested above. But let's see how it works out. In my applications, I only need to set up sum formulas in a few selected containers, so I can live with the current implementation.

Ok if you could give me an example, of what you are trying to achieve, we could see if it's possible or not.

And yes, no reference tree at the moment. Since the reference are created based on where the Parameter instance will be created, it is very hard to know what to refer to. In general, the reference should either be ABSOLUTE (fu) or in same container ish. 

If we really feel that we need a tree for this use case, we'll hvae to create a separate issue

**Comment by UlrichSi** [comment]
Think of the following as an example:
1. Use the MoBi example model "Diclofenac"
2. Tag the molecules "Diclofenac" and its metabolite "4'-Hydroxy-Diclofenac" with the label "SumUp".
3. In the Parameters section of "Diclofenac", add a _local_ parameter "Parent_Metabolite".
4. For this parameter, define a sum formula. Select "SumUp" as one tag condition. As the second condition, it should be possible to select "Current container", meaning the container where "Diclofenac" is located. This should sum up the parent drug and its metabolite in the local parameter separately for each container.

With only two compounds, it is of course easy to manually write sum formula, but imagine a model with a growing number of metabolites in each update.

Another application is the occupation of binding sites by different molecules, summed up separately in each physical container.
