### ISSUE TITLE
Sum formula iteration parameter reference for relative paths wrongly chosen

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/OSPSuite.Core#573]
Testing MoBi Beta 8.0.6, issue #539:

When entering a sum formula with additional dependent parameters (see example project attached to #572 ), the reference point for relative paths is set to the place where the target parameter computed by the sum formula is located.

In case of the upgraded ManualModel, these are the containers Vial1 and Vial2. A discussion with @Yuri05 resulted that the expected behavior would be that the location of the summed parameters, in this case the Molecules B and C within Vial1 or Vial2, should be the reference point, thus allowing to reference local parameters of those molecules. 

Currently, one cannot access such parameter, which would be quite useful to to.

**Comment by msevestre** [comment]
@UlrichSi As discussed. This is the correct behaviour. however description needs to be updated.  In such cases, in order to use  reference parameters relative to the iterated parameter, a `_#i` needs to be added to the alias
