### ISSUE TITLE
Extension of formula references concepts

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#603]
We have a lot of de-facto duplicated formulas in our models just due to the fact that we cannot reference neighbourhoods in a generic way like containers.
Having constructs like `PARENT|NEIGHBOURHOOD_TO.Interstitial` and some more would help.

Another problem is definition of calculation methods formulas for newly added organs in MoBi.
At the moment the problem (or at least one of the problems) is: parameters defined in the molecule properties of the Neighborhood `Organ|Interstitial<=>Organ|Intracellular` refer to other parameters of the same molecule defined in the molecule properties of the neighborhood `Organ|Plasma<=>Organ|Interstitial` (same organ!).

Thus if we find a good way to refer something like `SameOrgan|Plasma<=>SameOrgan|Interstitial / MoleculeProperties` - we could define help parameters in a generic way, which would add them to a tumor automagically.

One difficulty here: somehow full paths (or parts of the full parts) must be then integrated into the description of NEIGHBOURHOOD_TO.

E.g. the following example: 
* parameter `P1 `is located under `Container1|Plasma`
* parameter `P2 `is located in the neighbourhood between `Container1|Plasma` and `Container 4|Container 3|Plasma`
* `P1 `depends on `P2 `
![grafik](https://user-images.githubusercontent.com/25061876/64254645-19c8bd80-cf20-11e9-980b-216823ac4327.png)

In such a case `PARENT|NEIGHBOURHOOD_TO.Plasma` would not be sufficient. Instead, something like `PARENT|NEIGHBOURHOOD_TO.Container 4.Container 3.Plasma` should be used.

How should we deal with this?
 * Alternative 1: NEIGHBOURHOOD_TO keyword cann be followed only by a simple container name (e.g. `PARENT|NEIGHBOURHOOD_TO.Plasma`). 
   * Keyword-Resolver must then check if such a neighbourhood is unique.
   * If yes: reference can be resolved
   * If no (like in example above): exception
   * Examples like above must be handled as we do it now: using the name of the neighbourhoud
* Alternative 2: NEIGHBOURHOOD_TO keyword cann be followed by a sequence of container names (e.g. `PARENT|NEIGHBOURHOOD_TO.Container 4.Container 3.Plasma` or `PARENT|NEIGHBOURHOOD_TO.Container 4|Container 3|Plasma`)
* Other alternatives?

**Comment by Yuri05** [comment]
@ulrichsi @twendl @lkuepfer @Christoph27 @AndreDlm FYI

**Comment by msevestre** [comment]
@Yuri05 I don't understand this. Let's have a chat

**Comment by PavelBal** [comment]
> Alternative 2: NEIGHBOURHOOD_TO keyword cann be followed by a sequence of container names (e.g. PARENT|NEIGHBOURHOOD_TO.Container 4.Container 3.Plasma or PARENT|NEIGHBOURHOOD_TO.Container 4|Container 3|Plasma)

If I understand correctly: it could be possible to reference somethign like `PARENT|NEIGHBORHOOD_TO.Organism|Liver|Periportal|Plasma|ParXXX`. I like it.

**Comment by Yuri05** [comment]
>If I understand correctly: it could be possible to reference somethign like...

Yes. However we must find a good way to represent such references (e.g. `PARENT|NEIGHBORHOOD_TO.Organism|Liver|Periportal|Plasma|ParXXX` might be ambiguous)

**Comment by msevestre** [comment]
>PARENT|NEIGHBORHOOD_TO.Organism|Liver|Periportal|Plasma|ParXXX might be ambiguous

How can this be ambiguous? there can only be one neighborhood with the same source and target no?

**Comment by Yuri05** [comment]
>there can only be one neighborhood with the same source and target no?

Yes, but still.
E.g. in the following situation `Container1|NEIGHBORHOOD_TO.Container2|Container3|P1` is ambiguous. The situation is extremely unlikely, and we could just throw an exception in such a case.
(thus if there are >1 nbhoods satisfying the path)
![grafik](https://user-images.githubusercontent.com/25061876/74037980-adb31f80-49bf-11ea-8718-6993ef5aeea8.png)

**Comment by msevestre** [comment]
I don't understand.
Container1 only has one neibghborhood to Container2|Container

Maybe I do not understand the nomemclature. One container can only have one neighborhood to another container

**Comment by Yuri05** [comment]
(My example was wrong, have just fixed it)
It's not clear where there "Neighborhood_To" part of the path ends. 
E.g. the example above could be interpreted as either
* take the Nbhood between `Container1 `and `Container `2, then in this nbhood look for `Container3|P1` or
* take the Nbhood between `Container1 `and `Container2|Container3`, then in this Nbhood look for `P1`

**Comment by msevestre** [comment]
Ok. We should have an end tag then if we want to support this
In my mind, this was always `take the Nbhood between Container1 and Container2|Container3`

so something like 

Container1|NEIGHBORHOOD_TO.Container2.NEIGHBORHOOD_END|Container3|P1

**Comment by Yuri05** [comment]
yes, maybe something like this

**Comment by Yuri05** [comment]
`..|Plasma|<N_START>..|Interstitial<N_END>|SA_pls_int`

`..|Plasma|<NBH>..|Interstitial<NBH>|SA_pls_int`

**Comment by Yuri05** [comment]
K_cell_pls=f(K_water_cell): with path 
`Neighborhoods|ColonDescendens_int_ColonDescendens_cell|MOLECULE|Partition coefficient (intracellular/water)`
Location: Intracellular/MOLECULE

`..|..|<NBH>..|..|..|Interstitial<NBH>|MOLECULE|Partition coefficient (intracellular/water)`

**Comment by msevestre** [comment]
Looking at this
`..|..|<NBH>..|..|..|Interstitial<NBH>|MOLECULE|Partition coefficient (intracellular/water)`

Should it be 
`..|..|<NBH>|..|..|..|Interstitial|<NBH>|MOLECULE|Partition coefficient (intracellular/water)`

e.g.here the keywords are separate entry of the path? Or is it better if not?

**Comment by msevestre** [comment]
I am going to go for now with the original version and we can think about it

**Comment by Yuri05** [comment]
Have to think about it.
From the parsing perspective it's probably easier indeed to have the 2nd option (`|<NBH>|..|..|..|Interstitial|<NBH>|`). 
Apart from this, I don't see any good arguments right now, why option 1 or option 2 would be better.

**Comment by Yuri05** [comment]
Well, I think from the PK-Sim DB view the second option would be better as well.
Now we having each path entry separately, so we would have `<NBH>` as one of the entries.
With the original proposal we would suddenly have `<NBH>..` and `Interstitial<NBH>` and all other possible combinations as DB-entries, which does not really make sense.
So yes, option 2 for me now :)

**Comment by msevestre** [comment]
ok option 2. much easier to parse indeed :)

**Comment by PavelBal** [comment]
@msevestre @Yuri05 How is it implemented now? Do we have some kind of documentation for this?

**Comment by PavelBal** [comment]
@msevestre Ping :)

**Comment by msevestre** [comment]
All right here is how it's working
THE KEYWORD IS `<NBH>`

The goal it to be able to find TWO containers and specify that we want to reference the neighborhood between those two containers

Syntax is

`NEIGHBORHOOD_OATH = PATH_TO_CONTAINER_1|<NBH>|PATH_TO_CONTAINER_2|<NBH>`

### Example
As a parameter in Liver Cell, say, `P`, I want to reference the path of the parameter `K` in the neighborhood between `Liver Cell` and  `Liver Plasma`

From P point of view
```
Path to Liver Cell is .. (Parent)
Path to Liver Plasma is ..|..|Plasma
```

Path to neighborhood from P point of view will therefor be

```
..|<NBH>|..|..|Plasma<NBH>
```

Now path to parameter K in the neighborhood will be
```
..|<NBH>|..|..|Plasma<NBH>|K
```


@PavelBal Let me know if this helps

**Comment by PavelBal** [comment]
Oh yes: https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2078
