### ISSUE TITLE
Reusable importer configuration

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#616]
Observed data import process must be splitted into 2 stages:
1. Creation of an Import-Configuration
2. Import of observed data from one or more data sources based on a given import configuration.

Use cases based on this scenario: 
* Update of previously imported observed data from another data source (#785)
* Import further data files using existing import configuration ( #622)
* Don't keep observed data within PK-Sim/MoBi projects.
  * Only data sources and corresponding import configurations are saved within projects
  * When a project is opened: observed data is loaded on the fly

**Comment by msevestre** [comment]
> Update of previously imported observed data from another data source

I do not understand this use case. You want to update existing data set from another excel file? 

>  import output configurations

What's an import output configuration? 

> When a project is opened: observed data is loaded on the fly

When does the loading happen? When the project is opened, or when the data is accessed?

**Comment by Yuri05** [comment]
>What's an import output configuration?

_import output configuration_ was supposed to be just an _import configuration_.  Description fixed.

>When does the loading happen? When the project is opened, or when the data is accessed?

I think it should happen when the project is opened. In case external data source is missing (or was changed): it will be clear directly at the beginning.

**Comment by msevestre** [comment]
>I think it should happen when the project is opened. In case external data source is missing (or was changed): it will be clear directly at the beginning.

ok it's easier!

**Comment by Yuri05** [comment]
Already implemented as part of Importer-Redesign
