### ISSUE TITLE
[OBSOLETE] Management of (Observed data-) Import configurations within a project

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#617]
# This issue was replaced by #786
Import configurations should be saved as entities within a (PK-Sim/MoBi)-project 
Proposal for visualization:
* **Additional** node in the building block explorer "**(ObservedData)-ImportConfigurations**"
* below this node, ObservedData is displayed grouped by Import-configuration AND by (Import-) Data source.l
* "**ImportConfigurations**" structure is shown **parallel** to the **Observed Data** node
![grafik](https://user-images.githubusercontent.com/25061876/66458723-bf1d0700-ea73-11e9-9e1b-c8f2c93b74ac.png)
Thus in the Building Block-Explorer every observed data set is shown twice:
* under "Observed Data". Here a dataset can be moved into any subfolder (like now)
* under "Import-Configuration". Here, datasets **cannot be moved**.
* Proposal (to be discussed): delete/rename of an observed data set can be done **only** under "Observed Data"-node. The changes will be mirrored the to the "ImportConfigurations"-node

**Comment by ju-rgen** [comment]
I would prefer to visualize the real structure of entities in a - from my perspective - more clear way.
We have the entities **ImportConfiguration**, **Datasource** and **Import**, 
where a Import is defined by an ImportConfiguration and one or more Datasources.

In the example screenshot above the folder "Data source 1" represents an **Import**, _not_ a **Datasource** - this may lead to misunderstandings for the user. 
The situation gets even worse, if we have an Import with 3 Datasources - does this one Import then corresponds to multiple nodes "Data source i" under the configuration node?  Or does the one Import correspond to one node below the configuration node? - how should this be named?

I suggest the following visual representation:

**_ImportConfigurations_**
-	Config1
-	Config2

**_DataSources_**
-	SourceA
-	SourceB

**_Imports_**
-	ImportName1 : Config1 – SourceA 
   o	DS_11
   o	DS_12
-	ImportName2 : Config1 – SourceB
   o	DS_21
   o	DS_22
-	ImportName3 : Config1 – multiple data sources
   o	DS_31
   o	DS_32

**_Observed Data_**
- user specific structure of observerd data

(not clear, whether we should force the user to give a name to each import, or if for "simple imports" the import name could be chosen automatically to "importConfiguration name - datasource name")

Within this representation the user can easily see and select, if he wants to edit/insert/delete an **ImportConfiguration**, a **Datasource** or an **Import**.

Also actions like updates (see https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/620) are more clear then:
The user can select an Import, e.g. ImportName3 and edit the datasources and refresh the import.
(Perhaps it would be even better to reference in plots or parameter identifications "all imported datasets for a selected Import-entity" to allow easy refreshing there?)

I have an additional proposal:

What about moving the Observed data node with the non trivial substructure from the view "Building blocks" to an own view "Experimental data"?

In my opinion the resulting three views correspond to a clear contentwise separation:
- **Building blocks** : Model components 
- **Experimental data** : data from reality
- **Simulations** : Compositions of models and data (e.g. simulations with observed data in plots, parameter identifications based on a model and some experimental data, etc.)

**Comment by msevestre** [comment]
I actually like the proposed folder structure. I think it's quite clear to see what belongs where and with the usage of proper icons and nomenclature, it could be very easy to understand

 My only concern is how would it look like with real names

* Config1...n. What would be  a typical name? Who defines this name?
* Date source 1...n.  Let say I import from two files: C:\test\file.xls and  C:\test\file2.xls. What do we see in the folder structure (or in the flat structure) 
file
file2 

or the full path? 

or the abbreviated path (C:\...\file.xls)

**Comment by Yuri05** [comment]
> In the example screenshot above the folder "Data source 1" represents an Import, not a Datasource - this may lead to misunderstandings for the user.

No, it's indeed a **data source**, not the import. 

>The situation gets even worse, if we have an Import with 3 Datasources - does this one Import then corresponds to multiple nodes "Data source i" under the configuration node?

Yes.

>Also actions like updates (see #620) are more clear then:
The user can select an Import, e.g. ImportName3 and edit the datasources and refresh the import.
(Perhaps it would be even better to reference in plots or parameter identifications "all imported datasets for a selected Import-entity" to allow easy refreshing there?)

I disagree. IT's indeed the **data source** and **not the import** that should be updated. IMHO.

>I have an additional proposal:

What about moving the Observed data node with the non trivial substructure from the view "Building blocks" to an own view "Experimental data"?

An Issue was created for this: #623

**Comment by Yuri05** [comment]
>My only concern is how would it look like with real names
>*    Config1...n. What would be a typical name? Who defines this name?
>*    Date source 1...n. Let say I import from two files: C:\test\file.xls and C:\test\file2.xls. What do we see in the folder structure (or in the flat structure)
    file
    file2

Good question.. I think both config and data source should have a default name which can be changed by user later on. 
* For the config it could be just something like "ImportConficuration1", "ImportConfiguration2", ...
* For the datasource: abbreviated path as default (and full path as tooltext) could be a good choice.

**Comment by ju-rgen** [comment]
@Yuri05 : If the folder "Data source 1" represents a data source, then I do not see the grouping of all files of an Import (where I assumed, that an Import can consist of one ImportConfiguration and multiple Datasources) - wasn't that grouping originally intended by you? Or did you mean a grouping of an ImportConfiguration and ALL datasources, where this configuration was used?

I could imagine the situation, that you perform an import with Conf1 and SourceA, SourceB; then change Conf1 and import with Conf1 SourceA and SourceC. And I had considered this as two Imports. Or are such cases not intended?

**Comment by Yuri05** [comment]
>Or did you mean a grouping of an ImportConfiguration and ALL datasources, where this configuration was used?

Yes.

>I could imagine the situation, that you perform an import with Conf1 and SourceA, SourceB; then change Conf1 and import with Conf1 SourceA and SourceC. And I had considered this as two Imports. Or are such cases not intended?

I think it's pretty rare use case. And in such a case: it could be splitted into the combination of:
* Update SourceA based on Conf1
* Import (new) SourceC based on Conf1

And the result would be:
-- `ImportConfigurations`
---- `Conf1`
------ `SourceA`
------ `SourceB`
------ `SourceC`
