### ISSUE TITLE
[OBSOLETE] Update of previously imported observed data from another data source

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#620]
# This issue was replaced by #785
When importing observed data sets, one import process results in (generally) N observed data sets imported into a project. N>=1 (based on the grouping information).
It should be possible to update observed data sets imported from one data source by selecting another data source.
Here, ALL data sets will be updated simultaneously. It should not be possible to update only SOME of datasets previously imported from one data source (consistensy!)

Proposed workflow:
* Under "ImportConfigurations"-node: user selects a data source to be updated 
* User defines new data source
* Preview is shown (s. #625)
  * In the preview in this use case it **should not be possible to change the import configuration**
  * Only **NEWLY ADDED** datasets be selected/deselected (s. also #625)
![grafik](https://user-images.githubusercontent.com/25061876/66459107-9ea17c80-ea74-11e9-8840-c7a996fa2267.png)

Possible use cases here:
1. New data source has the _same structure_ (e.g. data columns) and the _same combinations of metadata_ **relevant for grouping**. Here, N datasets previously imported from another data source will be just updated with the new data
2. New data source has the _same structure_ but some _different combinations of metadata_ **relevant for grouping**. 
  a. In case of NEW grouping metadata (e.g. previous import had observed data for the Individuals 1, 2 and the new one for the individuals 1, 2,3): info for the user is shown, import can be performed
  b. In case of DELETED grouping metadata (e.g. previous import had observed data for the Individuals 1, 2 and the new one for the individuals 2,3): ERROR, Import CANNOT be performed. In such a case user has to explicitly delete observed data sets from the project first in order to be able for updating.
3. New data source has _different structure_ (e.g. data columns)
  a. If structure elements used in previous import configuration are not available in the new data source (e.g. one mapped column was deleted): ERROR, import not possible
  b. If new structural elements were added (e.g. new columns). **To be discussed**. The easiest option would be: 
    * show a warning to the user and ignore additional structure elements. 
    * After that continue with analyzing metadata and proceed according to the UseCases 1 and 2 above.

**Comment by ju-rgen** [comment]
I find unclear (for me and also users) what is represented by the node "Data source 1": 
does this correspond to an import (with only one or possibly multiple datasources?) ?
or does this correspond to a Data source - but the same Data source could be used under another ImportConfiguration ....

See my remarks here: https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/617#issuecomment-540013030

**Comment by msevestre** [comment]
>but the same Data source could be used under another ImportConfiguration ....

yes this is not a problem. Datasource corresponds to one specific file (Excel, CSV, Nonmem...potentially DB etc..)

The combination of an `ImportConfiguration` and a `data source` creates a well defined set of observed data.  If one decides to use the same data source with two different import configurations, the source name would appear twice. It seems to me like a very edge case to be honest but I may be wrong

**Comment by ju-rgen** [comment]
Does the combination of ImportConfiguration and Datasource really uniquely define the dataset?
What happens, if a datasource or an importConfiguration has been changed?
Should it be impossible to keep the old and the new datasets - at least for comparison reasons?
@Yuri05 - what do you think?

**Comment by Yuri05** [comment]
>yes this is not a problem. Datasource corresponds to one specific file (Excel, CSV, Nonmem...potentially DB etc..) 

Exactly. It should be possible to import the data from the same data source but using different configurations (and for some complicated files with several ranges of interest it might be the only way to import all the data without transforming the input data in other format first)

**Comment by Yuri05** [comment]
>Should it be impossible to keep the old and the new datasets - at least for comparison reasons?
@Yuri05 - what do you think?

I think: Yes (it should **not** be possible to keep the old dataset.)

**Comment by ju-rgen** [comment]
1) What does this mean for reproducibility of results?
2) How is a ImportConfiguration and a Datasource defined/identified? Just by a local filepath?

**Comment by Yuri05** [comment]
>What does this mean for reproducibility of results?

Even after this change observed data will not changed _automatically_ just because the external data source (e.g. excel file) was changed. So unless user **explicitly** updates observed data within a project - nothing will happen.
**Later**, when we introduce observed data _references_ (where the data is not stored in a project at all; but e.g. updated on the fly during the project loading), we will need some kind of checksum, which will be stored in projects. If the data was changed in the external data source, user will become a warning and some options for further actions. 

>How is a ImportConfiguration and a Datasource defined/identified? Just by a local filepath?

Import configuration: just by its name.
Datasource: yes, by a local (or remote, e.g. GitHub) path
