### ISSUE TITLE
Update of previously imported observed data after metadata change

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#621]
For the use case described in #785: observed data sets imported from one data source using particular import configuration are identified by the **combination of metadata used for grouping**. E.g. if I import the table below and use the columns **{Organ, Compartment, Species, Patient id}** for grouping: 2 observed data sets will be imported. Every data set is identified by the combination of {Organ, Compartment, Species, Patient id}.
However meta can be overwritten by user in the project (e.g. in example above: user would change a patient id for one imported observed data set).
Now when updating imported observed data from a new source: how should we deal with such datasets?

Time [min] | Organ | Compartment | Species | Patient id | Concentration [mg/ml]
-- | -- | -- | -- | -- | --
1 | Brain | Plasma | Human | 347 | 0,1
2 | Brain | Plasma | Human | 347 | 12
2 | Liver | Plasma | Human | 256 | 8
3 | Liver | Plasma | Human | 256 | 2

**Comment by msevestre** [comment]
In my opinion: Edit of observed data in PKSim and MoBi should be forbidden. In order to update data, user would need to update the source file and refresh the data set

**Comment by PavelBal** [comment]
Current behavior - the modified data set will be removed, a new data set will be created. I think this is the correct behavior.
