### ISSUE TITLE
Import further data files using existing import configuration

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#622]
It should be possible to import data from new data sources based on a previously used import configuration.

Proposed workflow (**to be discussed**):
1. User starts observed data import dialog

2. User selects one data source

3. User selects available import configuration from a drop-down menu
    * Per default all import configurations available in the project can be selected
    * Additionally it could be possible to load import configurations from:
      * Template database
      * Snapshot
<br>

4. Preview is shown. In the preview:
    * It should be possible to change the import configuration
    * A preview of all datasets which could be imported is shown. 
    * The user can only select/deselect observed data sets that should be imported from new data sources (**to be discussed**: should deselection of some data sets be possible or not?)
   * When the user clicks on one data source: preview of the data which would be imported is shown.
   * In case the import configuration was modified: user is asked to save it under a new name (overwriting of existing import configurations might be problematic for the use case #785)

<details><summary><b>Previous state of the discussion</b></summary>
It should be possible to import data from new data sources based on a previously used import configuration.

Proposed workflow (**to be discussed**):
1. User starts observed data import dialog

2. User selects one **or more** data sources (**to be discussed: should we allow MULTIPLE data sources or not?**)

3. User selects available import configuration from a drop-down menu
    * Per default all import configurations available in the project can be selected
    * Additionally it could be possible to load import configurations from:
      * Template database
      * Snapshot
<br>

4. Preview is shown. In the preview:
    * It should not be possible to change the import configuration (**to be discussed!**)
    * A preview of all data sources and datasets which could be imported is shown. Could look like this:
![grafik](https://user-images.githubusercontent.com/25061876/66464075-9b12f300-ea7e-11e9-94f7-35c46a5040d6.png)
    * Data sources which are not conform with the selected import configuration are marked with an exclamation mark. No data can be imported from them.
    * Data sources which are already available in the project for the given import configuration: **to be discussed**.
      * Either they should be automatically updated in this case according to #785
      * Or they are marked as available and **cannot** be imported (user must explicitly start the UPDATE use case for them)
    * For all other valid data sources: the user can only select/deselect observed data sets that should be imported from new data sources
   * When the user clicks on one data source: preview of the data which would be imported is shown.
</details>

**Comment by msevestre** [comment]
> User selects one or more data sources

More than one? Really?

**Comment by Yuri05** [comment]
Implemented with ObservedData Import Redesign (via Save/Load of importer configuration)
