### ISSUE TITLE
Handling of data ranges

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#624]
During creating of import configuration user can optionally select a data range to be used for import.
For the use case described in #785 (Update of existing observed data) and #622 (import of new datasets based on a given import configuration): relevant data range might grow or shrink in the new data source.
Proposal for the handling in case of update:
* Import configuration saves top left cell of the selected data range
* When a new data source is imported: data range is extended to the right and to the bottom until the right column / the bottom row are not empty

**Comment by msevestre** [comment]
I somewhat disagree. Data amount would grow or shrink, but only if NO RANGE was selected correct?
If  a range was selected (e.g. Col 1 to Col 10 and row 20 to row 30), then the range would not change

**Comment by msevestre** [comment]
In my opinion, the user should perform work on the source file before importing
I do not see how this use case make sense to select a SPECIFIC use range, and then ask the tool to magically extend it

I agree that if no range is selected, the data should extend  with the number of rows

Does data extension by column make sense at all? I know it's possible to construct such case but do we really need this?

**Comment by Yuri05** [comment]
>Does data extension by column make sense at all? I know it's possible to construct such case but do we really need this?

I think indeed, we don't need this
