### ISSUE TITLE
Preview of data in the import configuration editor

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#625]
There are 2 previews of the data:
1. Preview of raw data (on demand): only the data columns selected in mapping (and within a selected data range if applies) should be shown. Should be restricted per default to 100(?) rows.
2. Preview of data sets to be imported (on demand):
  Per default preview shows selected data sources with the datasets potentially available for import. Here the user can select/deselect single data sets. When the user clicks on one data set, preview can be shown on demand (I would also add here a checkbox "Show preview for selected data set automatically")
![grafik](https://user-images.githubusercontent.com/25061876/66467196-58541980-ea84-11e9-90f6-2fb188dd1491.png)

**Comment by msevestre** [comment]
> When the user clicks on one data set, preview can be shown on demand (I would also add here a checkbox "Show preview for selected data set

I would be careful with this. Especially, I think we should rethink how we display multiple datasets. I don't think a tab approach like we have so far is a good idea. I would suggest to only show on demand and NOT ALLOW any change configuration in specific data set (e,g unit etc..)

**Comment by Yuri05** [comment]
Implemented as part of Importer Redesign
