### ISSUE TITLE
Observed data import: data filtering

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#627]
Current observed data import does not support any data filtering.
It would be useful to have some filtering options:

E.g. handling of NaN values (import or ignore or show error).
In the next versions of observed data import also some advanced filtering (e.g. only import data for Time <=24 h) could be introduced.

**Comment by msevestre** [comment]
> handling of NaN values (import or ignore or show error).

Agree with this. But any other filtering should be done prior to import. This is not the job of the importer to perform pre data manipulation IMO
