### ISSUE TITLE
Missing line of identity in predicted vs observed

### ISSUE THREAD

**Issue by wilbertdew** [Open-Systems-Pharmacology/OSPSuite.Core#650]
Hi All,

Sometimes, the line of identity does not show up in my predicted vs observed plot, anyone recognize this issue? When I add symbols to this line, I only see one upper right symbol. In the legend, I do see a dashed line for identity. Disabling side margins does not help.
Any help would be appreciated.

P.S. In this plot, Predicted is on the y-axis and observed on the x-axis, while I believe it should be the other way around. I could not find the option to change this, is this available? Could the default be changed or is there disagreement on which one should be on the y-axis?

**Comment by msevestre** [comment]
This is a bug in the charting component

**Comment by PavelBal** [comment]
No way to reproduce without an example. Closing for now.

@msevestre @Yuri05 please re-open if you know exactly what the bug is and how to solve. Otherwise - have to wait until it is re-discovered.
