### ISSUE TITLE
Correlation and covariance matrix export

### ISSUE THREAD

**Issue by JGWojtyniak** [Open-Systems-Pharmacology/OSPSuite.Core#651]
Dear Community,

I wanted to ask if someone knows a way to export the correlation/covariance matrix which can be calculated by PK-Sim/MoBi during the parameter identification process (see figure below)? 
Neither to export it like a table by mouse right-click nor the import/export tab worked. Preffered export format would be a .csv file.

Thank you in advance and with best regards,
Jan
![correlation_matrix](https://user-images.githubusercontent.com/31009803/66632827-a47c9680-ec09-11e9-84e4-c2d8525a9ad4.JPG)

**Comment by msevestre** [comment]
@JGWojtyniak Not possible at the moment.
We can definitely and easily ensure that you can copy paste the content to excel fo example. This should be possible and is clearly and oversight

**Comment by msevestre** [comment]
@JGWojtyniak FYI I moved the issue into the code repo as feature request

**Comment by JGWojtyniak** [comment]
@msevestre Ok, good to know. Thank you for the quick response and for moving the issue to feature requests.

Best regards,
Jan
