### ISSUE TITLE
Observed data format: TTunitCompCCunit

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/OSPSuite.Core#656]
In addition to the suggested data formats, I'd also like to see the following format:

Time | Time unit | Comp | DV | DV unit
-- | -- | -- | -- | --
0.5 | h | Plasma | 0.534 | mg/L
1 | h | Plasma | 1.235 | mg/L
2 | h | Plasma | 0.982 | mg/L
4 | h | Plasma | 0.713 | mg/L
6 | h | Plasma | 0.568 | mg/L
8 | h | Plasma | 0.388 | mg/L
12 | h | Plasma | 0.102 | mg/L
12 | h | Urine | 15 | %

[Book1.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/3762355/Book1.xlsx)

**Comment by Yuri05** [comment]
What should happen in the case below (different units for the same data set)?
Error or convert alldata to the FIRST unit found or ...?

Time | Time unit | Comp | DV | DV unit
-- | -- | -- | -- | --
0.5 | h | Plasma | 0.000534 | **g/L**
1 | h | Plasma | 1.235 | **mg/L**
2 | h | Plasma | 0.982 | **mg/L**
... | ... | ... | ... | ...

**Comment by msevestre** [comment]
I don't this format should be supported. This is the first instance where we would have to map a column into something else that data or meta data. Suddenly, we need to support relationship between columns

**Comment by AndreDlm** [comment]
> What should happen in the case below (different units for the same data set)?
> Error or convert all data to the FIRST unit found(*) or ...?

Error is fine for me if that's easy to implement.

I don't like this format neither, but it's quite common and I do get data in this format. So a clear feature wish from my side.

**Comment by msevestre** [comment]
>What should happen in the case below (different units for the same data set)?

Not an error in my opinon (unless the unit is not in the same dimension). In your example, we just convert and show the value in the baseunit

>but it's quite common and I do get data in this format. 

Maybe ask the exchange format to be changed instead? We cannot support all possible format. This is precisely a wish of the new implementation.

**Comment by ju-rgen** [comment]
Isn't this format the most similar to the common format used in Nonmem, e.g.
Study,SubjectId,RecordType,Treatment,Dose,...,Component,**Time,DVID/DVName,DV,DVUnit**,Organ,Compartment, ....
where DVName can be e.g. Concentration,Fraction,... even BloodPressure
Such format should be included as it seems to be a (or the) typical format.

**Comment by Sulav1** [comment]
I agree with Jürgen. Most of times the data are already in NONMEM format. This would allow same data to be used by PKSIM and other software like NONMEM.

**Comment by Yuri05** [comment]
Subset of #797
