### ISSUE TITLE
PI: Visual Feedback shows identical values for Best and Current

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#702]
In the Viesual Feedback of a PI, the values of parameters shown in the columns "Best" and "Current" are always equal, though the error might be different.

![image](https://user-images.githubusercontent.com/25903040/72983096-d98bae00-3de0-11ea-9e04-a3049e404381.png)

**Comment by msevestre** [comment]
@PavelBal Does it happen wuth every algorithm or just MC?

**Comment by msevestre** [comment]
Only MC I believe

**Comment by PavelBal** [comment]
> Does it happen wuth every algorithm or just MC?

@msevestre Cannot say, I use MC most of the time.
