### ISSUE TITLE
Export of Results from and to csv 

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#704]
AT the moment we use a constant called QUANTITY_PATH with a value of Quantity Path
   public const string QUANTITY_PATH = "Quantity Path";

I think we should remove the space as it can only create issues with R etc..

Thoughts @Yuri05 ?

**Comment by Yuri05** [comment]
Not sure what the problem is.
Is it about Quntity path [here](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/pull/705/files#diff-9aa979e4e599d9a590e25238d5c2257a)?

**Comment by msevestre** [comment]
no it's about this one 
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/2c34eeca07098537d6c548cdae055838c0209734/src/OSPSuite.Core/Domain/Constants.cs#L326

Quantity Path with space. I think this can only lead to problem

**Comment by Yuri05** [comment]
You mean when you save such a data table to csv which must be handled by R later on? 
Or which use cases do you have in mind?

**Comment by msevestre** [comment]
In general. Exporting space in header is not a good idea as it always require special handling. By default, we should aim at exporting stuff without space

**Comment by Yuri05** [comment]
In this particular case I don't mind. We can remove the space.
In general we have plenty use cases where blanks are part of the headers (population tables etc.). Exporting headers in double quotes is usually OK.
