### ISSUE TITLE
Horizontal scrolling in Building Blocks Explorer

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#734]
Please enable horizontal scrolling in the BB explorer:

![image](https://user-images.githubusercontent.com/25903040/74726686-2d52b100-5240-11ea-92d3-9fd3cd5d29cd.png)

**Comment by msevestre** [comment]
@PavelBal This is fixed

**Comment by PavelBal** [comment]
Great, thanks!
