### ISSUE TITLE
Remove FuncParserException

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#739]
and replace all usages with `OSPSuiteException`
This together with https://github.com/Open-Systems-Pharmacology/OSPSuite.FuncParser/issues/37 will fix https://github.com/Open-Systems-Pharmacology/MoBi/issues/453

@msevestre Or do you see any reason why we would need `FuncParserException`?

**Comment by msevestre** [comment]
In case we want to do something specific when a function cannot be parsed. OSPSuiteException is very generic and can be thrown from anywhere. I think having a specific exception is not a bad idea.

But I do not know how this was used so far

**Comment by Yuri05** [comment]
ok, I'll keep it for the moment but will adjust the usage, currently it's not correct anyway.

**Comment by msevestre** [comment]
What's the status here?
