### ISSUE TITLE
blank sensitivity analysis results with a valid variable parameter

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/OSPSuite.Core#752]
Concerns [this](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/develop/tests/dev/test-sa-path-error.R) test.

This contains a sensitivity analysis where the variable parameter was selected from ospsuite::potentialVariableParameterPathsFor(), so it is a valid parameter for SA.

Issue is that the sensitivity analysis results are returned blank.

The results (from a reporting engine run) are in this zip file:  
[Workflow_20200315_144023.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/4334854/Workflow_20200315_144023.zip)

**Comment by msevestre** [comment]
I have moved the issues to core as the fix needs to be performed here
