### ISSUE TITLE
Observed Data Formats

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#787]
I've seen some discussions on support of different formats of observed data import. Is it actually planned to _automatically_ guess which format the imported file representes?

I would suggest to only have a defined set of supported data formats (which are described somewhere in the wiki), and the user should select which data format he is loading.

**Comment by msevestre** [comment]
What do you mean @PavelBal ?
What discussions are you referring to? Are you talking about file format? (E.g. csv, XLS)

**Comment by PavelBal** [comment]
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/656
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/649
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/647

and so on.

**Comment by msevestre** [comment]
Why should the user select the format if the tool can identify it?
