### ISSUE TITLE
Observed data format: DV oriented (Nonmem like)

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/OSPSuite.Core#797]
Very common in study data handling (e.g. when working with the popular Nonmem) is the provision of parameter values in a column DV (dependent variable), where the type of the parameter is given in a numerical column DVID or a alphanumerical column DVNAME with a standardized list of parameter types *like "Concentration","Fraction","SBP" (systolic blood pressure), "DBP", "HR" (heart rate), ...*
In an additional column DVUNIT the unit of the parameter value is given, e.g. "µg/l","%",... (*needs to be clarified, if consistent units are expected for a data series or not*).

For such files a (pre)selection of columns of interest is helpful to keep the overview, because they can contain >100 columns.

The option to filter the records before import is important, because in such files often not only observation records (but e.g. also application records) are given and because records to be excluded in certain analyses are often marked by entries in certain flag columns (*e.g. a validity flag VFLAG for DV values, which could be 0 for valid values, 1 for values below LLOQ, 2 for kinetically implausible values*).
*It needs to be clarified, if filtering should be possible just in total or specifically per imported parameter.*

Multiple columns in this example are already chosen according to the existing OSP Data Import pattern, e.g. grouping by ORGAN, COMPARTMENT, MOLECULE, PATIENT_ID, ....

[NM_like_DV.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/4722245/NM_like_DV.xlsx)

Simplified example:
|SID|TGR|SEX|WGHT|CYLCLE|TADP|TAD|AMT|DOSE|RECTYPE|ORGAN|COMPTMT|MOLECULE|DVNAME|DV|DV_UNIT|LLOQ|VFLAG
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
|100010002|GBCA_0.03|Female|70,7|1|0|0|2,13|0,03|DOSING||||||||
|100010002|GBCA_0.03|Female|70,7|1|2|3,1||0,03|OBSERVATION|PVB|Plasma|HRCA|Concentration|21,962|umol/L|1,5|0
|100010002|GBCA_0.03|Female|70,7|1|3|3,8||0,03|OBSERVATION|Bladder|Urine|HRCA|Fraction|5|%||0
|100010002|GBCA_0.03|Female|70,7|1|6|6,77||0,03|OBSERVATION|PVB|Plasma|HRCA|Concentration|4,153|umol/L|1,5|0
|100010002|GBCA_0.03|Female|70,7|1|6|9,51||0,03|OBSERVATION|Bladder|Urine|HRCA|Fraction|11|%||0
|100010002|GBCA_0.03|Female|70,7|3|0|0|7,1|0,1|DOSING||||||||
|100010002|GBCA_0.03|Female|70,7|3|2|2,77||0,1|OBSERVATION|PVB|Plasma|GADOBUTROL|Concentration|131,138|umol/L|2,5|0
|100010002|GBCA_0.03|Female|70,7|3|3|2,98||0,1|OBSERVATION|Bladder|Urine|GADOBUTROL|Fraction|10|%||0
|100010002|GBCA_0.03|Female|70,7|3|6|6,27||0,1|OBSERVATION|PVB|Plasma|GADOBUTROL|Concentration|18000,08|umol/L|1,5|2
|100010002|GBCA_0.03|Female|70,7|3|6|7,33||0,1|OBSERVATION|Bladder|Urine|GADOBUTROL|Fraction|16|%||0
|100010004|GBCA_0.01|Male|92,6|2|0|0|0,93|0,01|DOSING||||||||
|100010004|GBCA_0.01|Male|92,6|2|1|0,87||0,01|OBSERVATION|Bladder|Urine|HRCA|Fraction|4|%||0
|100010004|GBCA_0.01|Male|92,6|2|2|2,03||0,01|OBSERVATION|PVB|Plasma|HRCA|Concentration|16,29|umol/L|1,5|0
|100010004|GBCA_0.01|Male|92,6|2|6|7,78||0,01|OBSERVATION|PVB|Plasma|HRCA|Concentration|0,89|umol/L|1,5|1
|100010004|GBCA_0.01|Male|92,6|2|6|8,11||0,01|OBSERVATION|Bladder|Urine|HRCA|Fraction|14|%||0
|100010004|GBCA_0.01|Male|92,6|3|0|0|9,3|0,1|DOSING||||||||
|100010004|GBCA_0.01|Male|92,6|3|2|3,27||0,1|OBSERVATION|PVB|Plasma|GADOBUTROL|Concentration|171,594|umol/L|2,5|0
|100010004|GBCA_0.01|Male|92,6|3|6|6,82||0,1|OBSERVATION|PVB|Plasma|GADOBUTROL|Concentration|56,275|umol/L|1,5|0

**Comment by sfrechen** [comment]
Thanks @ju-rgen .
Fully support this as this is also fully compatible with the dataset concept in the reporting engine .
