### ISSUE TITLE
_norm PK Parameters return NaN in multiAdmin-simulations

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#798]
see https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/403

**Comment by msevestre** [comment]
@Yuri05 The normalization per interval was never implemented in Core. Only in PKSim.
This is the already the case when calculating SA in V8 in MoBi.

**Comment by msevestre** [comment]
see code in PK-Sim

```
  public override void UpdateTotalDrugMassPerBodyWeight(IModelCoreSimulation simulation, string moleculeName, PKCalculationOptions options, IReadOnlyList<ApplicationParameters> allApplicationParametersOrderedByStartTime)
      {
         base.UpdateTotalDrugMassPerBodyWeight(simulation, moleculeName, options, allApplicationParametersOrderedByStartTime);

         if (options.SingleDosing)
            return;

         //we have at least 2 applied applications at that stage since we are in multiple dosing mode
         var bodyWeight = simulation.DowncastTo<Simulation>().BodyWeight?.Value;
         var applicationCount = allApplicationParametersOrderedByStartTime.Count;
         options.FirstInterval.DrugMassPerBodyWeight = drugMassPerBodyWeightFor(allApplicationParametersOrderedByStartTime[0].DrugMass, bodyWeight);
         options.LastMinusOneInterval.DrugMassPerBodyWeight = drugMassPerBodyWeightFor(allApplicationParametersOrderedByStartTime[applicationCount - 2].DrugMass, bodyWeight);
         options.LastInterval.DrugMassPerBodyWeight = drugMassPerBodyWeightFor(allApplicationParametersOrderedByStartTime[applicationCount - 1].DrugMass, bodyWeight);
      }
```

**Comment by msevestre** [comment]
with 
```
  private double? drugMassPerBodyWeightFor(IParameter drugMass, double? bodyWeight)
      {
         if (drugMass ==null || bodyWeight == null || double.IsNaN(bodyWeight.Value))
            return null;

         return drugMass.Value / bodyWeight.Value;
      }
```

**Comment by msevestre** [comment]
The issue is that one does not have the bodyweight as a parameter in the simulation. But we could add it as a nullable (that would return null if not defined.). That way, we can potentially make that work for Core and R as well. Thoughts?

**Comment by Yuri05** [comment]
>The issue is that one does not have the bodyweight as a parameter in the simulation. 

I wonder why C_max_norm, AUC_norm etc. (for **single** admin) works then in MoBi/RE. Because bodyweight is required here as well.

**Comment by msevestre** [comment]
Because we have a function for this. Totaldrugmassperbodyweight

**Comment by Yuri05** [comment]
>The issue is that one does not have the bodyweight as a parameter in the simulation. But we could add it as a nullable (that would return null if not defined.). That way, we can potentially make that work for Core and R as well. Thoughts?

Sounds reasonable, don't see a problem if we introduce BW in Core

**Comment by msevestre** [comment]
ok will implement now. This will mean a new version of PKSim and MoBI
