### ISSUE TITLE
Nuget symbol package not valid

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#808]
see https://github.com/NuGet/NuGetGallery/issues/7668#issuecomment-552021977

**Comment by msevestre** [comment]
due to https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/src/OSPSuite.Core/OSPSuite.Core.csproj#L22

@Yuri05 What was the reason for this change again?

**Comment by Yuri05** [comment]
assume this is obsolete. closing
