### ISSUE TITLE
Icon for Endosome

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#829]
We do not have an icon for Endosome. I will ask our designer to design one for us

How should it look like

What about something like this?
![image](https://user-images.githubusercontent.com/1041237/95589687-13eeb700-0a13-11eb-8996-c52bc52fb533.png)

Feedback please @StephanSchaller , @Christoph27, @Yuri05 @pavelbal, @prvmalik

**Comment by msevestre** [comment]
All right. Thanks for the feedback. I'll go ahead with this version then

**Comment by StephanSchaller** [comment]
You are welcome ;-)
