### ISSUE TITLE
Molecule keyword replacement does not work for global parmaeter referencing other global molecule parameters

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#832]
Trying to define a global parameter such as 

fract_exp_baso = 1 - fract_exp_api - fract_exp_end does not work when all references are global

**Comment by Yuri05** [comment]
why not just use` ..` instead of `MOLECULE`? if a global molecule parameter references another global molecule parameter - both are in the same container

**Comment by msevestre** [comment]
True. But this should still work;-)
Also we had this issue where we said that global parameters should be accessed via absolute path because it's easier to understand
