### ISSUE TITLE
Importer-Redesign: columns not selectable

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#867]
In the example attached only 2 columns can be mapped to concentration. Why?
Theoretically it should be possible to map ANY suitable column from the sheet (from the **user** point of view only marked columns would make sense but the importer cannot check this. Thus here I would expect ALL columns except time to appear in the mapping combobox (of course if not already mapped/groupped))

![grafik](https://user-images.githubusercontent.com/25061876/104352069-7ec5f780-5506-11eb-999d-f1cc6b2a27e6.png)
[TST_Data.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/5803847/TST_Data.xlsx)

@sfrechen @Sulav1 @ju-rgen @Christoph27 FYI

The same applies for the error column: while from the **user** perspective only **SD** and **gSD** columns would make sense, importer should allow selection of any suitable column
![grafik](https://user-images.githubusercontent.com/25061876/104352993-a79abc80-5507-11eb-8bb6-b8bd92f52039.png)

**Comment by abdelr** [comment]
@Yuri05 I will take a look and come back to you with an answer but looks like some bug, not an intended behavior.
