### ISSUE TITLE
Importer-Redesign: Measurement settings

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#877]
Some improvement suggestions for the measurement settings window:

* rename "assign a column" to "Import unit from a column"
* Introduce "Import LLOQ from a column" selector:
  * If activated: combobox with column selection for LLOQ is shown
![grafik](https://user-images.githubusercontent.com/25061876/104585378-31f83300-5664-11eb-90ac-09d0e1cabc10.png)
  * If deactivated: combobox is hidden and information text will be shown
![grafik](https://user-images.githubusercontent.com/25061876/104585619-93200680-5664-11eb-9730-0f150cd6c65c.png)

**Comment by Yuri05** [comment]
@sfrechen @Sulav1 @ju-rgen @Christoph27FYI
Better suggestions for the "LLOQ explanation text" (s. above) are welcome :)

**Comment by PavelBal** [comment]
What happens in case there are different <xxx entries in the data set, e.g., one entry is "<0.2" and another is "<0.3"?

**Comment by Yuri05** [comment]
>What happens in case there are different <xxx entries in the data set, e.g., one entry is "<0.2" and another is "<0.3"?

2 options:
* either the same as in case of LLOQ defined in a separate column, namely different LLOQs will be set for different data points
* or Error

Im principle I don't see a reason why with the new concept we should not allow different LLOQs with "< xx"
