### ISSUE TITLE
Importer-Redesign: Error settings

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#878]
At the moment error settings window has the same unit selection possibilities as in the measurement settings (select from a column; Dimension/Unit).
<img width="450" src="https://user-images.githubusercontent.com/25061876/104585983-248f7880-5665-11eb-9f88-1630f1c1452a.png">

Some suggestions to improve it and better match the unit settings of the measurment:

* When the Error Type is set to "Geometric": unit selection should be completely hidden (in this case the error dimension would be always Dimensionless, so no further unit selection options are required)
<img width="450" src="https://user-images.githubusercontent.com/25061876/104586568-ee062d80-5665-11eb-9670-9083e4e712e9.png">

* When the Error Type is set to Arithmetic
  * If in the **measurement** unit settings **Dimension and Unit** are set ("Select unit from a column = OFF"): show only the unit (because the dimension of the arithmetic error can only be the same as the dimension of the measurement)
<img width="450" src="https://user-images.githubusercontent.com/25061876/104587533-543f8000-5667-11eb-96e7-9f283717f5a2.png"><br>Every time the user changes the Dimension of the measurement, the unit selected for the error is validated. If it is not valid, a warning is shown, and the user has to change the unit.<br>**Question 1**: do we still need "Import units from column" here?

  * If in the **measurement** unit settings **Import unit from a column** is set ("Import unit from a column = ON"): only the "Import from a column" option is available
  <img width="450" src="https://user-images.githubusercontent.com/25061876/104589170-c1ecab80-5669-11eb-9a98-b93bda347aa6.png"><br>**Question 2**: what we cannot handle with this proposal is something like in the example below - but I think we can just ignore such a weird data? Or should we allow import of data like below?

Time [min] | Amount | Amount_Unit | Error [µmol]
-- | -- | -- | --
  | 1 | mol | 2
  | 2 | mmol | 2

@sfrechen @Sulav1 @ju-rgen @Christoph27 @PavelBal @StephanSchaller please comment (especially regarding the 2 questions)

**Comment by ju-rgen** [comment]
To question 1: yes, we must be able to select a unit column (most often the measurement unit column).
To question 2:  I do not see, what cannot be handled here. As Error unit could be selected fixed µmol OR the Amount_Unit column. One of these options should be correct.

One additional remark: Because the display or unit selection options depends on the Error Type, I personally would opt to move the Error Type selection to the top of the window, because natural order of users actions is top-down.

**Comment by Yuri05** [comment]
>To question 2: I do not see, what cannot be handled here. As Error unit could be selected fixed µmol OR the Amount_Unit column. One of these options should be correct.

The suggestion above was "**only the "Import from a column" option is available**" (but **not the Dimension/Unit** option). If done so, the example above cannot be imported. And that was the question: do we need the combination "measurement units *from a column* but error units **set as dimension/unit**" to be able to import data like in the example above?

>Because the display or unit selection options depends on the Error Type, I personally would opt to move the Error Type selection to the top of the window, because natural order of users actions is top-down.

makes sense :)
