### ISSUE TITLE
Importer-Redesign: Filter

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#880]
Data filter can be set in the data preview. Those filter could be used for the **data filtering during the import** as well.
(s. [Filter Editor tutorial](https://docs.devexpress.com/WindowsForms/114645/controls-and-libraries/data-grid/getting-started/walkthroughs/filter-and-search/tutorial-filter-editor) for details)
![grafik](https://user-images.githubusercontent.com/25061876/104592597-ba7bd100-566e-11eb-9527-261a35ccfd3a.png)

To distinguish if the filter was set by user just for **inspecting** the data (but still ALL data must be imported) or the filter really should be used to filter out some data during the import, an additional option "Import only filtered data" (default: FALSE) should be introduced:
![grafik](https://user-images.githubusercontent.com/25061876/104593252-b0a69d80-566f-11eb-9780-11b4daa5609c.png)

**Caution when filtering out some data from the columns used for groupping** - this might have side effects when updating the imported data from a new data source (https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/785)

**Comment by ju-rgen** [comment]
I personally prefer a simple checkbox for the yes/no decision for import only filtered data, because I find it more clear than the Switch with changing Off (On) captions.
About the default TRUE or FALSE should the users decide.
