### ISSUE TITLE
LLOQ: Now that LLOQ can be a column, what has changed for other part of the software using it?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#887]
/cc @Yuri05 @abdelr @georgeDaskalakis 
LLOQ used to be a single value. Now it's an array of value (potentially).
Has the code been updated to support this ? Off the top of my head, LLOQ is used in
1. Parameter Identification
2. Charts

**Comment by StephanSchaller** [comment]
Only one value should be assigned per imported (split) dataset.

So: either 
- abort and make sure there is a consistent LLOQ for a set of measurements or
- let the user choose one of the entries if there have (accidently?) been multiple LLOQs set for one imported (split) dataset

**Comment by msevestre** [comment]
I might be wrong but I don't think this is how it should work. It is possible to define an LLOQ value PER point. That's why LLOQ is now a column and not a single value in a dataset.  
Is this correct @Yuri05 ? Different point within a dataset can have different LLOQ? Or are we at the end expecting all values to be the same for one DataSet (easier!)

**Comment by Yuri05** [comment]
>Is this correct? Different point within a dataset can have different LLOQ? 

Yes!

**Comment by StephanSchaller** [comment]
> Yes!

This makes no sense?!
Can you give me an example? LLOQs are assay-specific...so typically one set of measurements has the same LLOQ.

**Comment by msevestre** [comment]
I hope we don't have to implement this. Or we take the lower value or sthg. Because it will make the code extremely more complicated

**Comment by msevestre** [comment]
@StephanSchaller @Yuri05 
Just talked to Andrea. She said it does not make sense either (or it is a VERY BAD PROTOCOL) to have multiple LLOQ within one dataset. 
So I would suggest to NOT implement this for three reasons
1-We don't have much time
2-It will make the code much complicated everywhere
3-it does not make sense to support such a feature

**Comment by Yuri05** [comment]
>Can you give me an example? LLOQs are assay-specific...so typically one set of measurements has the same LLOQ.

Example: samples from a long time experiment are sent to *different labs* which use different assays.

**Comment by msevestre** [comment]
Yes but then they should be two different data sets or the lowest value should be used

**Comment by msevestre** [comment]
This is such a specific use case. I don't think we should support it

**Comment by Yuri05** [comment]
>Yes but then they should be two different data sets or the lowest value should be used

You mean e.g. grouped/splitted by the lab name? Maybe...

**Comment by msevestre** [comment]
Yes exactly. Same patient id, but two different dataset. This is a very complex change (chart, serialization, parameter identification) for such a very rare case.

**Comment by StephanSchaller** [comment]
> Example: samples from a long time experiment are sent to different labs which use different assays.

you have this as a use case?... you changed the lab/vendor in-between?... are the subjects (from which the blood is sampled) still the same?

**Comment by Yuri05** [comment]
>you have this as a use case?... you changed the lab/vendor in-between?... are the subjects (from which the blood is sampled) still the same?

Yes. Yes. Yes. 
But as Michael mentioned above: this could be solved e.g. by adding the **grouping by the lab id**.

**Comment by StephanSchaller** [comment]
For now only assign ONE LLOQ per dataset and assigned the value of LLOQ/2 for caluse < LLOQ

Only one value per dataset
- Split dataset by a column "lab" if you have multiple LLOQ values
- if you still have multiple LLOQ in the dataset show an error

**Comment by abdelr** [comment]
Developer comment: Check DataSetToDataRepositoryMapper.cs line 103...
