### ISSUE TITLE
Update: ChartTest program 

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#89]
* Data Repository always creates the same curves. This is ok for this one problem we try to solve but will be an issue if we try to solve/understand other problems with this tool. Add some randomization (I think the previous code was doing a great job at generating curves that were not monotonous)

* Generated Observed Data do not represent are usual observed data. We need to have data with Errors, and less point that the Simulation data. Especially, the number of point and X values should not always be the same

* Last but not least, we also need some curves with GeoMean and Arithmetical Mean set. This is one of the feature that the chart is provided and we cannot test it anymore

**Comment by rwmcintosh** [comment]
We can improve the data repositories that are added by number, but all the
old repositories are still there as well.

**Comment by msevestre** [comment]
not sure what you mean.  I am talkign about the generated data. They should
not alwyas be the same, and obs data should look like observed data and not
calculated data

**Comment by rwmcintosh** [comment]
I mean if you use a different button, the original data repositories are
still available.

**Comment by msevestre** [comment]
ok. I think however that the N added observed data should be real observed data, just in case the drawing of other type of series is what's being slow.
Also let's add some randomness to those values. All points are one on top of the other right now. Who knows if the chart is done doing some special stuff internally

**Comment by msevestre** [comment]
There are still a bunch of stuff to change:

* With Arithmetic Mean and With Geometric Mean. Is this creating the data for shaded area (e.g. using the type `StdDevAPop` and `StdDevGPop` ?

* Dimension of calculation should be for concentration and not dimensionsless

* Default point count for calculation should be 200

* Point count for observed data can be a smaller number (e.g. 10 or 15). This is different that the number above.

**Comment by msevestre** [comment]
Also X Axis points should also NOT always be the same (some random variation would be great here also)

![image](https://user-images.githubusercontent.com/1041237/27084812-3ce01f06-501b-11e7-8dbb-376afde85b32.png)

**Comment by msevestre** [comment]
Also a bit more range in the STD would be good. Right now, the bar are a bit to narrow

**Comment by msevestre** [comment]
LLOQ capability is required (for observed Data only, make sure we can create some curves with LLOQ)
