### ISSUE TITLE
Unit-Synonyms

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#890]
Feature-wish: allow unit-**synonyms** in the dimension factory.
This would allow to have alternative representations of some units e.g. when importing observed data.

Unit synonyms would be used only for identification of a unit; the software would still use the "main" units only.

E.g.:
- `"mcmol/ml"` and `"umol/ml"` could be defined as synonyms for `"µmol/ml"`
- when importing an observed data with such a unit
  - **UI unit** would be set to `"µmol/m"l` (the "main" unit for the given synonyme)
  - **internal unit** would be set - as always - to `"µmol/l"` (base unit of the OSP)

Unit synonyms could be defined in the dimension factory e.g. like this:
```
...
    <Dimension name="Amount" baseUnit="µmol">
      <BaseRepresentation lengthExponent="0" massExponent="0" timeExponent="0" electricCurrentExponent="0" temperatureExponent="0" amountExponent="1" luminousIntensityExponent="0" />
      <Units>
        <Unit name="mol" factor="1E6" />
        <Unit name="mmol" factor="1000" />
        <Unit name="µmol" factor="1" >
            <UnitSynonyms>
                <UnitSynonym name="mcmol" />
                <UnitSynonym name="umol" />
            </UnitSynonyms>
        </Unit>
        <Unit name="nmol" factor="0.001" />
        <Unit name="pmol" factor="1E-06" />
      </Units>
    </Dimension>
...
```

**Comment by Yuri05** [comment]
@msevestre @ju-rgen FYI

**Comment by msevestre** [comment]
I thought about this yesterday and a few more pointers:
1. It should be possible to set a unit using one of the synonym, at least via R script. e.g `setUnit(param, "umol")`
2. However, unit will always be displayed in our internal unit. I think this is an ok compromise. so getUnit(param) will return `µmol`

**Comment by msevestre** [comment]
@abdelr @georgeDaskalakis 
Another reason why it is crucial to not use another Dimension system for the importer.
