### ISSUE TITLE
Container criteria "in container" only applies for the children of the container

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#907]
@PavelBal commented on [Thu Nov 26 2020](https://github.com/Open-Systems-Pharmacology/MoBi/issues/523)

I would expect that setting the container criteria for e.g. a reaction or an event to "Intracellular" would create the reaction/event in the container itself and its descendants. Instead, only children container become the new entity.

Example: I have created a reaction "InContainer" with container criteria "In container: Intracellular" and a reaction "MatchTag" with container criteria "tagged with: Intracellular". I also did the same for the events.

In the simulation, only the reaction "MatchTag" is created in the comparments "Intracellular", but not the reaction "InContainer". The same is valid for the events - event "MatchTagEvent" is created in the container "Intracellular", event "InContainerEvent" is created in the Molecule-container under "Intracellular.

![image](https://user-images.githubusercontent.com/25903040/100347030-0b633780-2fe5-11eb-9f9f-3b9d60aec8e5.png)
[InContainerBug.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/5602700/InContainerBug.zip)

**Comment by msevestre** [comment]
@PavelBal
I think in your example, MatchTag shoould not be created beacuse there are not educt or product
Can you reproduce the behavior with a well defined reaction

**Comment by msevestre** [comment]
@PavelBal

Ok I can reproduce and I also understand what is going on. 
I think the behavior might be ok if we think about it

We are looking at an expression that should be fulfilled by the container where the reaction will be created. 
so In container "tagged with" Intracellular returns Intracellular

In container "in container Intracellular "does not return Intracellular because Intracellular is NOT in Intracellular (e.g. no parent in the hierarchy is called Intracellular")

Now we could extend the logic of "In Container" to return the container itself 
e.g. "is Intracellular in a container called Intracellular" could return yes. Right now it returned no. I think the behavior at the moment is correct.

@Yuri05 What do you think?

**Comment by PavelBal** [comment]
It might indeed work as intended, but the naming is unintuitive to me. If I define a reaction "in container intracellular", I would expect it to happen in Intracellular.

The current behavior can be left as is but it would require a proper documentation. At least a pop-up info showing whats the difference between "in container" and "tagged with".

**Comment by Yuri05** [comment]
_I think the behavior at the moment is correct._

I disagree. I would expect that "In Container" includes the container itself.

Then, if for some (unlikely) reason I would need to create something in all subcontainers of e.g. Liver but not in the Liver itself,
I could achieve this with "InContainer: Liver AND Not Match Tag: Liver" 
(well, currently it would not be possible because liver subcontainers have the tag "Liver" as well. But after - hopefully soon - we adjust our criteria conditions for transports etc. and remove those "parental" tags everywhere)

**Comment by PavelBal** [comment]
OK, then I would also prefer that "In Container" does include the container itself.

**Comment by msevestre** [comment]
@Yuri05  if we change the behavior, do you expect anything to break?

**Comment by Yuri05** [comment]
Looking at the current behaviour: it seems that the container itself is already used by "InContainer"??? 

E.g. for the lung blood flow formula: blood flows of all organs are defined at the organ level. If the organ istself would not be included by "InContainer", then the formula would be wrong - but it isn't. I'm lost...
![grafik](https://user-images.githubusercontent.com/25061876/110517578-52e08000-810b-11eb-8a5f-0b27a1036f59.png)

**Comment by msevestre** [comment]
You are not comparing the right thing here.
The container says: FOR ALL PARAMETER IN CONTAINER TISSUE_ORGAN. 

Above this was different. The criteria was applied to a CONTAINER (Intracellular) and the criteria was In Container Intracellular

Intracellular is NOT in container Intracellular. It IS Intracellular. I maintain that  `I disagree. I would expect that "In Container" includes the container itself.` is wrong

**Comment by msevestre** [comment]
EDIT: It is wrong at least `semantically`, A container is NOT IN ITSELF

**Comment by msevestre** [comment]
>Then, if for some (unlikely) reason I would need to create something in all subcontainers of e.g. Liver but not in the Liver itself,
I could achieve this with "InContainer: Liver AND Not Match Tag: Liver"

This is not the problem. The question is WHERE do you apply the criteria. 

If you apply the criteria to Liver and you say InContainer:Liver and Not Match tag Liver. It clearly is stupid
so you would endup with Liver and criteria InContainer:Liver

os the question. do you expect the question **IS LIVER IN LIVER to return TRUE OR FALSE**
