### ISSUE TITLE
Do not create container observer in "ForAll" scenario for non floating molecules

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#916]
@Yuri05 commented on [Fri Oct 23 2020](https://github.com/Open-Systems-Pharmacology/MoBi/issues/519)

If I export a simulation which contains proteins from PK-Sim to MoBi and recreate in MoBi, unnecessary empty molecule properties containers are created on organ level.
E.g. originally exported simulation looks like this (molecule properties for CYP3A4 only on **compartment** level, which is correct):
![grafik](https://user-images.githubusercontent.com/25061876/96997925-f8b39980-1532-11eb-9946-2bf1b0732745.png)
Creating new simulation from existing building blocks in MoBi produces empty CYP3A4-container on organ level:
![grafik](https://user-images.githubusercontent.com/25061876/96998013-154fd180-1533-11eb-9aaf-880099289f0e.png)

If such a simulation is then exported back to PK-Sim: editing of relative expressions crashes
![grafik](https://user-images.githubusercontent.com/25061876/96998228-61027b00-1533-11eb-9c3f-890b0f1c824b.png)
(I guess due to normalization, which tries to find relExp_Norm parameter in ALL CYP3A4-containers, which crashes then for those wrongly inserted empty containers.

---

@msevestre commented on [Fri Mar 12 2021](https://github.com/Open-Systems-Pharmacology/MoBi/issues/519#issuecomment-797751104)

Well well...it took me some times but it seems to be `by design`
In PKSim, observers are never ForAll. However, when we export to Mobi, some observers are set explicitly to ForAll=True
```
  public static IReadOnlyCollection<string> MoBiForAll => new[]
            {CONCENTRATION_IN_CONTAINER, FRACTION_EXCRETED_TO_URINE, TISSUE, PLASMA_PERIPHERAL_VENOUS_BLOOD, PLASMA_UNBOUND_PERIPHERAL_VENOUS_BLOOD};

```

One of them is Tissue
![image](https://user-images.githubusercontent.com/1041237/110997592-a214f380-834b-11eb-8d05-6303ddfc553f.png)

and that's why it is showing up here

I feel that ForAll should not apply to non floating molecule 

@Yuri05 @PavelBal @StephanSchaller Thoughts?

**Comment by msevestre** [comment]
This needs discussion here. I just wanted to try

**Comment by Yuri05** [comment]
>I feel that ForAll should not apply to non floating molecule 

Hard to say... no real opinion on this from my side...
