### ISSUE TITLE
Layout issues with the Importer

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#941]
- [x] Save Configuration button should use the same layout etcc as other buttons. Specifically, use an icon (save)
![image](https://user-images.githubusercontent.com/1041237/113044037-3c0dd600-916b-11eb-86c1-9fad0078f88f.png)

- [x] The import button is hidden. It is the main action of this view and I think it should be bottom right. 
- [ ] There is no Cancel button in the modal view
- [x] Still too much frame (maybe this was not fixed, better be safe than sorry)
![image](https://user-images.githubusercontent.com/1041237/113044244-6d86a180-916b-11eb-8fe1-173f9b78c126.png)

**Comment by georgeDaskalakis** [comment]
> * [ ]  There is no Cancel button in the modal view
But do we really need one? I would say adding one more button to this view would just make things more complicated for the user. The importer can be terminated by clicking the X button on the top right.
