### ISSUE TITLE
How can the user set the Molecule name after the import? 

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#943]
@Yuri05 @georgeDaskalakis @abdelr 
Is this something that is not supported? I forgot what was said.

![image](https://user-images.githubusercontent.com/1041237/113045357-bf7bf700-916c-11eb-8e68-bad10916000e.png)

Please close if this is by design

**Comment by PavelBal** [comment]
As I remember - this **should** be possible.
