### ISSUE TITLE
Source + file in meta data. Why

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#944]
![image](https://user-images.githubusercontent.com/1041237/113045573-04079280-916d-11eb-9277-dd1c26c57225.png)

Why do we have two properties that are the same?

Also I think Source is also part of some other DataInfo properties. Should we delete this and only use the Meta data for this?

**Comment by georgeDaskalakis** [comment]
You are right, this actually is a duplication. Both values are assigned from exactly the same variable. If nobody is against this, I will remove File, since it seems to make more functional sense to keep Source in DataInfo.

**Comment by Yuri05** [comment]
>If nobody is against this, I will remove File, since it seems to make more functional sense to keep Source in DataInfo.

Agree. 
@ju-rgen @christoph27 @sfrechen Do you see any problems?

**Comment by PavelBal** [comment]
Can "Source" be something else than a file?

**Comment by Yuri05** [comment]
could be an URL or (one day in the future) a database. I would go with Source

**Comment by PavelBal** [comment]
Yes, in this case I would also remove "File" and have the "Source" only.
