### ISSUE TITLE
Importer crashes if there is a missing mapped column

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/OSPSuite.Core#950]
If we map an excel column that is not present in one of the sheets of the excel and then try to import that sheet we get an unhandled exception (s. screenshot). 

![importer bug](https://user-images.githubusercontent.com/37107428/114846699-3952e800-9ddd-11eb-8bc1-29459fe560b2.png)

I would suggest as a solutio to this issue to catch the exception, show an error message to the user and prevent the import.

**Comment by PavelBal** [comment]
I agree with showing an error message and preventing the import.
