### ISSUE TITLE
Importer: Selecting a seperator for .csv files

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/OSPSuite.Core#952]
Currently .csv files are only read from the importer with "," as a separator. To change that I would suggest we give the user the option to select a separator on loading the file. I would propose not to pollute the importer dialog with even more controls, since the choice of separator is only relevant for .csv files and actually really only make sense on first loading the file. Most possibly a .csv file that someone tries to load with the wrong separator selected would result in an error (format not supported).

The proposed workflow would be:

After the file selection when starting the importer, if the user has selected a .csv file, a dialog pops up with the file path and underneath the possibility to select a separator for loading the file. If loading the file is unsuccessful, the user gets an error message and the user stays on the separator selection dialog. 

In the extreme case that a user succeeds to load a file with a wrong separator, he would have to open the file selection dialog and select the same file once again in order to be able to change the selected separator. For me this is not really a big problem, especially taking into account the very low probability of such a use case.

**Comment by PavelBal** [comment]
I support the proposal.

**Comment by Yuri05** [comment]
@twendl @ju-rgen @sfrechen @Sulav1 FYI

**Comment by Yuri05** [comment]
@georgeDaskalakis "Should have been closed" means this issue is fixed?
