### ISSUE TITLE
Problem with unit tests

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#956]
This type of tests is a little bit of a problem showing maybe an underlying issues with the component

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/tests/OSPSuite.Presentation.Tests/Importer/Presenters/ImporterPresenterSpecs.cs#L97

Specfically, the 
```
  A.Fake<IImporterView>(),
            mapper,
            A.Fake<IImporter>(),
            A.Fake<INanPresenter>(),
            importerPresenter,
            A.Fake<IImportConfirmationPresenter>(),
            A.Fake<IColumnMappingPresenter>(),
            A.Fake<ISourceFilePresenter>(),
            A.Fake<IDialogCreator>(),
            A.Fake<IDimensionFactory>(),
            A.Fake<IOSPSuiteXmlSerializerRepository>(),
            A.Fake<Utility.Container.IContainer>(),
```

Shows that the test is passing a bunch of Fake Object to the caller and never do anything with them. So it shows that a lot of the logic of the presenter is in fact not testing.

Does the component has too many dependencies? Maybe maybe not
Should our tests, test the interactions between all components. NO this is too brittle. 
Should our tests, test at least some behavior of the sut? YEs. Right now, each single dependencies is going to be faked and no expectations are set on those fakes. This is surprising to say the least

**Comment by abdelr** [comment]
Check these presenters thoroughly:
> ColumnMapping
> ImportConfirmation
> ImporterData
> Importer

And also these:
> ImporterReload
> MappingParameterEditor
> MetaDataParameterEditor
> SourceFile
> UnitsEditor
