### ISSUE TITLE
ConcurrentSimulationRunner - NumberOfCores is obsolete?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#966]
The implementation of `ConcurrentSimulationRunner` has a field `NumberOfCores`. I think this field is obsolete, as `SimulationRunOptions` already has has a property. `ConcurrentSimulationRunner` should get the value from `SimulationRunOptions` is the latter is set. Otherwise it is a redundant option the user has to set (or the caller from R).

**Comment by msevestre** [comment]
This is a very good point. I wanted to mention it to @abdelr and forgot about this as we were thinking about the implementation in general
