### ISSUE TITLE
SettingsForConcurrentRunSimulationBatch: Constructor with SimulationBatch

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#969]
I could not find a public constructor for `SettingsForConcurrentRunSimulationBatch` that I could call from R. From what I see in the code, the procedure would be:

1) Create an instance of `SettingsForConcurrentRunSimulationBatch`
2) Set simulation
3) Create and set `SimulationBatchOptions`
4) Add `SimulationBatchRunValues`

It would be good to have a constructor with an instance of `SimulationBatch` as an argument, as steps 2) and 3) are already implemented in R as part of creation of a `SimulationBatch`. I would even not expose the fields `simulation `and `SimulationBatchOptions`, as I do not see a use-case where these should be changed after the creation of `SettingsForConcurrentRunSimulationBatch`.

**Comment by msevestre** [comment]
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/src/OSPSuite.R/Services/ConcurrentSimulationRunner.cs#L17

There is a public constructor here. (if it's not there, it's assumed to be there without parameter)

**Comment by PavelBal** [comment]
Ah yes, forgot to provide the full namespace to the `clrNew`-caller.

**Comment by PavelBal** [comment]
This is done
