### ISSUE TITLE
Importer: Apply configuration: Naming pattern and "use filters.." option are lost

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#991]
I import the data from [Book 3.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6398562/Book.3.xlsx)
and save the configuration before importing [Config01.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6398570/Config01.zip)

![grafik](https://user-images.githubusercontent.com/25061876/116551261-07bb4000-a8f8-11eb-8e86-8a76757b0952.png)
![grafik](https://user-images.githubusercontent.com/25061876/116551314-1ace1000-a8f8-11eb-9f5c-52c4afeafe05.png)

Then I start another import, load the same file and load the saved configuration.
Mappings and Filters are correctly restored then, however:
- The option "Use filters for importing the data" is not selected anymore and
- The naming pattern has gone
![grafik](https://user-images.githubusercontent.com/25061876/116552519-692fde80-a8f9-11eb-9cf6-8a37ce64d934.png)
![grafik](https://user-images.githubusercontent.com/25061876/116552626-8795da00-a8f9-11eb-8f9a-cbe9d981729d.png)

**Comment by msevestre** [comment]
and what's with the alignments.... (left and top)

![image](https://user-images.githubusercontent.com/1041237/116554224-eee76600-a8c8-11eb-8e50-c0ae270d3482.png)

@georgeDaskalakis and @abdelr 
Do you want me to die of pain in the eye?

**Comment by Yuri05** [comment]
Works now for the option "Use filters for importing the data".
However the naming pattern is still ignored.
Tested with PK-Sim 10.0.135 (last nightly)
